# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[AiryBi, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:24`; `multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[AiryAi,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,AiryBi(_AnyFiniteOrdinaryPoint),AiryBi(1,_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),AiryBi(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:25`; SERIES(scale,MultiSeries:-`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[AiryBi, infinity, -1/3*Pi .. 1/3*Pi]:=proc (expr, scale, var, order, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:25`; res := `multiseries/add`([`multiseries/mul`([`multiseries/compose`(`multiseries/pow`(SERIES(scale,[1],0,integer,[1],infinity,integer,eval(scale['variable'],1),eval(scale['variable'],1)),1/2,scale,var,order),`multiseries/MulDoit`(`multiseries/pow`(expr,1/2,scale,var,order),-1),scale,var,order), MultiSeries:-`multiseries/function`[exp](`multiseries/MulDoit`(`multiseries/pow`(`multiseries/MulDoit`(`multiseries/pow`(expr,1/2,scale,var,order),-1),-3,scale,var,order),-2/3),scale,var,order), `multiseries/compose`(MultiSeries:-`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`](SERIES(scale,[1],0,integer,[1],infinity,integer,eval(scale['variable'],1),eval(scale['variable'],1)),scale,[eval(scale['variable'],1)],order),`multiseries/MulDoit`(`multiseries/pow`(expr,1/2,scale,var,order),-1),scale,var,order)])]) end proc:
`multiseries/function`[AiryBi]:=proc (expr, scale, var, order) local lim, lim2, asymptdir, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:26`; if expr = 0 then return `multiseries/Convert2SERIES`(AiryBi(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then if has(lim,exp) then asymptdir := op(select(type,lim,specfunc(anything,exp))) elif 1 < nops(lim) then asymptdir := argument(subs(infinity = 1,lim)) else asymptdir := 0 end if; lim := infinity else asymptdir := argument(lim) end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := `multiseries/function`[AiryBi,0](argseq) elif lim = infinity then if evalb(signum(-1/3*Pi-asymptdir) <> 1) and evalb(signum(1/3*Pi-asymptdir) <> -1) then res := `multiseries/function`[AiryBi,infinity,-1/3*Pi .. 1/3*Pi](argseq,[op(1,[argseq]), scale, var, order]) else error "unable to compute series" end if else res := eval(`multiseries/function`[AiryBi,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = AiryBi(op(9,expr)),res) end proc:
`multiseries/function`[AiryBi, 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:24`; `multiseries/compose`(SERIES(scale,MultiSeries:-`multiseries/function`[AiryAi,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,1/3*3^(5/6)/GAMMA(2/3),1/2*3^(2/3)/Pi*GAMMA(2/3),0),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),AiryBi(eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:25`; [MultiSeries:-`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:25`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := -I/Pi^(1/2); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:24`; if n = 0 then [1] elif n = 1 then [1, 0] elif n = 2 then [1, 0, 0] else loc[0] := 1; loc[1] := 0; loc[2] := 0; for i1 from 3 to n do loc[i1] := -(5-12*c+4*c^2+(8*c-12+4*i1)*i1)*loc[i1-3]/(16*c+16*i1) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:24`; `multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(_AnyFiniteOrdinaryPoint),diff(`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:25`; if expr = 0 then return `multiseries/Convert2SERIES`(`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:24`; [0, MultiSeries:-`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:25`; MultiSeries:-`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"CoeffProc"](n,0) end proc:
