# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[ChebyshevT, -1, "CoeffProc", 3/2]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:02`; MultiSeries:-`multiseries/function`[ChebyshevT,-1,"CoeffProc"](n,3/2,a1) end proc:
`multiseries/function`[ChebyshevT, -1, "BasisVector", 3/2]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:02`; [3/2, MultiSeries:-`multiseries/function`[ChebyshevT,-1,"CoeffProc"](n,3/2,a1)] end proc:
`multiseries/function`[ChebyshevT, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:57`; `multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[ChebyshevT,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,ChebyshevT(a1,_AnyFiniteOrdinaryPoint),-a1*_AnyFiniteOrdinaryPoint/(1-_AnyFiniteOrdinaryPoint^2)*ChebyshevT(a1,_AnyFiniteOrdinaryPoint)+a1/(1-_AnyFiniteOrdinaryPoint^2)*ChebyshevT(a1-1,_AnyFiniteOrdinaryPoint),a1,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),ChebyshevT(a1,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[ChebyshevT, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, a1, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:57`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] else loc[0] := arg0; loc[1] := arg1; for i1 from 2 to n do loc[i1] := (-(a1^2-4)*loc[i1-2]+3*xarg*loc[i1-1]-(4*loc[i1-2]+5*xarg*loc[i1-1]+(-loc[i1-2]-2*xarg*loc[i1-1])*i1)*i1)/(-1+xarg^2+(1-xarg^2)*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[ChebyshevT, 1, "CoeffProc", 1/2]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:59`; MultiSeries:-`multiseries/function`[ChebyshevT,1,"CoeffProc"](n,1/2,a1) end proc:
`multiseries/function`[ChebyshevT, infinity, "BasisVector", _a1, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:06`; [MultiSeries:-`multiseries/function`[ChebyshevT,infinity,"BasisVector",_a1,"MultiSeries",0](args)] end proc:
`multiseries/function`[ChebyshevT, 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:57`; `multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[ChebyshevT,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,cos(1/2*a1*Pi),a1*sin(1/2*a1*Pi),a1,0)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),ChebyshevT(a1,eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[ChebyshevT, 1, "BasisVector", 1/2, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:00`; [MultiSeries:-`multiseries/function`[ChebyshevT,1,"BasisVector",1/2,"MultiSeries",0](args)] end proc:
`multiseries/function`[ChebyshevT, -1, "BasisVector", 3/2, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:03`; [MultiSeries:-`multiseries/function`[ChebyshevT,-1,"BasisVector",3/2,"MultiSeries",0](args)] end proc:
`multiseries/function`[ChebyshevT]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:07`; if nops(exprlist) <> 2 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return `multiseries/Convert2SERIES`(ChebyshevT(paramseq,0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = -1 or Testzero(lim+1) then res := `multiseries/function`[ChebyshevT,-1](argseq) elif lim = 0 then res := `multiseries/function`[ChebyshevT,0](argseq) elif lim = 1 or Testzero(lim-1) then res := `multiseries/function`[ChebyshevT,1](argseq) elif lim = infinity then res := `multiseries/function`[ChebyshevT,infinity](argseq) else res := eval(`multiseries/function`[ChebyshevT,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = ChebyshevT(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[ChebyshevT, 1, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:00`; [MultiSeries:-`multiseries/function`[ChebyshevT,1,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[ChebyshevT, infinity, "BasisVector", -_a1, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:06`; [MultiSeries:-`multiseries/function`[ChebyshevT,infinity,"BasisVector",-_a1,"MultiSeries",0](args)] end proc:
`multiseries/function`[ChebyshevT, 1, "CoeffProc"]:=proc (n, c, a1) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:58`; if n = 0 then [normal(1)] else loc[0] := normal(1); for i1 to n do loc[i1] := normal(-(a1^2-c^2+2*c-1+(-2*c+2-i1)*i1)*loc[i1-1]/(c-2*c^2+(-4*c+1-2*i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[ChebyshevT, -1, "BasisVector", 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:01`; [0, MultiSeries:-`multiseries/function`[ChebyshevT,-1,"CoeffProc"](n,0,a1)] end proc:
`multiseries/function`[ChebyshevT, 1, "BasisVector", 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:58`; [0, MultiSeries:-`multiseries/function`[ChebyshevT,1,"CoeffProc"](n,0,a1)] end proc:
`multiseries/function`[ChebyshevT, infinity]:=proc (expr, scale, var, order, a1) local d1, loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:07`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[ChebyshevT,infinity,"BasisVector",_a1,"MultiSeries"](expr,scale,var,order,a1); loc2 := limit(2^(-d1-1),d1 = a1,'left'); res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],a1,loc2,infinity); loc1 := MultiSeries:-`multiseries/function`[ChebyshevT,infinity,"BasisVector",-_a1,"MultiSeries"](expr,scale,var,order,a1); loc2 := limit(2^(d1-1),d1 = a1,'left'); res2 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],-a1,loc2,infinity); res := `multiseries/add`([res1, res2]); subsop(9 = ChebyshevT(a1,op(9,expr)),res) end proc:
`multiseries/function`[ChebyshevT, 1, "BasisVector", 1/2]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:59`; [1/2, MultiSeries:-`multiseries/function`[ChebyshevT,1,"CoeffProc"](n,1/2,a1)] end proc:
`multiseries/function`[ChebyshevT, infinity, "CoeffProc"]:=proc (n, c, a1) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:04`; if n = 0 then [normal(1)] elif n = 1 then [normal(1), normal(0)] else loc[0] := normal(1); loc[1] := normal(0); for i1 from 2 to n do loc[i1] := normal(-(-3*c+2+c^2+(-3+2*c+i1)*i1)*loc[i1-2]/(a1^2-c^2+(-2*c-i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[ChebyshevT, -1, "CoeffProc", 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:01`; MultiSeries:-`multiseries/function`[ChebyshevT,-1,"CoeffProc"](n,0,a1) end proc:
`multiseries/function`[ChebyshevT, 1, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:59`; SERIES(scale,MultiSeries:-`multiseries/function`[ChebyshevT,1,"CoeffProc",0](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`ChebyshevT/1/BasisVector/0/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[ChebyshevT, -1, "CoeffProc"]:=proc (n, c, a1) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:01`; if n = 0 then [normal(1)] else loc[0] := normal(1); for i1 to n do loc[i1] := normal(-(a1^2-c^2+2*c-1+(-2*c+2-i1)*i1)*loc[i1-1]/(-c+2*c^2+(4*c-1+2*i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[ChebyshevT, -1, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:03`; [MultiSeries:-`multiseries/function`[ChebyshevT,-1,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[ChebyshevT, 1]:=proc (expr, scale, var, order, a1) local d1, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:00`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[ChebyshevT,1,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1); loc2 := limit(1,d1 = a1,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*ChebyshevT(a1,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,1); res := res1; subsop(9 = ChebyshevT(a1,op(9,expr)),res) end proc:
`multiseries/function`[ChebyshevT, -1, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:02`; SERIES(scale,MultiSeries:-`multiseries/function`[ChebyshevT,-1,"CoeffProc",0](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`ChebyshevT/-1/BasisVector/0/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[ChebyshevT, 1, "CoeffProc", 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:58`; MultiSeries:-`multiseries/function`[ChebyshevT,1,"CoeffProc"](n,0,a1) end proc:
`multiseries/function`[ChebyshevT, infinity, "BasisVector", _a1, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:05`; SERIES(scale,MultiSeries:-`multiseries/function`[ChebyshevT,infinity,"CoeffProc",_a1](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`ChebyshevT/infinity/BasisVector/_a1/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[ChebyshevT, 1, "BasisVector", 1/2, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:00`; SERIES(scale,MultiSeries:-`multiseries/function`[ChebyshevT,1,"CoeffProc",1/2](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`ChebyshevT/1/BasisVector/1/2/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[ChebyshevT, -1]:=proc (expr, scale, var, order, a1) local d1, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:04`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[ChebyshevT,-1,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1); loc2 := limit(cos(d1*Pi),d1 = a1,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*ChebyshevT(a1,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,-1); res := res1; subsop(9 = ChebyshevT(a1,op(9,expr)),res) end proc:
`multiseries/function`[ChebyshevT, infinity, "BasisVector", -_a1]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:05`; [-a1, MultiSeries:-`multiseries/function`[ChebyshevT,infinity,"CoeffProc"](n,-a1,a1)] end proc:
`multiseries/function`[ChebyshevT, infinity, "BasisVector", _a1]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:04`; [a1, MultiSeries:-`multiseries/function`[ChebyshevT,infinity,"CoeffProc"](n,a1,a1)] end proc:
`multiseries/function`[ChebyshevT, infinity, "CoeffProc", -_a1]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:05`; MultiSeries:-`multiseries/function`[ChebyshevT,infinity,"CoeffProc"](n,-a1,a1) end proc:
`multiseries/function`[ChebyshevT, -1, "BasisVector", 3/2, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:03`; SERIES(scale,MultiSeries:-`multiseries/function`[ChebyshevT,-1,"CoeffProc",3/2](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`ChebyshevT/-1/BasisVector/3/2/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[ChebyshevT, infinity, "CoeffProc", _a1]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:05`; MultiSeries:-`multiseries/function`[ChebyshevT,infinity,"CoeffProc"](n,a1,a1) end proc:
`multiseries/function`[ChebyshevT, infinity, "BasisVector", -_a1, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:13:06`; SERIES(scale,MultiSeries:-`multiseries/function`[ChebyshevT,infinity,"CoeffProc",-_a1](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`ChebyshevT/infinity/BasisVector/-_a1/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
