# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[CoulombF, 0, "CoeffProc", -_a2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:11`; MultiSeries:-`multiseries/function`[CoulombF,0,"CoeffProc"](n,-a2,a1,a2) end proc:
`multiseries/function`[`CoulombF/infinity/aux/0/-Pi .. Pi`, 0]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:16`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`CoulombF/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit(-1/2*I*exp(1/2*I*Pi*d2)*2^(I*d1)*signum(GAMMA(d2+1+I*d1)),d1 = a1,'left'),d2 = a2,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`CoulombF/infinity/aux/0/-Pi .. Pi`(a1,a2,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `CoulombF/infinity/aux/0/-Pi .. Pi`(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[CoulombF, 0, "BasisVector", -_a2, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:12`; [MultiSeries:-`multiseries/function`[CoulombF,0,"BasisVector",-_a2,"MultiSeries",0](args)] end proc:
`multiseries/function`[`CoulombF/infinity/aux/1/-Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c, a1, a2) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:17`; if n = 0 then [normal(1)] else loc[0] := normal(1); for i1 to n do loc[i1] := normal(-(-a2-I*a1-a1^2-a2^2-c+2*I*a1*c+c^2+(-1+2*c+2*I*a1+i1)*i1)*loc[i1-1]/(-2*I*c-2*I*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[CoulombF, 0, "BasisVector", -_a2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:11`; [-a2, MultiSeries:-`multiseries/function`[CoulombF,0,"CoeffProc"](n,-a2,a1,a2)] end proc:
`multiseries/function`[CoulombF, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, a1, a2, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:10`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, -1/2*arg0*(xarg^2-2*a1*xarg-a2^2-a2)/xarg^2] elif n = 3 then [arg0, arg1, -1/2*arg0*(xarg^2-2*a1*xarg-a2^2-a2)/xarg^2, -1/6/xarg^3*(2*arg0*a1*xarg+arg1*xarg^3-2*arg1*a1*xarg^2-arg1*a2^2*xarg-arg1*a2*xarg+2*arg0*a2^2+2*arg0*a2)] else loc[0] := arg0; loc[1] := arg1; loc[2] := -1/2*arg0*(xarg^2-2*a1*xarg-a2^2-a2)/xarg^2; loc[3] := -1/6/xarg^3*(2*arg0*a1*xarg+arg1*xarg^3-2*arg1*a1*xarg^2-arg1*a2^2*xarg-arg1*a2*xarg+2*arg0*a2^2+2*arg0*a2); for i1 from 4 to n do loc[i1] := (-loc[i1-4]-(2*xarg-2*a1)*loc[i1-3]-(xarg^2-2*a1*xarg-a2^2-a2+6)*loc[i1-2]-4*xarg*loc[i1-1]-(-5*loc[i1-2]-6*xarg*loc[i1-1]+(loc[i1-2]+2*xarg*loc[i1-1])*i1)*i1)/(-xarg^2+xarg^2*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[CoulombF, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:10`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[CoulombF,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,CoulombF(a1,a2,_AnyFiniteOrdinaryPoint),((a1+1)^2/_AnyFiniteOrdinaryPoint+a2)/(a1+1)*CoulombF(a1,a2,_AnyFiniteOrdinaryPoint)-((a1+1)^2+a2^2)^(1/2)*CoulombF(a1+1,a2,_AnyFiniteOrdinaryPoint)/(a1+1),a1,a2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),CoulombF(a1,a2,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[CoulombF, 0, "CoeffProc"]:=proc (n, c, a1, a2) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:10`; if n = 0 then [normal(1)] elif n = 1 then [normal(1), normal(-2*a1/(-c^2-c+a2^2+a2))] else loc[0] := normal(1); loc[1] := normal(-2*a1/(-c^2-c+a2^2+a2)); for i1 from 2 to n do loc[i1] := normal((-loc[i1-2]+2*a1*loc[i1-1])/(c^2-a2^2-a2-c+(2*c-1+i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`CoulombF/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:15`; [0, MultiSeries:-`multiseries/function`[`CoulombF/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0,a1,a2)] end proc:
`multiseries/function`[`CoulombF/infinity/aux/1/-Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:17`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`CoulombF/infinity/aux/1/-Pi .. Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`CoulombF/infinity/aux/1/-Pi .. Pi`(a1,a2,_AnyFiniteOrdinaryPoint),D[3](`CoulombF/infinity/aux/1/-Pi .. Pi`)(a1,a2,_AnyFiniteOrdinaryPoint),a1,a2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`CoulombF/infinity/aux/1/-Pi .. Pi`(a1,a2,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`CoulombF/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:14`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`CoulombF/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`CoulombF/infinity/aux/0/-Pi .. Pi`(a1,a2,_AnyFiniteOrdinaryPoint),D[3](`CoulombF/infinity/aux/0/-Pi .. Pi`)(a1,a2,_AnyFiniteOrdinaryPoint),a1,a2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`CoulombF/infinity/aux/0/-Pi .. Pi`(a1,a2,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`CoulombF/infinity/aux/1/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:19`; [MultiSeries:-`multiseries/function`[`CoulombF/infinity/aux/1/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[CoulombF, 0, "BasisVector", _a2+1]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:11`; [a2+1, MultiSeries:-`multiseries/function`[CoulombF,0,"CoeffProc"](n,a2+1,a1,a2)] end proc:
`multiseries/function`[`CoulombF/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:15`; MultiSeries:-`multiseries/function`[`CoulombF/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0,a1,a2) end proc:
`multiseries/function`[`CoulombF/infinity/aux/1/-Pi .. Pi`, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, a1, a2, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:16`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] else loc[0] := arg0; loc[1] := arg1; for i1 from 2 to n do loc[i1] := (-(2-3*I*a1-a2^2-a2-a1^2)*loc[i1-2]-(2*xarg+2*I-2*I*a1*xarg)*loc[i1-1]-((2*I*a1-3)*loc[i1-2]+(-2*I-4*xarg+2*I*a1*xarg)*loc[i1-1]+(loc[i1-2]+2*xarg*loc[i1-1])*i1)*i1)/(-xarg^2+xarg^2*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[CoulombF, 0, "BasisVector", _a2+1, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:13`; SERIES(scale,MultiSeries:-`multiseries/function`[CoulombF,0,"CoeffProc",_a2+1](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`CoulombF/0/BasisVector/_a2+1/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[`CoulombF/infinity/aux/1/-Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:18`; MultiSeries:-`multiseries/function`[`CoulombF/infinity/aux/1/-Pi .. Pi`,0,"CoeffProc"](n,0,a1,a2) end proc:
`multiseries/function`[`CoulombF/infinity/aux/1/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:18`; SERIES(scale,MultiSeries:-`multiseries/function`[`CoulombF/infinity/aux/1/-Pi .. Pi`,0,"CoeffProc",0](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`CoulombF/infinity/aux/1/-Pi .. Pi/0/BasisVector/0/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[`CoulombF/infinity/aux/1/-Pi .. Pi`, 0]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:19`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`CoulombF/infinity/aux/1/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit(-1/2*I*exp(-1/2*I*Pi*d2)/(2^(I*d1))*signum(GAMMA(d2+1+I*d1)),d1 = a1,'left'),d2 = a2,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`CoulombF/infinity/aux/1/-Pi .. Pi`(a1,a2,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `CoulombF/infinity/aux/1/-Pi .. Pi`(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[`CoulombF/infinity/aux/0/-Pi .. Pi`]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:16`; if nops(exprlist) <> 3 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`CoulombF/infinity/aux/0/-Pi .. Pi`(paramseq,0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`CoulombF/infinity/aux/0/-Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`CoulombF/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `CoulombF/infinity/aux/0/-Pi .. Pi`(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[CoulombF, 0, "BasisVector", -_a2, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:12`; SERIES(scale,MultiSeries:-`multiseries/function`[CoulombF,0,"CoeffProc",-_a2](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`CoulombF/0/BasisVector/-_a2/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[`CoulombF/infinity/aux/1/-Pi .. Pi`, 0, "BasisVector", 0]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:18`; [0, MultiSeries:-`multiseries/function`[`CoulombF/infinity/aux/1/-Pi .. Pi`,0,"CoeffProc"](n,0,a1,a2)] end proc:
`multiseries/function`[CoulombF]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:20`; if nops(exprlist) <> 3 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return `multiseries/Convert2SERIES`(CoulombF(paramseq,0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := `multiseries/function`[CoulombF,0](argseq) elif lim = infinity then res := `multiseries/function`[CoulombF,infinity,-Pi .. Pi](argseq,[[op(1 .. -2,exprlist), op(1,[argseq])], scale, var, order]) else res := eval(`multiseries/function`[CoulombF,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = CoulombF(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[`CoulombF/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c, a1, a2) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:14`; if n = 0 then [normal(1)] else loc[0] := normal(1); for i1 to n do loc[i1] := normal(-(-a2+I*a1-a1^2-a2^2-c-2*I*a1*c+c^2+(-1+2*c-2*I*a1+i1)*i1)*loc[i1-1]/(2*I*c+2*I*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`CoulombF/infinity/aux/1/-Pi .. Pi`]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:19`; if nops(exprlist) <> 3 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`CoulombF/infinity/aux/1/-Pi .. Pi`(paramseq,0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`CoulombF/infinity/aux/1/-Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`CoulombF/infinity/aux/1/-Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `CoulombF/infinity/aux/1/-Pi .. Pi`(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[CoulombF, 0]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:13`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[CoulombF,0,"BasisVector",_a2+1,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit(1/GAMMA(2*d2+2)*exp(-1/2*d1*Pi)*2^d2*(Re(GAMMA(d2+1+I*d1))^2+Im(GAMMA(d2+1+I*d1))^2)^(1/2),d1 = a1,'left'),d2 = a2,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*CoulombF(a1,a2,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],a2+1,loc2,0); res := res1; subsop(9 = CoulombF(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[`CoulombF/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:15`; SERIES(scale,MultiSeries:-`multiseries/function`[`CoulombF/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc",0](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`CoulombF/infinity/aux/0/-Pi .. Pi/0/BasisVector/0/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[CoulombF, infinity, -Pi .. Pi]:=proc (expr, scale, var, order, a1, a2, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:20`; res := MultiSeries:-`multiseries/add`([MultiSeries:-`multiseries/mul`([MultiSeries:-`multiseries/pow`(expr,-a1*RootOf(1+_Z^2,index = 1),scale,var,order), MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),-I),scale,var,order), MultiSeries:-`multiseries/function`[`CoulombF/infinity/aux/0/-Pi .. Pi`](op(arglist))]), MultiSeries:-`multiseries/mul`([MultiSeries:-`multiseries/pow`(expr,-a1*RootOf(1+_Z^2,index = 2),scale,var,order), MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),I),scale,var,order), MultiSeries:-`multiseries/function`[`CoulombF/infinity/aux/1/-Pi .. Pi`](op(arglist))])]) end proc:
`multiseries/function`[`CoulombF/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:16`; [MultiSeries:-`multiseries/function`[`CoulombF/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`CoulombF/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, a1, a2, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:14`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] else loc[0] := arg0; loc[1] := arg1; for i1 from 2 to n do loc[i1] := (-(2+3*I*a1-a2^2-a2-a1^2)*loc[i1-2]-(2*xarg-2*I+2*I*a1*xarg)*loc[i1-1]-((-2*I*a1-3)*loc[i1-2]+(2*I-4*xarg-2*I*a1*xarg)*loc[i1-1]+(loc[i1-2]+2*xarg*loc[i1-1])*i1)*i1)/(-xarg^2+xarg^2*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[CoulombF, 0, "CoeffProc", _a2+1]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:12`; MultiSeries:-`multiseries/function`[CoulombF,0,"CoeffProc"](n,a2+1,a1,a2) end proc:
`multiseries/function`[CoulombF, 0, "BasisVector", _a2+1, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:13`; [MultiSeries:-`multiseries/function`[CoulombF,0,"BasisVector",_a2+1,"MultiSeries",0](args)] end proc:
