# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[dilog, infinity, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:24`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/infinity/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, infinity, "CoeffProc", 0, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:23`; loc[0] := 1; loc[1] := 0; for i1 from 2 to n do loc[i1] := (i1-1)*loc[i1-1]/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[`dilog/0/BasisVector/0/0/0/MultiSeries/2`]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 01/27/2004 @ 15:23:13`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,1,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/0/BasisVector/0/0/0/MultiSeries/2`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`dilog/infinity/BasisVector/0/0/2/MultiSeries/2`]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 01/27/2004 @ 15:23:29`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/infinity/BasisVector/0/0/2/MultiSeries/2`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, infinity, "BasisVector", 0, 0, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:24`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/infinity/BasisVector/0/0/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`dilog/infinity/BasisVector/0/0/2/MultiSeries/1`]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 01/27/2004 @ 15:23:29`; SERIES(scale,2*MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/infinity/BasisVector/0/0/2/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, infinity, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:24`; [MultiSeries:-`multiseries/function`[dilog,infinity,"BasisVector",0,0,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[dilog, infinity, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:23`; [0, MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[`dilog/infinity/BasisVector/0/0/1/MultiSeries/1`]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 01/27/2004 @ 15:23:28`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/infinity/BasisVector/0/0/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`dilog/0/BasisVector/0/0/0/MultiSeries/0`]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 01/27/2004 @ 15:23:12`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,1,2](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/0/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog]:=proc (expr, scale, var, order) local tmp, re, im, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:25`; if expr = 0 then return `multiseries/Convert2SERIES`(dilog(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := `multiseries/function`[dilog,0](argseq) elif lim = 1 or Testzero(lim-1) then res := `multiseries/function`[dilog,1](argseq) elif lim = infinity then res := `multiseries/function`[dilog,infinity](argseq) else res := eval(`multiseries/function`[dilog,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; if _Envnobranchcut <> true then 
	if `multiseries/IsOnBranchCut`([0, -infinity],expr,scale,var) then userinfo(2,MultiSeries,`branchcut:`,dilog,[0, -infinity]);
		if lim = infinity then im := `multiseries/sign`(Im(`multiseries/MulSeriesCst`(expr,-1,algebraic))) 
		else im := `multiseries/sign`(Im(`multiseries/MulSeriesCst`(`multiseries/AddDoit`(expr,-lim),-1,algebraic))) end if;
		if lim<>infinity then
		if im=1 then
			userinfo(2,MultiSeries,`jump:`,dilog,`multiseries/run`(-2*Pi^2+2*I*Pi*ln(expr-1),scale,var,order));
			res := `multiseries/run`(-2*Pi^2+2*I*Pi*ln(expr-1)+res,scale,var,order)
		elif type(im,specfunc(anything,'signum')) or type(-im,specfunc(anything,signum)) then
			userinfo(2,MultiSeries,`jump:`,dilog,`multiseries/run`(1/2*(-im+1)*(-2*Pi^2+2*I*Pi*ln(expr-1)),scale,var,order));
			res := `multiseries/run`(1/2*(-im+1)*(-2*Pi^2+2*I*Pi*ln(expr-1))+res,scale,var,order)
		end if;
		else
		     if im=0 then
			userinfo(2,MultiSeries,`jump:`,dilog,`multiseries/run`(-2*Pi^2-2*I*Pi*ln(expr-1),scale,var,order));
			res := `multiseries/run`(-2*Pi^2-2*I*Pi*ln(expr-1)+res,scale,var,order)
		     fi
		fi
	end if end if; 
subsop(9 = dilog(op(9,expr)),res) end proc:
`multiseries/function`[dilog, 1, "CoeffProc", 1, 1, 2]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:20`; xxloc1 := MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,1,1](n); loc[0] := 4; loc[1] := 0; loc[2] := 0; for i1 from 3 to n do loc[i1] := ((-6*(i1-1)^2*op(i1,xxloc1)-2*(2*i1*(i1-1)+i1^2)*op(i1+1,xxloc1))/(i1-1)-(i1-1)^2*loc[i1-1])/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[dilog, 0, "BasisVector", 0, 1, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:19`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/0/BasisVector/0/1/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, infinity, "BasisVector", 0, 0, 2, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:25`; [MultiSeries:-`multiseries/function`[dilog,infinity,"BasisVector",0,0,2,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[dilog,infinity,"BasisVector",0,0,2,"MultiSeries",1](args), MultiSeries:-`multiseries/function`[dilog,infinity,"BasisVector",0,0,2,"MultiSeries",2](args)] end proc:
`multiseries/function`[dilog, 0, "CoeffProc", 1, 1, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:17`; [`$`(0,n+1)] end proc:
`multiseries/function`[dilog, 1, "BasisVector", 0, 0, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:22`; [MultiSeries:-`multiseries/function`[dilog,1,"BasisVector",0,0,1,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[dilog,1,"BasisVector",0,0,1,"MultiSeries",1](args), MultiSeries:-`multiseries/function`[dilog,1,"BasisVector",0,0,1,"MultiSeries",2](args)] end proc:
`multiseries/function`[dilog, infinity, "BasisVector", 0, 0, 2, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:25`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,2](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/infinity/BasisVector/0/0/2/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, 0, "BasisVector", 0, 1, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:19`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/0/BasisVector/0/1/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, infinity, "CoeffProc", 0, 0, 1]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:23`; xxloc1 := MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,0](n); loc[0] := 0; loc[1] := 1; for i1 from 2 to n do loc[i1] := -((-(2*i1*(i1-1)+i1^2)*op(i1,xxloc1)+3*i1^2*op(i1+1,xxloc1))/((i1-1)^2+2*i1-1)-(i1-1)*loc[i1-1])/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[dilog, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, arg2, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:16`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, 1/4*arg2] else loc[0] := arg0; loc[1] := arg1; loc[2] := 1/4*arg2; for i1 from 3 to n do loc[i1] := (-4*loc[i1-2]-(3*xarg-2)*loc[i1-1]-(-4*loc[i1-2]+(-5*xarg+3)*loc[i1-1]+(loc[i1-2]+(-1+2*xarg)*loc[i1-1])*i1)*i1)/(xarg-xarg^2+(-xarg+xarg^2)*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[dilog, 1, "BasisVector", 0, 0, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:21`; [0, MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,1,2](n), 2*MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,1,1](n), MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,1,0](n)] end proc:
`multiseries/function`[dilog, 1, "BasisVector", 0, 0, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:22`; SERIES(scale,2*MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,1,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/1/BasisVector/0/0/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, infinity, "BasisVector", 0, 0, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:24`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/infinity/BasisVector/0/0/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, 0, "CoeffProc", 1, 1, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:17`; [`$`(0,n+1)] end proc:
`multiseries/function`[dilog, 1, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:21`; [0, MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,1,1](n), MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,1,0](n)] end proc:
`multiseries/function`[dilog, 0, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:18`; [0, MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,1,2](n), 2*MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,1,1](n), MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,1,0](n)] end proc:
`multiseries/function`[dilog, infinity, "BasisVector", 0, 0, 2, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:25`; SERIES(scale,2*MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/infinity/BasisVector/0/0/2/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, 1, "CoeffProc", 1, 1, 1]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:20`; loc[0] := 1; loc[1] := 0; loc[2] := 0; for i1 from 3 to n do loc[i1] := -(i1-1)^2*loc[i1-1]/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[`dilog/1/BasisVector/0/0/1/MultiSeries/1`]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 01/27/2004 @ 15:23:21`; SERIES(scale,2*MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,1,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/1/BasisVector/0/0/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, 0, "BasisVector", 0, 1, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:19`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,0,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/0/BasisVector/0/1/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`dilog/0/BasisVector/0/1/0/MultiSeries/0`]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 01/27/2004 @ 15:23:13`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/0/BasisVector/0/1/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, infinity, "BasisVector", 0, 0, 2, "MultiSeries", 2]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:25`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/infinity/BasisVector/0/0/2/MultiSeries/2`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`dilog/0/BasisVector/0/1/1/MultiSeries/0`]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 01/27/2004 @ 15:23:14`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,0,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/0/BasisVector/0/1/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, infinity, "BasisVector", 0, 0, 2]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:24`; [0, MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,2](n), 2*MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,1](n), MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[dilog, 0, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:18`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,1,2](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/0/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`dilog/0/BasisVector/0/1/1/MultiSeries/1`]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 01/27/2004 @ 15:23:15`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/0/BasisVector/0/1/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`dilog/1/BasisVector/0/0/1/MultiSeries/0`]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 01/27/2004 @ 15:23:21`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,1,2](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/1/BasisVector/0/0/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, 0, "BasisVector", 0, 0, 0, "MultiSeries", 2]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:18`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,1,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/0/BasisVector/0/0/0/MultiSeries/2`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, infinity, "CoeffProc", 0, 0, 2]:=proc (n) local i1, loc, xxloc1, xxloc2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:23`; xxloc1 := MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,1](n); xxloc2 := MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,0](n); loc[0] := 0; loc[1] := -2; for i1 from 2 to n do loc[i1] := -((-2*(2*i1*(i1-1)+i1^2)*op(i1,xxloc1)+6*i1^2*op(i1+1,xxloc1)-(-2+6*i1)*op(i1,xxloc2)+6*i1*op(i1+1,xxloc2))/((i1-1)^2+2*i1-1)-(i1-1)*loc[i1-1])/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[dilog, 0, "CoeffProc", 1, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:17`; loc[0] := -2; loc[1] := -1; for i1 from 2 to n do loc[i1] := -i1*loc[i1-1]/(-i1-1) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[dilog, 0, "CoeffProc", 1, 0, 1]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:17`; xxloc1 := MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,0,0](n); loc[0] := -5; loc[1] := -3; for i1 from 2 to n do loc[i1] := ((-3*i1^2*op(i1,xxloc1)-(-i1^2-2*(i1+1)*i1)*op(i1+1,xxloc1))/((i1-1)^2+2*i1-1)-loc[i1-1]*i1)/(-i1-1) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[dilog, 1, "CoeffProc", 1, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:20`; loc[0] := 4; loc[1] := -1; for i1 from 2 to n do loc[i1] := -i1^2*loc[i1-1]/(1+(i1+2)*i1) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[dilog, infinity, "BasisVector", 0, 0, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:25`; [MultiSeries:-`multiseries/function`[dilog,infinity,"BasisVector",0,0,1,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[dilog,infinity,"BasisVector",0,0,1,"MultiSeries",1](args)] end proc:
`multiseries/function`[dilog, infinity, "BasisVector", 0, 0, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:24`; [0, MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,1](n), MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[dilog, 1, "CoeffProc", 1, 1, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:20`; [`$`(0,n+1)] end proc:
`multiseries/function`[dilog, 1, "BasisVector", 0, 0, 0, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:21`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,1,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/1/BasisVector/0/0/0/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, 1, "BasisVector", 0, 1, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:22`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/1/BasisVector/0/1/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, 0, "BasisVector", 0, 0, 0, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:18`; SERIES(scale,2*MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,1,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/0/BasisVector/0/0/0/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, 1, "BasisVector", 0, 0, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:21`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,1,2](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/1/BasisVector/0/0/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, 1, "BasisVector", 0, 0, 1, "MultiSeries", 2]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:22`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,1,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/1/BasisVector/0/0/1/MultiSeries/2`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`dilog/infinity/BasisVector/0/0/2/MultiSeries/0`]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 01/27/2004 @ 15:23:28`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,2](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/infinity/BasisVector/0/0/2/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`dilog/infinity/BasisVector/0/0/0/MultiSeries/0`]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 01/27/2004 @ 15:23:26`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/infinity/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, 0, "CoeffProc", 1, 1, 2]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:17`; loc[0] := -2; loc[1] := 0; loc[2] := 0; for i1 from 3 to n do loc[i1] := (i1-1)*loc[i1-1]/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[dilog, 0, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:18`; [MultiSeries:-`multiseries/function`[dilog,0,"BasisVector",0,0,0,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[dilog,0,"BasisVector",0,0,0,"MultiSeries",1](args), MultiSeries:-`multiseries/function`[dilog,0,"BasisVector",0,0,0,"MultiSeries",2](args)] end proc:
`multiseries/function`[dilog, 1, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:21`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,1,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/1/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`dilog/1/BasisVector/0/0/0/MultiSeries/1`]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 01/27/2004 @ 15:23:20`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,1,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/1/BasisVector/0/0/0/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, 0, "BasisVector", 0, 1, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:18`; [1, MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,0,1](n), MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,0,0](n)] end proc:
`multiseries/function`[`dilog/infinity/BasisVector/0/0/1/MultiSeries/0`]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 01/27/2004 @ 15:23:27`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,infinity,"CoeffProc",0,0,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/infinity/BasisVector/0/0/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, 0, "BasisVector", 0, 1, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:17`; [1, MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,0,0](n)] end proc:
`multiseries/function`[dilog, 1, "BasisVector", 0, 1, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:22`; [MultiSeries:-`multiseries/function`[dilog,1,"BasisVector",0,1,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[dilog, 0, "BasisVector", 0, 1, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:19`; [MultiSeries:-`multiseries/function`[dilog,0,"BasisVector",0,1,1,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[dilog,0,"BasisVector",0,1,1,"MultiSeries",1](args)] end proc:
`multiseries/function`[dilog, 0]:=proc (expr, scale, var, order) local loc1, loc2, loc3, res, res1, res2, res3; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:19`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc3 := MultiSeries:-`multiseries/MulSeriesCst`(expr,1,algebraic); loc1 := MultiSeries:-`multiseries/function`[dilog,0,"BasisVector",0,0,0,"MultiSeries"](loc3,scale,var,order); loc2 := -1/12*Pi^2; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[loc3, scale, var, order],0,loc2,0); loc1 := MultiSeries:-`multiseries/function`[dilog,0,"BasisVector",0,1,0,"MultiSeries"](loc3,scale,var,order); loc2 := 7/4; res2 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[loc3, scale, var, order],1,loc2,0); loc1 := MultiSeries:-`multiseries/function`[dilog,0,"BasisVector",0,1,1,"MultiSeries"](loc3,scale,var,order); loc2 := -1/2; res3 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[loc3, scale, var, order],1,loc2,0); res := MultiSeries:-`multiseries/add`([res1, res2, res3]); subsop(9 = dilog(op(9,expr)),res) end proc:
`multiseries/function`[`dilog/1/BasisVector/0/0/0/MultiSeries/0`]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 01/27/2004 @ 15:23:19`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,1,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/1/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, 1, "BasisVector", 0, 1, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:21`; [1, MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,0,0](n)] end proc:
`multiseries/function`[dilog, 0, "BasisVector", 0, 1, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:19`; [MultiSeries:-`multiseries/function`[dilog,0,"BasisVector",0,1,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`dilog/1/BasisVector/0/0/1/MultiSeries/2`]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 01/27/2004 @ 15:23:21`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,1,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/1/BasisVector/0/0/1/MultiSeries/2`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:16`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[dilog,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,dilog(_AnyFiniteOrdinaryPoint),ln(_AnyFiniteOrdinaryPoint)/(1-_AnyFiniteOrdinaryPoint),2/_AnyFiniteOrdinaryPoint/(1-_AnyFiniteOrdinaryPoint)+2*ln(_AnyFiniteOrdinaryPoint)/(1-_AnyFiniteOrdinaryPoint)^2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),dilog(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`dilog/1/BasisVector/0/1/0/MultiSeries/0`]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 01/27/2004 @ 15:23:22`; SERIES(scale,MultiSeries:-`multiseries/function`[dilog,1,"CoeffProc",1,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/1/BasisVector/0/1/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dilog, infinity]:=proc (expr, scale, var, order) local loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:25`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[dilog,infinity,"BasisVector",0,0,0,"MultiSeries"](expr,scale,var,order); loc2 := -1/6*Pi^2; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,infinity); loc1 := MultiSeries:-`multiseries/function`[dilog,infinity,"BasisVector",0,0,2,"MultiSeries"](expr,scale,var,order); loc2 := -1/2; res2 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,infinity); res := MultiSeries:-`multiseries/add`([res1, res2]); subsop(9 = dilog(op(9,expr)),res) end proc:
`multiseries/function`[dilog, 1]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:22`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[dilog,1,"BasisVector",0,1,0,"MultiSeries"](expr,scale,var,order); loc2 := -1/4; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*dilog(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],1,loc2,1); res := res1; subsop(9 = dilog(op(9,expr)),res) end proc:
`multiseries/function`[dilog, 1, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/07/2004 @ 17:18:21`; [MultiSeries:-`multiseries/function`[dilog,1,"BasisVector",0,0,0,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[dilog,1,"BasisVector",0,0,0,"MultiSeries",1](args)] end proc:
`multiseries/function`[`dilog/0/BasisVector/0/0/0/MultiSeries/1`]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 01/27/2004 @ 15:23:12`; SERIES(scale,2*MultiSeries:-`multiseries/function`[dilog,0,"CoeffProc",1,1,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dilog/0/BasisVector/0/0/0/MultiSeries/1`(eval(scale['variable'],1))) end proc:
