# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[EllipticCE, 1, "BasisVector", 0, 0, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:05`; [0, MultiSeries:-`multiseries/function`[EllipticCE,1,"CoeffProc",0,0,1](n), MultiSeries:-`multiseries/function`[EllipticCE,1,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[EllipticCE, 1, "CoeffProc", 0, 0, 1]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:04`; xxloc1 := MultiSeries:-`multiseries/function`[EllipticCE,1,"CoeffProc",0,0,0](n); loc[0] := 0; loc[1] := -1/2; loc[2] := -5/16; for i1 from 3 to n do loc[i1] := 1/2*(-2*(i1-2)*op(i1-1,xxloc1)-(-7+6*i1)*op(i1,xxloc1)-4*i1*op(i1+1,xxloc1)-3*loc[i1-2]-3*loc[i1-1]-(-4*loc[i1-2]-7*loc[i1-1]+(loc[i1-2]+3*loc[i1-1])*i1)*i1)/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticCE, -1]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:14`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[EllipticCE,-1,"BasisVector",0,0,0,"MultiSeries"](expr,scale,var,order); loc2 := 1/2*Pi; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*EllipticCE(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,-1); res := res1; subsop(9 = EllipticCE(op(9,expr)),res) end proc:
`multiseries/function`[EllipticCE, 1, "BasisVector", 0, 0, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:06`; [MultiSeries:-`multiseries/function`[EllipticCE,1,"BasisVector",0,0,1,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[EllipticCE,1,"BasisVector",0,0,1,"MultiSeries",1](args)] end proc:
`multiseries/function`[EllipticCE, 1, "BasisVector", 0, 0, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:06`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticCE,1,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCE/1/BasisVector/0/0/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCE]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:15`; if expr = 0 then return `multiseries/Convert2SERIES`(EllipticCE(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = -1 or Testzero(lim+1) then res := `multiseries/function`[EllipticCE,-1](argseq) elif lim = 0 then res := `multiseries/function`[EllipticCE,0](argseq) elif lim = 1 or Testzero(lim-1) then res := `multiseries/function`[EllipticCE,1](argseq) elif lim = infinity then res := `multiseries/function`[EllipticCE,infinity](argseq) else res := eval(`multiseries/function`[EllipticCE,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = EllipticCE(op(9,expr)),res) end proc:
`multiseries/function`[EllipticCE, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:59`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[EllipticCE,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,EllipticCE(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint/(1-_AnyFiniteOrdinaryPoint^2)*EllipticCK(_AnyFiniteOrdinaryPoint)-_AnyFiniteOrdinaryPoint/(1-_AnyFiniteOrdinaryPoint^2)*EllipticCE(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),EllipticCE(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[EllipticCE, infinity, "BasisVector", -1, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:10`; [MultiSeries:-`multiseries/function`[EllipticCE,infinity,"BasisVector",-1,0,0,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[EllipticCE,infinity,"BasisVector",-1,0,0,"MultiSeries",1](args)] end proc:
`multiseries/function`[EllipticCE, 0, "BasisVector", 0, 2, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:01`; [2, MultiSeries:-`multiseries/function`[EllipticCE,0,"CoeffProc",2,0,0](n)] end proc:
`multiseries/function`[EllipticCE, -1, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:12`; [0, MultiSeries:-`multiseries/function`[EllipticCE,-1,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[EllipticCE, infinity, "CoeffProc", 1, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:07`; loc[0] := 24; loc[1] := 0; loc[2] := 9; for i1 from 3 to n do loc[i1] := -(i1^2-1)*loc[i1-2]/i1/(-i1-2) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticCE, 0, "CoeffProc", 2, 2, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:00`; loc[0] := 0; loc[1] := 0; loc[2] := 1; loc[3] := 0; loc[4] := 3/8; for i1 from 5 to n do loc[i1] := -(3+(i1-4)*i1)*loc[i1-2]/i1/(-i1+2) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticCE, 1, "CoeffProc", 0, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:04`; loc[0] := 1; loc[1] := 1/2; loc[2] := 1/16; for i1 from 3 to n do loc[i1] := 1/2*(-3*loc[i1-2]-3*loc[i1-1]-(-4*loc[i1-2]-7*loc[i1-1]+(loc[i1-2]+3*loc[i1-1])*i1)*i1)/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticCE, 1, "BasisVector", 0, 0, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:06`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticCE,1,"CoeffProc",0,0,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCE/1/BasisVector/0/0/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCE, 0, "CoeffProc", 2, 2, 1]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:00`; xxloc1 := MultiSeries:-`multiseries/function`[EllipticCE,0,"CoeffProc",2,2,0](n); loc[0] := -2; loc[1] := 0; loc[2] := 0; loc[3] := 0; loc[4] := 7/32; for i1 from 5 to n do loc[i1] := (-2*(i1-2)*op(i1-1,xxloc1)-(2-2*i1)*op(i1+1,xxloc1)-(3+(i1-4)*i1)*loc[i1-2])/i1/(-i1+2) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticCE, 1, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:05`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticCE,1,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCE/1/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCE, 0, "CoeffProc", 2, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:59`; loc[0] := 24; loc[1] := 0; loc[2] := 9; for i1 from 3 to n do loc[i1] := -(i1^2-1)*loc[i1-2]/i1/(-i1-2) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticCE, -1, "BasisVector", 0, 0, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:13`; [0, MultiSeries:-`multiseries/function`[EllipticCE,-1,"CoeffProc",0,0,1](n), MultiSeries:-`multiseries/function`[EllipticCE,-1,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[EllipticCE, -1, "BasisVector", 0, 0, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:13`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticCE,-1,"CoeffProc",0,0,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCE/-1/BasisVector/0/0/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCE, infinity, "BasisVector", -1, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:09`; [-1, MultiSeries:-`multiseries/function`[EllipticCE,infinity,"CoeffProc",1,2,1](n), MultiSeries:-`multiseries/function`[EllipticCE,infinity,"CoeffProc",1,2,0](n)] end proc:
`multiseries/function`[EllipticCE, infinity, "BasisVector", -1, 0, 0, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:10`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticCE,infinity,"CoeffProc",1,2,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCE/infinity/BasisVector/-1/0/0/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCE, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:14:58`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, 1/2*(xarg*arg0-arg1-arg1*xarg^2)/(xarg^2-1)/xarg] else loc[0] := arg0; loc[1] := arg1; loc[2] := 1/2*(xarg*arg0-arg1-arg1*xarg^2)/(xarg^2-1)/xarg; for i1 from 3 to n do loc[i1] := (-8*loc[i1-3]-(5*xarg^2-3)*loc[i1-1]-13*xarg*loc[i1-2]-(-6*loc[i1-3]-13*xarg*loc[i1-2]+(-8*xarg^2+4)*loc[i1-1]+(3*xarg*loc[i1-2]+loc[i1-3]+(-1+3*xarg^2)*loc[i1-1])*i1)*i1)/(xarg-xarg^3+(-xarg+xarg^3)*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[EllipticCE, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:03`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[EllipticCE,0,"BasisVector",0,0,0,"MultiSeries"](expr,scale,var,order); loc2 := -1/2; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); loc1 := MultiSeries:-`multiseries/function`[EllipticCE,0,"BasisVector",0,2,0,"MultiSeries"](expr,scale,var,order); loc2 := 1/24*ln(2)-1/96; res2 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],2,loc2,0); res := MultiSeries:-`multiseries/add`([res1, res2]); subsop(9 = EllipticCE(op(9,expr)),res) end proc:
`multiseries/function`[EllipticCE, infinity, "CoeffProc", 1, 2, 1]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:08`; xxloc1 := MultiSeries:-`multiseries/function`[EllipticCE,infinity,"CoeffProc",1,2,0](n); loc[0] := -2; loc[1] := 0; loc[2] := 0; loc[3] := 0; loc[4] := 7/32; for i1 from 5 to n do loc[i1] := (-2*(i1-2)*op(i1-1,xxloc1)-(2-2*i1)*op(i1+1,xxloc1)-(3+(i1-4)*i1)*loc[i1-2])/i1/(-i1+2) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticCE, infinity, "BasisVector", -1, 2, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:10`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticCE,infinity,"CoeffProc",1,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCE/infinity/BasisVector/-1/2/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCE, infinity]:=proc (expr, scale, var, order) local loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:11`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[EllipticCE,infinity,"BasisVector",-1,0,0,"MultiSeries"](expr,scale,var,order); loc2 := -1/2; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],-1,loc2,infinity); loc1 := MultiSeries:-`multiseries/function`[EllipticCE,infinity,"BasisVector",-1,2,0,"MultiSeries"](expr,scale,var,order); loc2 := 1/24*ln(2)-1/96; res2 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],1,loc2,infinity); res := MultiSeries:-`multiseries/add`([res1, res2]); subsop(9 = EllipticCE(op(9,expr)),res) end proc:
`multiseries/function`[EllipticCE, -1, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:13`; [MultiSeries:-`multiseries/function`[EllipticCE,-1,"BasisVector",0,0,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[EllipticCE, infinity, "BasisVector", -1, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:09`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticCE,infinity,"CoeffProc",1,2,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCE/infinity/BasisVector/-1/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCE, -1, "CoeffProc", 0, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:12`; loc[0] := 1; loc[1] := -1/2; loc[2] := 1/16; for i1 from 3 to n do loc[i1] := 1/2*(-3*loc[i1-2]+3*loc[i1-1]-(-4*loc[i1-2]+7*loc[i1-1]+(loc[i1-2]-3*loc[i1-1])*i1)*i1)/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticCE, 1, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:05`; [MultiSeries:-`multiseries/function`[EllipticCE,1,"BasisVector",0,0,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[EllipticCE, 1]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:07`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[EllipticCE,1,"BasisVector",0,0,0,"MultiSeries"](expr,scale,var,order); loc2 := 1/2*Pi; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*EllipticCE(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,1); res := res1; subsop(9 = EllipticCE(op(9,expr)),res) end proc:
`multiseries/function`[EllipticCE, infinity, "BasisVector", -1, 2, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:10`; [MultiSeries:-`multiseries/function`[EllipticCE,infinity,"BasisVector",-1,2,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[EllipticCE, infinity, "CoeffProc", 1, 2, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:08`; loc[0] := 0; loc[1] := 0; loc[2] := 1; loc[3] := 0; loc[4] := 3/8; for i1 from 5 to n do loc[i1] := -(3+(i1-4)*i1)*loc[i1-2]/i1/(-i1+2) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticCE, infinity, "BasisVector", -1, 2, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:09`; [1, MultiSeries:-`multiseries/function`[EllipticCE,infinity,"CoeffProc",1,0,0](n)] end proc:
`multiseries/function`[EllipticCE, -1, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:13`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticCE,-1,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCE/-1/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCE, 0, "BasisVector", 0, 2, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:03`; [MultiSeries:-`multiseries/function`[EllipticCE,0,"BasisVector",0,2,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[EllipticCE, 0, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:01`; [0, MultiSeries:-`multiseries/function`[EllipticCE,0,"CoeffProc",2,2,1](n), MultiSeries:-`multiseries/function`[EllipticCE,0,"CoeffProc",2,2,0](n)] end proc:
`multiseries/function`[EllipticCE, 0, "BasisVector", 0, 2, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:02`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticCE,0,"CoeffProc",2,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCE/0/BasisVector/0/2/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCE, 1, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:04`; [0, MultiSeries:-`multiseries/function`[EllipticCE,1,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[EllipticCE, -1, "CoeffProc", 0, 0, 1]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:12`; xxloc1 := MultiSeries:-`multiseries/function`[EllipticCE,-1,"CoeffProc",0,0,0](n); loc[0] := 0; loc[1] := 1/2; loc[2] := -5/16; for i1 from 3 to n do loc[i1] := 1/2*(-2*(i1-2)*op(i1-1,xxloc1)-(7-6*i1)*op(i1,xxloc1)-4*i1*op(i1+1,xxloc1)-3*loc[i1-2]+3*loc[i1-1]-(-4*loc[i1-2]+7*loc[i1-1]+(loc[i1-2]-3*loc[i1-1])*i1)*i1)/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticCE, -1, "BasisVector", 0, 0, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:14`; [MultiSeries:-`multiseries/function`[EllipticCE,-1,"BasisVector",0,0,1,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[EllipticCE,-1,"BasisVector",0,0,1,"MultiSeries",1](args)] end proc:
`multiseries/function`[EllipticCE, -1, "BasisVector", 0, 0, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:14`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticCE,-1,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCE/-1/BasisVector/0/0/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCE, 0, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:02`; [MultiSeries:-`multiseries/function`[EllipticCE,0,"BasisVector",0,0,0,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[EllipticCE,0,"BasisVector",0,0,0,"MultiSeries",1](args)] end proc:
`multiseries/function`[EllipticCE, 0, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:01`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticCE,0,"CoeffProc",2,2,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCE/0/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCE, 0, "BasisVector", 0, 0, 0, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:02`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticCE,0,"CoeffProc",2,2,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCE/0/BasisVector/0/0/0/MultiSeries/1`(eval(scale['variable'],1))) end proc:
