# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[LommelS2, 0, "CoeffProc"]:=proc (n, c, a1, a2) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:35`; if n = 0 then [normal(1)] elif n = 1 then [normal(1), normal(0)] else loc[0] := normal(1); loc[1] := normal(0); for i1 from 2 to n do loc[i1] := normal(loc[i1-2]/(-c^2+a2^2+(-2*c-i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`LommelS2/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:41`; MultiSeries:-`multiseries/function`[`LommelS2/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0,a1,a2) end proc:
`multiseries/function`[`LommelS2/infinity/aux/0/-Pi .. Pi`, 0]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:42`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`LommelS2/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit(-1,d1 = a1,'left'),d2 = a2,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`LommelS2/infinity/aux/0/-Pi .. Pi`(a1,a2,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `LommelS2/infinity/aux/0/-Pi .. Pi`(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[LommelS2, 0, "BasisVector", _a1+1, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:39`; [MultiSeries:-`multiseries/function`[LommelS2,0,"BasisVector",_a1+1,"MultiSeries",0](args)] end proc:
`multiseries/function`[LommelS2, 0, "CoeffProc", _a1+1]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:37`; MultiSeries:-`multiseries/function`[LommelS2,0,"CoeffProc"](n,a1+1,a1,a2) end proc:
`multiseries/function`[LommelS2, 0, "BasisVector", -_a2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:36`; [-a2, MultiSeries:-`multiseries/function`[LommelS2,0,"CoeffProc"](n,-a2,a1,a2)] end proc:
`multiseries/function`[`LommelS2/infinity/aux/1/-Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:43`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`LommelS1/infinity/aux/2/-Pi .. Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`LommelS2/infinity/aux/1/-Pi .. Pi`(a1,a2,_AnyFiniteOrdinaryPoint),D[3](`LommelS2/infinity/aux/1/-Pi .. Pi`)(a1,a2,_AnyFiniteOrdinaryPoint),2*D[3,3](`LommelS2/infinity/aux/1/-Pi .. Pi`)(a1,a2,_AnyFiniteOrdinaryPoint),a1,a2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`LommelS2/infinity/aux/1/-Pi .. Pi`(a1,a2,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[LommelS2, 0, "BasisVector", _a1+1, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:39`; SERIES(scale,MultiSeries:-`multiseries/function`[LommelS2,0,"CoeffProc",_a1+1](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`LommelS2/0/BasisVector/_a1+1/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[LommelS2, 0, "BasisVector", -_a2, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:38`; SERIES(scale,MultiSeries:-`multiseries/function`[LommelS2,0,"CoeffProc",-_a2](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`LommelS2/0/BasisVector/-_a2/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[LommelS2]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:45`; if nops(exprlist) <> 3 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return `multiseries/Convert2SERIES`(LommelS2(paramseq,0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := `multiseries/function`[LommelS2,0](argseq) elif lim = infinity then res := `multiseries/function`[LommelS2,infinity,-Pi .. Pi](argseq,[[op(1 .. -2,exprlist), op(1,[argseq])], scale, var, order]) else res := eval(`multiseries/function`[LommelS2,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = LommelS2(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[LommelS2, 0, "CoeffProc", _a2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:36`; MultiSeries:-`multiseries/function`[LommelS2,0,"CoeffProc"](n,a2,a1,a2) end proc:
`multiseries/function`[`LommelS2/infinity/aux/1/-Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:44`; MultiSeries:-`multiseries/function`[`LommelS2/infinity/aux/1/-Pi .. Pi`,0,"CoeffProc"](n,0,a1,a2) end proc:
`multiseries/function`[LommelS2, 0, "BasisVector", _a2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:36`; [a2, MultiSeries:-`multiseries/function`[LommelS2,0,"CoeffProc"](n,a2,a1,a2)] end proc:
`multiseries/function`[`LommelS2/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:41`; SERIES(scale,MultiSeries:-`multiseries/function`[`LommelS2/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc",0](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`LommelS2/infinity/aux/0/-Pi .. Pi/0/BasisVector/0/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[LommelS2, 0, "BasisVector", _a2, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:37`; SERIES(scale,MultiSeries:-`multiseries/function`[LommelS2,0,"CoeffProc",_a2](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`LommelS2/0/BasisVector/_a2/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[`LommelS2/infinity/aux/1/-Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c, a1, a2) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:43`; if n = 0 then [normal(1)] elif n = 1 then [normal(1), normal(-1/8*I*(-4*a2^2+1+8*c+12*c^2+8*a1*c)/(c+1))] else loc[0] := normal(1); loc[1] := normal(-1/8*I*(-4*a2^2+1+8*c+12*c^2+8*a1*c)/(c+1)); for i1 from 2 to n do loc[i1] := normal((-(9-18*a1-30*c+8*a2^2*c+8*a1*a2^2-8*c^3-4*a2^2+24*a1*c+28*c^2-8*a1*c^2)*loc[i1-2]-(-8*I*a2^2+10*I-32*I*c+24*I*c^2+16*I*a1*c-16*I*a1)*loc[i1-1]-((-30+56*c+24*a1-16*a1*c+8*a2^2-24*c^2)*loc[i1-2]+(-32*I+48*I*c+16*I*a1)*loc[i1-1]+((-8*a1+28-24*c)*loc[i1-2]+24*I*loc[i1-1]-8*loc[i1-2]*i1)*i1)*i1)/(16*c+16*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`LommelS2/infinity/aux/1/-Pi .. Pi`, 0, "BasisVector", 0]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:43`; [0, MultiSeries:-`multiseries/function`[`LommelS2/infinity/aux/1/-Pi .. Pi`,0,"CoeffProc"](n,0,a1,a2)] end proc:
`multiseries/function`[`LommelS2/infinity/aux/1/-Pi .. Pi`]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:45`; if nops(exprlist) <> 3 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`LommelS2/infinity/aux/1/-Pi .. Pi`(paramseq,0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`LommelS2/infinity/aux/1/-Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`LommelS2/infinity/aux/1/-Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `LommelS2/infinity/aux/1/-Pi .. Pi`(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[`LommelS2/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c, a1, a2) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:40`; if n = 0 then [normal(1)] elif n = 1 then [normal(1), normal(0)] else loc[0] := normal(1); loc[1] := normal(0); for i1 from 2 to n do loc[i1] := normal((-c^2+2*c-1+2*a1*c+a2^2-2*a1-a1^2+(2+2*a1-2*c-i1)*i1)*loc[i1-2]) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[LommelS2, 0, "BasisVector", _a2, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:38`; [MultiSeries:-`multiseries/function`[LommelS2,0,"BasisVector",_a2,"MultiSeries",0](args)] end proc:
`multiseries/function`[`LommelS2/infinity/aux/1/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:44`; SERIES(scale,MultiSeries:-`multiseries/function`[`LommelS2/infinity/aux/1/-Pi .. Pi`,0,"CoeffProc",0](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`LommelS2/infinity/aux/1/-Pi .. Pi/0/BasisVector/0/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[`LommelS2/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:41`; [0, MultiSeries:-`multiseries/function`[`LommelS2/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0,a1,a2)] end proc:
`multiseries/function`[`LommelS2/infinity/aux/0/-Pi .. Pi`]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:42`; if nops(exprlist) <> 3 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`LommelS2/infinity/aux/0/-Pi .. Pi`(paramseq,0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`LommelS2/infinity/aux/0/-Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`LommelS2/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `LommelS2/infinity/aux/0/-Pi .. Pi`(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[LommelS2, 0]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1, res2, res3; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:39`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[LommelS2,0,"BasisVector",_a2,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit(2^(d1-d2-1)*cos(1/2*Pi*(d1+d2))*GAMMA(1/2*d1+1/2*d2+1/2)*GAMMA(1/2*d1-1/2*d2+1/2)*GAMMA(-d2)/Pi,d1 = a1,'left'),d2 = a2,'left'); res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],a2,loc2,0); loc1 := MultiSeries:-`multiseries/function`[LommelS2,0,"BasisVector",-_a2,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit(2^(d1+d2-1)*cos(1/2*(d1-d2)*Pi)*GAMMA(1/2*d1+1/2*d2+1/2)*GAMMA(1/2*d1-1/2*d2+1/2)*GAMMA(d2)/Pi,d1 = a1,'left'),d2 = a2,'left'); res2 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],-a2,loc2,0); loc1 := MultiSeries:-`multiseries/function`[LommelS2,0,"BasisVector",_a1+1,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit(1/(d2+d1+1)/(1-d2+d1),d1 = a1,'left'),d2 = a2,'left'); res3 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],a1+1,loc2,0); res := MultiSeries:-`multiseries/add`([res1, res2, res3]); subsop(9 = LommelS2(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[`LommelS2/infinity/aux/1/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:44`; [MultiSeries:-`multiseries/function`[`LommelS2/infinity/aux/1/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[LommelS2, infinity, -Pi .. Pi]:=proc (expr, scale, var, order, a1, a2, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:45`; res := MultiSeries:-`multiseries/add`([MultiSeries:-`multiseries/mul`([MultiSeries:-`multiseries/pow`(expr,1-a1,scale,var,order), MultiSeries:-`multiseries/function`[`LommelS2/infinity/aux/0/-Pi .. Pi`](op(arglist))]), MultiSeries:-`multiseries/mul`([MultiSeries:-`multiseries/pow`(expr,1/2,scale,var,order), MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),I),scale,var,order), MultiSeries:-`multiseries/function`[`LommelS2/infinity/aux/1/-Pi .. Pi`](op(arglist))])]) end proc:
`multiseries/function`[LommelS2, 0, "BasisVector", _a1+1]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:37`; [a1+1, MultiSeries:-`multiseries/function`[LommelS2,0,"CoeffProc"](n,a1+1,a1,a2)] end proc:
`multiseries/function`[`LommelS2/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:42`; [MultiSeries:-`multiseries/function`[`LommelS2/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[LommelS2, 0, "BasisVector", -_a2, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:38`; [MultiSeries:-`multiseries/function`[LommelS2,0,"BasisVector",-_a2,"MultiSeries",0](args)] end proc:
`multiseries/function`[`LommelS2/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:40`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`LommelS1/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`LommelS2/infinity/aux/0/-Pi .. Pi`(a1,a2,_AnyFiniteOrdinaryPoint),D[3](`LommelS2/infinity/aux/0/-Pi .. Pi`)(a1,a2,_AnyFiniteOrdinaryPoint),2*D[3,3](`LommelS2/infinity/aux/0/-Pi .. Pi`)(a1,a2,_AnyFiniteOrdinaryPoint),a1,a2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`LommelS2/infinity/aux/0/-Pi .. Pi`(a1,a2,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`LommelS2/infinity/aux/1/-Pi .. Pi`, 0]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:45`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`LommelS2/infinity/aux/1/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit((1-I)*2^(d1-1)*GAMMA(1/2*d1+1/2*d2+1/2)*GAMMA(1/2*d1-1/2*d2+1/2)*sin(1/2*d1*Pi)/Pi^(1/2),d1 = a1,'left'),d2 = a2,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`LommelS2/infinity/aux/1/-Pi .. Pi`(a1,a2,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `LommelS2/infinity/aux/1/-Pi .. Pi`(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[LommelS2, 0, "CoeffProc", -_a2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:37`; MultiSeries:-`multiseries/function`[LommelS2,0,"CoeffProc"](n,-a2,a1,a2) end proc:
`multiseries/function`[LommelS2, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:35`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[LommelS1,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,LommelS2(a1,a2,_AnyFiniteOrdinaryPoint),-a2/_AnyFiniteOrdinaryPoint*LommelS2(a1,a2,_AnyFiniteOrdinaryPoint)+(a1+a2-1)*LommelS2(a1-1,a2-1,_AnyFiniteOrdinaryPoint),2*a2/_AnyFiniteOrdinaryPoint^2*LommelS2(a1,a2,_AnyFiniteOrdinaryPoint)-2*a2/_AnyFiniteOrdinaryPoint*(-a2/_AnyFiniteOrdinaryPoint*LommelS2(a1,a2,_AnyFiniteOrdinaryPoint)+(a1+a2-1)*LommelS2(a1-1,a2-1,_AnyFiniteOrdinaryPoint))+2*(a1+a2-1)*(-(a2-1)/_AnyFiniteOrdinaryPoint*LommelS2(a1-1,a2-1,_AnyFiniteOrdinaryPoint)+(a1-3+a2)*LommelS2(-2+a1,-2+a2,_AnyFiniteOrdinaryPoint)),a1,a2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),LommelS2(a1,a2,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
