# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[`Shi/infinity/aux/2/-Pi .. Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:58`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Shi/infinity/aux/2/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := 1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Shi/infinity/aux/2/-Pi .. Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Shi/infinity/aux/2/-Pi .. Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Shi/infinity/aux/1/-Pi .. Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:54`; [0, MultiSeries:-`multiseries/function`[`Shi/infinity/aux/1/-Pi .. Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[Shi, 0, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:49`; [0, MultiSeries:-`multiseries/function`[Shi,0,"CoeffProc",1,1,1](n), MultiSeries:-`multiseries/function`[Shi,0,"CoeffProc",1,1,0](n)] end proc:
`multiseries/function`[Shi, 0, "BasisVector", 0, 0, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:51`; [MultiSeries:-`multiseries/function`[Shi,0,"BasisVector",0,0,1,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[Shi,0,"BasisVector",0,0,1,"MultiSeries",1](args), MultiSeries:-`multiseries/function`[Shi,0,"BasisVector",0,0,1,"MultiSeries",2](args)] end proc:
`multiseries/function`[`Shi/infinity/aux/1/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:54`; [MultiSeries:-`multiseries/function`[`Shi/infinity/aux/1/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[Shi, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:52`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[Shi,0,"BasisVector",0,1,0,"MultiSeries"](expr,scale,var,order); loc2 := 1/4; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*Shi(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],1,loc2,0); res := res1; subsop(9 = Shi(op(9,expr)),res) end proc:
`multiseries/function`[`Shi/infinity/aux/1/-Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:53`; if n = 0 then [1] elif n = 1 then [1, 3/2*c+1] else loc[0] := 1; loc[1] := 3/2*c+1; for i1 from 2 to n do loc[i1] := 1/2*(-c^2+2*c-1)*loc[i1-2]+1/2*(-1+3*c)*loc[i1-1]+1/2*((-2*c+2)*loc[i1-2]+3*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[Shi, 0, "BasisVector", 0, 1, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:52`; [MultiSeries:-`multiseries/function`[Shi,0,"BasisVector",0,1,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[Shi, 0, "CoeffProc", 1, 1, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:48`; [`$`(0,n+1)] end proc:
`multiseries/function`[`Shi/infinity/aux/2/-Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:56`; if n = 0 then [1] elif n = 1 then [1, -3/2*c-1] else loc[0] := 1; loc[1] := -3/2*c-1; for i1 from 2 to n do loc[i1] := 1/2*(-c^2+2*c-1)*loc[i1-2]+1/2*(1-3*c)*loc[i1-1]+1/2*((-2*c+2)*loc[i1-2]-3*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`Shi/infinity/aux/2/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:57`; [MultiSeries:-`multiseries/function`[`Shi/infinity/aux/2/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[Shi, 0, "CoeffProc", 1, 1, 2]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:48`; xxloc1 := MultiSeries:-`multiseries/function`[Shi,0,"CoeffProc",1,1,1](n); loc[0] := 4; loc[1] := 0; loc[2] := 1/2; loc[3] := 0; for i1 from 4 to n do loc[i1] := (2*op(i1-1,xxloc1)-2*(-i1+i1^2+i1*(2*i1-1))*op(i1+1,xxloc1)-(-i1+2)*loc[i1-2])/i1^2/(i1-1) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[Shi, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:46`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[Chi,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,Shi(_AnyFiniteOrdinaryPoint),sinh(_AnyFiniteOrdinaryPoint)/_AnyFiniteOrdinaryPoint,2*cosh(_AnyFiniteOrdinaryPoint)/_AnyFiniteOrdinaryPoint-2*sinh(_AnyFiniteOrdinaryPoint)/_AnyFiniteOrdinaryPoint^2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),Shi(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[Shi, 0, "CoeffProc", 1, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:47`; loc[0] := 4; loc[1] := 0; loc[2] := 2/9; for i1 from 3 to n do loc[i1] := -(1-i1)*loc[i1-2]/(1+(i1+2)*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[`Shi/infinity/aux/1/-Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:53`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Shi/infinity/aux/1/-Pi .. Pi`(_AnyFiniteOrdinaryPoint),diff(`Shi/infinity/aux/1/-Pi .. Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Shi/infinity/aux/1/-Pi .. Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Shi/infinity/aux/1/-Pi .. Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`Shi/infinity/aux/2/-Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:57`; MultiSeries:-`multiseries/function`[`Shi/infinity/aux/2/-Pi .. Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[Shi]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:58`; if expr = 0 then return `multiseries/Convert2SERIES`(Shi(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := `multiseries/function`[Shi,0](argseq) elif lim = infinity then res := `multiseries/function`[Shi,infinity,-Pi .. Pi](argseq,[op(1,[argseq]), scale, var, order]) else res := eval(`multiseries/function`[Shi,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = Shi(op(9,expr)),res) end proc:
`multiseries/function`[Shi, 0, "BasisVector", 0, 0, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:49`; [0, MultiSeries:-`multiseries/function`[Shi,0,"CoeffProc",1,1,2](n), 2*MultiSeries:-`multiseries/function`[Shi,0,"CoeffProc",1,1,1](n), MultiSeries:-`multiseries/function`[Shi,0,"CoeffProc",1,1,0](n)] end proc:
`multiseries/function`[Shi, 0, "BasisVector", 0, 0, 1, "MultiSeries", 2]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:51`; SERIES(scale,MultiSeries:-`multiseries/function`[Shi,0,"CoeffProc",1,1,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Shi/0/BasisVector/0/0/1/MultiSeries/2`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Shi/infinity/aux/2/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:57`; SERIES(scale,MultiSeries:-`multiseries/function`[`Shi/infinity/aux/2/-Pi .. Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Shi/infinity/aux/2/-Pi .. Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Shi/infinity/aux/1/-Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:54`; MultiSeries:-`multiseries/function`[`Shi/infinity/aux/1/-Pi .. Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[Shi, 0, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:49`; SERIES(scale,MultiSeries:-`multiseries/function`[Shi,0,"CoeffProc",1,1,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Shi/0/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Shi/infinity/aux/2/-Pi .. Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:58`; if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`Shi/infinity/aux/2/-Pi .. Pi`(0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Shi/infinity/aux/2/-Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Shi/infinity/aux/2/-Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Shi/infinity/aux/2/-Pi .. Pi`(op(9,expr)),res) end proc:
`multiseries/function`[Shi, 0, "BasisVector", 0, 0, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:50`; SERIES(scale,MultiSeries:-`multiseries/function`[Shi,0,"CoeffProc",1,1,2](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Shi/0/BasisVector/0/0/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Shi, 0, "CoeffProc", 1, 1, 1]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:48`; loc[0] := 1; loc[1] := 0; loc[2] := 0; loc[3] := 0; for i1 from 4 to n do loc[i1] := -(-i1+2)*loc[i1-2]/i1^2/(i1-1) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[Shi, 0, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:50`; [MultiSeries:-`multiseries/function`[Shi,0,"BasisVector",0,0,0,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[Shi,0,"BasisVector",0,0,0,"MultiSeries",1](args)] end proc:
`multiseries/function`[`Shi/infinity/aux/1/-Pi .. Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:55`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Shi/infinity/aux/1/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := 1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Shi/infinity/aux/1/-Pi .. Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Shi/infinity/aux/1/-Pi .. Pi`(op(9,expr)),res) end proc:
`multiseries/function`[Shi, 0, "BasisVector", 0, 1, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:48`; [1, MultiSeries:-`multiseries/function`[Shi,0,"CoeffProc",1,0,0](n)] end proc:
`multiseries/function`[`Shi/infinity/aux/1/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:54`; SERIES(scale,MultiSeries:-`multiseries/function`[`Shi/infinity/aux/1/-Pi .. Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Shi/infinity/aux/1/-Pi .. Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Shi/infinity/aux/2/-Pi .. Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:56`; [0, MultiSeries:-`multiseries/function`[`Shi/infinity/aux/2/-Pi .. Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`Shi/infinity/aux/1/-Pi .. Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:55`; if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`Shi/infinity/aux/1/-Pi .. Pi`(0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Shi/infinity/aux/1/-Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Shi/infinity/aux/1/-Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Shi/infinity/aux/1/-Pi .. Pi`(op(9,expr)),res) end proc:
`multiseries/function`[Shi, 0, "BasisVector", 0, 1, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:52`; SERIES(scale,MultiSeries:-`multiseries/function`[Shi,0,"CoeffProc",1,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Shi/0/BasisVector/0/1/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Shi, 0, "BasisVector", 0, 0, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:51`; SERIES(scale,2*MultiSeries:-`multiseries/function`[Shi,0,"CoeffProc",1,1,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Shi/0/BasisVector/0/0/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Shi, 0, "BasisVector", 0, 0, 0, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:50`; SERIES(scale,MultiSeries:-`multiseries/function`[Shi,0,"CoeffProc",1,1,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Shi/0/BasisVector/0/0/0/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Shi, infinity, -Pi .. Pi]:=proc (expr, scale, var, order, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:58`; res := MultiSeries:-`multiseries/add`([MultiSeries:-`multiseries/Convert2SERIES`(-1/2*I*Pi,scale,var,false), MultiSeries:-`multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),1),scale,var,order), MultiSeries:-`multiseries/function`[`Shi/infinity/aux/1/-Pi .. Pi`](op(arglist))]), MultiSeries:-`multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),-1),scale,var,order), MultiSeries:-`multiseries/function`[`Shi/infinity/aux/2/-Pi .. Pi`](op(arglist))])]) end proc:
`multiseries/function`[`Shi/infinity/aux/2/-Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:55`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Shi/infinity/aux/2/-Pi .. Pi`(_AnyFiniteOrdinaryPoint),diff(`Shi/infinity/aux/2/-Pi .. Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Shi/infinity/aux/2/-Pi .. Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Shi/infinity/aux/2/-Pi .. Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
