# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[Si, infinity, -Pi .. -1/2*Pi]:=proc (expr, scale, var, order, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:17`; res := MultiSeries:-`multiseries/add`([MultiSeries:-`multiseries/Convert2SERIES`(-1/2*Pi,scale,var,false), MultiSeries:-`multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),-I),scale,var,order), MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/-Pi .. -1/2*Pi`](op(arglist))]), MultiSeries:-`multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),I),scale,var,order), MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/-Pi .. -1/2*Pi`](op(arglist))])]) end proc:
`multiseries/function`[Si, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:19:59`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[Ci,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,Si(_AnyFiniteOrdinaryPoint),sin(_AnyFiniteOrdinaryPoint)/_AnyFiniteOrdinaryPoint,2*cos(_AnyFiniteOrdinaryPoint)/_AnyFiniteOrdinaryPoint-2*sin(_AnyFiniteOrdinaryPoint)/_AnyFiniteOrdinaryPoint^2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),Si(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`Si/infinity/aux/1/-Pi .. -1/2*Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:14`; [MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/-Pi .. -1/2*Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`Si/infinity/aux/2/1/2*Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:21`; if n = 0 then [1] elif n = 1 then [1, -3/2*I*c-I] else loc[0] := 1; loc[1] := -3/2*I*c-I; for i1 from 2 to n do loc[i1] := -1/2*(-c^2+2*c-1)*loc[i1-2]-1/2*(-I+3*I*c)*loc[i1-1]-1/2*((-2*c+2)*loc[i1-2]+3*I*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`Si/infinity/aux/1/-Pi .. -1/2*Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:12`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Ci/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Si/infinity/aux/1/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint),diff(`Si/infinity/aux/1/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Si/infinity/aux/1/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Si/infinity/aux/1/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`Si/infinity/aux/2/1/2*Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:22`; MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/1/2*Pi .. Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:10`; [MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`Si/infinity/aux/1/-Pi .. -1/2*Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:12`; if n = 0 then [1] elif n = 1 then [1, 3/2*I*c+I] else loc[0] := 1; loc[1] := 3/2*I*c+I; for i1 from 2 to n do loc[i1] := -1/2*(-c^2+2*c-1)*loc[i1-2]-1/2*(I-3*I*c)*loc[i1-1]-1/2*((-2*c+2)*loc[i1-2]-3*I*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[Si, 0, "CoeffProc", 1, 1, 1]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:01`; loc[0] := 1; loc[1] := 0; loc[2] := 0; loc[3] := 0; for i1 from 4 to n do loc[i1] := -(i1-2)*loc[i1-2]/i1^2/(i1-1) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[Si, infinity, -1/2*Pi .. 1/2*Pi]:=proc (expr, scale, var, order, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:11`; res := MultiSeries:-`multiseries/add`([MultiSeries:-`multiseries/Convert2SERIES`(1/2*Pi,scale,var,false), MultiSeries:-`multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),-I),scale,var,order), MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`](op(arglist))]), MultiSeries:-`multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),I),scale,var,order), MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`](op(arglist))])]) end proc:
`multiseries/function`[`Si/infinity/aux/2/-Pi .. -1/2*Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:17`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/-Pi .. -1/2*Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := -1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Si/infinity/aux/2/-Pi .. -1/2*Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Si/infinity/aux/2/-Pi .. -1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:08`; [MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`Si/infinity/aux/2/1/2*Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:22`; [MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/1/2*Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:10`; SERIES(scale,MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Si/infinity/aux/1/1/2*Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:19`; [MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/1/2*Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[Si, 0, "CoeffProc", 1, 1, 2]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:01`; xxloc1 := MultiSeries:-`multiseries/function`[Si,0,"CoeffProc",1,1,1](n); loc[0] := 4; loc[1] := 0; loc[2] := -1/2; loc[3] := 0; for i1 from 4 to n do loc[i1] := (-2*op(i1-1,xxloc1)-2*(-i1+i1^2+i1*(2*i1-1))*op(i1+1,xxloc1)-(i1-2)*loc[i1-2])/i1^2/(i1-1) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[`Si/infinity/aux/2/-Pi .. -1/2*Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:15`; [0, MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/-Pi .. -1/2*Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`Si/infinity/aux/1/1/2*Pi .. Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:19`; [0, MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/1/2*Pi .. Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`Si/infinity/aux/1/-Pi .. -1/2*Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:13`; [0, MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/-Pi .. -1/2*Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:11`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := -1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Si/infinity/aux/2/-Pi .. -1/2*Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:16`; [MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/-Pi .. -1/2*Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`Si/infinity/aux/1/-Pi .. -1/2*Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:14`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/-Pi .. -1/2*Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := -1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Si/infinity/aux/1/-Pi .. -1/2*Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Si/infinity/aux/1/-Pi .. -1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Si/infinity/aux/1/1/2*Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:18`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Ci/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Si/infinity/aux/1/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint),diff(`Si/infinity/aux/1/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Si/infinity/aux/1/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Si/infinity/aux/1/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:09`; if n = 0 then [1] elif n = 1 then [1, -3/2*I*c-I] else loc[0] := 1; loc[1] := -3/2*I*c-I; for i1 from 2 to n do loc[i1] := -1/2*(-c^2+2*c-1)*loc[i1-2]-1/2*(-I+3*I*c)*loc[i1-1]-1/2*((-2*c+2)*loc[i1-2]+3*I*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[Si, 0, "BasisVector", 0, 1, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:05`; [MultiSeries:-`multiseries/function`[Si,0,"BasisVector",0,1,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`Si/infinity/aux/1/1/2*Pi .. Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:20`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/1/2*Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := -1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Si/infinity/aux/1/1/2*Pi .. Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Si/infinity/aux/1/1/2*Pi .. Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Si/infinity/aux/1/-Pi .. -1/2*Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:13`; MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/-Pi .. -1/2*Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[Si, 0, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:02`; [0, MultiSeries:-`multiseries/function`[Si,0,"CoeffProc",1,1,1](n), MultiSeries:-`multiseries/function`[Si,0,"CoeffProc",1,1,0](n)] end proc:
`multiseries/function`[Si, 0, "CoeffProc", 1, 1, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:01`; [`$`(0,n+1)] end proc:
`multiseries/function`[`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:08`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := -1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Si/infinity/aux/2/1/2*Pi .. Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:23`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/1/2*Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := -1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Si/infinity/aux/2/1/2*Pi .. Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Si/infinity/aux/2/1/2*Pi .. Pi`(op(9,expr)),res) end proc:
`multiseries/function`[Si, 0, "BasisVector", 0, 0, 0, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:03`; SERIES(scale,MultiSeries:-`multiseries/function`[Si,0,"CoeffProc",1,1,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Si/0/BasisVector/0/0/0/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Si, 0, "BasisVector", 0, 0, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:02`; [0, MultiSeries:-`multiseries/function`[Si,0,"CoeffProc",1,1,2](n), 2*MultiSeries:-`multiseries/function`[Si,0,"CoeffProc",1,1,1](n), MultiSeries:-`multiseries/function`[Si,0,"CoeffProc",1,1,0](n)] end proc:
`multiseries/function`[Si, 0, "BasisVector", 0, 0, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:03`; SERIES(scale,MultiSeries:-`multiseries/function`[Si,0,"CoeffProc",1,1,2](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Si/0/BasisVector/0/0/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Si/infinity/aux/2/1/2*Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:22`; SERIES(scale,MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/1/2*Pi .. Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Si/infinity/aux/2/1/2*Pi .. Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Si/infinity/aux/2/-Pi .. -1/2*Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:16`; MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/-Pi .. -1/2*Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:07`; SERIES(scale,MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Si/infinity/aux/2/-Pi .. -1/2*Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:15`; if n = 0 then [1] elif n = 1 then [1, -3/2*I*c-I] else loc[0] := 1; loc[1] := -3/2*I*c-I; for i1 from 2 to n do loc[i1] := -1/2*(-c^2+2*c-1)*loc[i1-2]-1/2*(-I+3*I*c)*loc[i1-1]-1/2*((-2*c+2)*loc[i1-2]+3*I*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`Si/infinity/aux/1/1/2*Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:18`; if n = 0 then [1] elif n = 1 then [1, 3/2*I*c+I] else loc[0] := 1; loc[1] := 3/2*I*c+I; for i1 from 2 to n do loc[i1] := -1/2*(-c^2+2*c-1)*loc[i1-2]-1/2*(I-3*I*c)*loc[i1-1]-1/2*((-2*c+2)*loc[i1-2]-3*I*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`Si/infinity/aux/2/1/2*Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:21`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Ci/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Si/infinity/aux/2/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint),diff(`Si/infinity/aux/2/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Si/infinity/aux/2/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Si/infinity/aux/2/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[Si, 0, "BasisVector", 0, 1, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:05`; SERIES(scale,MultiSeries:-`multiseries/function`[Si,0,"CoeffProc",1,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Si/0/BasisVector/0/1/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Si/infinity/aux/2/-Pi .. -1/2*Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:16`; SERIES(scale,MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/-Pi .. -1/2*Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Si/infinity/aux/2/-Pi .. -1/2*Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Si/infinity/aux/2/-Pi .. -1/2*Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:17`; if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`Si/infinity/aux/2/-Pi .. -1/2*Pi`(0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/-Pi .. -1/2*Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/-Pi .. -1/2*Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Si/infinity/aux/2/-Pi .. -1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:06`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Ci/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint),diff(`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`Si/infinity/aux/1/1/2*Pi .. Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:20`; if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`Si/infinity/aux/1/1/2*Pi .. Pi`(0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/1/2*Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/1/2*Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Si/infinity/aux/1/1/2*Pi .. Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:06`; if n = 0 then [1] elif n = 1 then [1, 3/2*I*c+I] else loc[0] := 1; loc[1] := 3/2*I*c+I; for i1 from 2 to n do loc[i1] := -1/2*(-c^2+2*c-1)*loc[i1-2]-1/2*(I-3*I*c)*loc[i1-1]-1/2*((-2*c+2)*loc[i1-2]-3*I*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[Si, 0, "BasisVector", 0, 1, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:01`; [1, MultiSeries:-`multiseries/function`[Si,0,"CoeffProc",1,0,0](n)] end proc:
`multiseries/function`[Si, 0, "CoeffProc", 1, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:00`; loc[0] := 4; loc[1] := 0; loc[2] := -2/9; for i1 from 3 to n do loc[i1] := -(i1-1)*loc[i1-2]/(1+(i1+2)*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[Si, 0, "BasisVector", 0, 0, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:04`; SERIES(scale,2*MultiSeries:-`multiseries/function`[Si,0,"CoeffProc",1,1,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Si/0/BasisVector/0/0/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Si/infinity/aux/1/-Pi .. -1/2*Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:14`; if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`Si/infinity/aux/1/-Pi .. -1/2*Pi`(0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/-Pi .. -1/2*Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/-Pi .. -1/2*Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Si/infinity/aux/1/-Pi .. -1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Si/infinity/aux/1/1/2*Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:19`; MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/1/2*Pi .. Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:09`; [0, MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:08`; if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:09`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Ci/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint),diff(`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:07`; MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[`Si/infinity/aux/1/-Pi .. -1/2*Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:13`; SERIES(scale,MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/-Pi .. -1/2*Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Si/infinity/aux/1/-Pi .. -1/2*Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:07`; [0, MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:10`; MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:11`; if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`(0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Si/infinity/aux/2/-1/2*Pi .. 1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[Si, infinity, 1/2*Pi .. Pi]:=proc (expr, scale, var, order, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:23`; res := MultiSeries:-`multiseries/add`([MultiSeries:-`multiseries/Convert2SERIES`(-1/2*Pi,scale,var,false), MultiSeries:-`multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),-I),scale,var,order), MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/1/2*Pi .. Pi`](op(arglist))]), MultiSeries:-`multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),I),scale,var,order), MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/1/2*Pi .. Pi`](op(arglist))])]) end proc:
`multiseries/function`[Si, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:05`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[Si,0,"BasisVector",0,1,0,"MultiSeries"](expr,scale,var,order); loc2 := 1/4; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*Si(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],1,loc2,0); res := res1; subsop(9 = Si(op(9,expr)),res) end proc:
`multiseries/function`[Si, 0, "BasisVector", 0, 0, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:04`; [MultiSeries:-`multiseries/function`[Si,0,"BasisVector",0,0,1,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[Si,0,"BasisVector",0,0,1,"MultiSeries",1](args), MultiSeries:-`multiseries/function`[Si,0,"BasisVector",0,0,1,"MultiSeries",2](args)] end proc:
`multiseries/function`[`Si/infinity/aux/2/1/2*Pi .. Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:23`; if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`Si/infinity/aux/2/1/2*Pi .. Pi`(0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/1/2*Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/1/2*Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Si/infinity/aux/2/1/2*Pi .. Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Si/infinity/aux/2/1/2*Pi .. Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:21`; [0, MultiSeries:-`multiseries/function`[`Si/infinity/aux/2/1/2*Pi .. Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[Si]:=proc (expr, scale, var, order) local lim, lim2, asymptdir, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:24`; if expr = 0 then return `multiseries/Convert2SERIES`(Si(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then if has(lim,exp) then asymptdir := op(select(type,lim,specfunc(anything,exp))) elif 1 < nops(lim) then asymptdir := argument(subs(infinity = 1,lim)) else asymptdir := 0 end if; lim := infinity else asymptdir := argument(lim) end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := `multiseries/function`[Si,0](argseq) elif lim = infinity then if evalb(signum(1/2*Pi-asymptdir) <> 1) and evalb(signum(Pi-asymptdir) <> -1) then res := `multiseries/function`[Si,infinity,1/2*Pi .. Pi](argseq,[op(1,[argseq]), scale, var, order]) elif evalb(signum(-1/2*Pi-asymptdir) <> 1) and evalb(signum(1/2*Pi-asymptdir) <> -1) then res := `multiseries/function`[Si,infinity,-1/2*Pi .. 1/2*Pi](argseq,[op(1,[argseq]), scale, var, order]) elif evalb(signum(-Pi-asymptdir) <> 1) and evalb(signum(-1/2*Pi-asymptdir) <> -1) then res := `multiseries/function`[Si,infinity,-Pi .. -1/2*Pi](argseq,[op(1,[argseq]), scale, var, order]) end if else res := eval(`multiseries/function`[Si,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = Si(op(9,expr)),res) end proc:
`multiseries/function`[Si, 0, "BasisVector", 0, 0, 1, "MultiSeries", 2]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:04`; SERIES(scale,MultiSeries:-`multiseries/function`[Si,0,"CoeffProc",1,1,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Si/0/BasisVector/0/0/1/MultiSeries/2`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Si/infinity/aux/1/1/2*Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:19`; SERIES(scale,MultiSeries:-`multiseries/function`[`Si/infinity/aux/1/1/2*Pi .. Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Si/infinity/aux/1/1/2*Pi .. Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Si, 0, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:02`; SERIES(scale,MultiSeries:-`multiseries/function`[Si,0,"CoeffProc",1,1,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Si/0/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Si, 0, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:03`; [MultiSeries:-`multiseries/function`[Si,0,"BasisVector",0,0,0,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[Si,0,"BasisVector",0,0,0,"MultiSeries",1](args)] end proc:
`multiseries/function`[`Si/infinity/aux/2/-Pi .. -1/2*Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:20:15`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Ci/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Si/infinity/aux/2/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint),diff(`Si/infinity/aux/2/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Si/infinity/aux/2/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Si/infinity/aux/2/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
