# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[StruveL, 0]:=proc (expr, scale, var, order, a1) local d1, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:13`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[StruveL,0,"BasisVector",_a1,1,0,"MultiSeries"](expr,scale,var,order,a1); loc2 := limit(1/4*2^(-d1)/Pi^(1/2)/GAMMA(d1+3/2)/(d1+1),d1 = a1,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*StruveL(a1,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],a1+1,loc2,0); res := res1; subsop(9 = StruveL(a1,op(9,expr)),res) end proc:
`multiseries/function`[StruveL, 0, "BasisVector", _a1, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:11`; [MultiSeries:-`multiseries/function`[StruveL,0,"BasisVector",_a1,0,0,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[StruveL,0,"BasisVector",_a1,0,0,"MultiSeries",1](args)] end proc:
`multiseries/function`[StruveL, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, arg2, a1, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:06`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, 1/4*arg2] elif n = 3 then [arg0, arg1, 1/4*arg2, -1/12/xarg^3*(2*arg0*a1^2+2*a1^3*arg0+2*arg0*a1*xarg^2-2*arg0*xarg^2-2*arg1*xarg^3-2*arg1*a1^2*xarg-2*arg1*a1*xarg+2*arg2*xarg^2-arg2*xarg^2*a1)] elif n = 4 then [arg0, arg1, 1/4*arg2, -1/12/xarg^3*(2*arg0*a1^2+2*a1^3*arg0+2*arg0*a1*xarg^2-2*arg0*xarg^2-2*arg1*xarg^3-2*arg1*a1^2*xarg-2*arg1*a1*xarg+2*arg2*xarg^2-arg2*xarg^2*a1), -1/48/xarg^4*(8*arg1*a1^2*xarg+8*arg1*a1*xarg+2*arg1*xarg^3-8*arg0*a1*xarg^2-10*arg0*a1^2-8*a1^3*arg0+6*arg0*xarg^2-6*arg2*xarg^2+4*arg2*xarg^2*a1+2*a1^2*arg0*xarg^2-xarg^4*arg2-2*xarg^2*arg2*a1^2+2*arg0*a1^4)] else loc[0] := arg0; loc[1] := arg1; loc[2] := 1/4*arg2; loc[3] := -1/12/xarg^3*(2*arg0*a1^2+2*a1^3*arg0+2*arg0*a1*xarg^2-2*arg0*xarg^2-2*arg1*xarg^3-2*arg1*a1^2*xarg-2*arg1*a1*xarg+2*arg2*xarg^2-arg2*xarg^2*a1); loc[4] := -1/48/xarg^4*(8*arg1*a1^2*xarg+8*arg1*a1*xarg+2*arg1*xarg^3-8*arg0*a1*xarg^2-10*arg0*a1^2-8*a1^3*arg0+6*arg0*xarg^2-6*arg2*xarg^2+4*arg2*xarg^2*a1+2*a1^2*arg0*xarg^2-xarg^4*arg2-2*xarg^2*arg2*a1^2+2*arg0*a1^4); for i1 from 5 to n do loc[i1] := (-(a1+4)*loc[i1-5]-(2*xarg*a1+10*xarg)*loc[i1-4]-(-36-9*a1+4*a1^2+a1*xarg^2+8*xarg^2+a1^3)*loc[i1-3]-(2*xarg^3-48*xarg+2*a1^2*xarg-10*xarg*a1)*loc[i1-2]-(-14*xarg^2-2*a1*xarg^2)*loc[i1-1]-(-loc[i1-5]-3*xarg*loc[i1-4]+(-a1^2+33+6*a1-3*xarg^2)*loc[i1-3]+(9*xarg*a1-a1^2*xarg+58*xarg-xarg^3)*loc[i1-2]+(3*a1*xarg^2+27*xarg^2)*loc[i1-1]+((-a1-10)*loc[i1-3]+(-2*xarg*a1-23*xarg)*loc[i1-2]+(-16*xarg^2-a1*xarg^2)*loc[i1-1]+(loc[i1-3]+3*xarg*loc[i1-2]+3*xarg^2*loc[i1-1])*i1)*i1)*i1)/(2*xarg^3+(-3*xarg^3+xarg^3*i1)*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[StruveL]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:20`; if nops(exprlist) <> 2 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return `multiseries/Convert2SERIES`(StruveL(paramseq,0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := `multiseries/function`[StruveL,0](argseq) elif lim = infinity then res := `multiseries/function`[StruveL,infinity,-Pi .. Pi](argseq,[[op(1 .. -2,exprlist), op(1,[argseq])], scale, var, order]) else res := eval(`multiseries/function`[StruveL,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = StruveL(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[StruveL, 0, "BasisVector", -_a1, 0, 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:10`; [-a1, MultiSeries:-`multiseries/function`[StruveL,0,"CoeffProc",-_a1,0,0](n,a1)] end proc:
`multiseries/function`[`StruveL/infinity/aux/1/-Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:18`; MultiSeries:-`multiseries/function`[`StruveL/infinity/aux/1/-Pi .. Pi`,0,"CoeffProc"](n,0,a1) end proc:
`multiseries/function`[`StruveL/infinity/aux/0/-Pi .. Pi`]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:16`; if nops(exprlist) <> 2 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`StruveL/infinity/aux/0/-Pi .. Pi`(paramseq,0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`StruveL/infinity/aux/0/-Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`StruveL/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `StruveL/infinity/aux/0/-Pi .. Pi`(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[`StruveL/infinity/aux/1/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:18`; SERIES(scale,MultiSeries:-`multiseries/function`[`StruveL/infinity/aux/1/-Pi .. Pi`,0,"CoeffProc",0](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`StruveL/infinity/aux/1/-Pi .. Pi/0/BasisVector/0/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[StruveL, 0, "CoeffProc", _a1+1, 1, 1]:=proc (n, a1) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:09`; if n = 0 then [2*a1+1] elif n = 1 then [2*a1+1, 0] elif n = 2 then [2*a1+1, 0, 1/4*(2*a1+1)/(a1+1)] elif n = 3 then [2*a1+1, 0, 1/4*(2*a1+1)/(a1+1), 0] else loc[0] := 2*a1+1; loc[1] := 0; loc[2] := 1/4*(2*a1+1)/(a1+1); loc[3] := 0; for i1 from 4 to n do loc[i1] := normal(loc[i1-2]/(2*a1+i1)/i1) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`StruveL/infinity/aux/1/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:19`; [MultiSeries:-`multiseries/function`[`StruveL/infinity/aux/1/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`StruveL/infinity/aux/1/-Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c, a1) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:17`; if n = 0 then [normal(1)] elif n = 1 then [normal(1), normal(-1/8*(4*a1^2-1-8*c-12*c^2-8*a1*c)/(c+1))] else loc[0] := normal(1); loc[1] := normal(-1/8*(4*a1^2-1-8*c-12*c^2-8*a1*c)/(c+1)); for i1 from 2 to n do loc[i1] := normal((-(9-18*a1-30*c-4*a1^2+8*c*a1^2-8*c^3+24*a1*c-8*a1*c^2+8*a1^3+28*c^2)*loc[i1-2]-(-8*a1^2+10-32*c+24*c^2+16*a1*c-16*a1)*loc[i1-1]-((24*a1-16*a1*c-24*c^2+8*a1^2+56*c-30)*loc[i1-2]+(-32+48*c+16*a1)*loc[i1-1]+((-8*a1+28-24*c)*loc[i1-2]+24*loc[i1-1]-8*loc[i1-2]*i1)*i1)*i1)/(-16*c-16*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[StruveL, 0, "BasisVector", _a1, 1, 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:09`; [a1+1, MultiSeries:-`multiseries/function`[StruveL,0,"CoeffProc",_a1+1,0,0](n,a1)] end proc:
`multiseries/function`[StruveL, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:07`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[StruveL,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,StruveL(a1,_AnyFiniteOrdinaryPoint),StruveL(a1+1,_AnyFiniteOrdinaryPoint)+a1/_AnyFiniteOrdinaryPoint*StruveL(a1,_AnyFiniteOrdinaryPoint)+(1/2*_AnyFiniteOrdinaryPoint)^a1/Pi^(1/2)/GAMMA(a1+3/2),2*StruveL(a1,_AnyFiniteOrdinaryPoint)-2*(a1+1)/_AnyFiniteOrdinaryPoint*StruveL(a1+1,_AnyFiniteOrdinaryPoint)-2*a1/_AnyFiniteOrdinaryPoint^2*StruveL(a1,_AnyFiniteOrdinaryPoint)+2*a1/_AnyFiniteOrdinaryPoint*(StruveL(a1+1,_AnyFiniteOrdinaryPoint)+a1/_AnyFiniteOrdinaryPoint*StruveL(a1,_AnyFiniteOrdinaryPoint)+(1/2*_AnyFiniteOrdinaryPoint)^a1/Pi^(1/2)/GAMMA(a1+3/2))+2*(1/2*_AnyFiniteOrdinaryPoint)^a1*a1/_AnyFiniteOrdinaryPoint/Pi^(1/2)/GAMMA(a1+3/2),a1,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),StruveL(a1,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[StruveL, 0, "BasisVector", _a1, 0, 0, "MultiSeries", 1]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:11`; SERIES(scale,MultiSeries:-`multiseries/function`[StruveL,0,"CoeffProc",_a1+1,1,0](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`StruveL/0/BasisVector/_a1/0/0/MultiSeries/1`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[`StruveL/infinity/aux/1/-Pi .. Pi`]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:19`; if nops(exprlist) <> 2 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`StruveL/infinity/aux/1/-Pi .. Pi`(paramseq,0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`StruveL/infinity/aux/1/-Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`StruveL/infinity/aux/1/-Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `StruveL/infinity/aux/1/-Pi .. Pi`(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[`StruveL/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:15`; SERIES(scale,MultiSeries:-`multiseries/function`[`StruveL/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc",0](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`StruveL/infinity/aux/0/-Pi .. Pi/0/BasisVector/0/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[`StruveL/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:15`; [0, MultiSeries:-`multiseries/function`[`StruveL/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0,a1)] end proc:
`multiseries/function`[`StruveL/infinity/aux/0/-Pi .. Pi`, 0]:=proc (expr, scale, var, order, a1) local d1, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:16`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`StruveL/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1); loc2 := limit(-2^(1-d1)/Pi^(1/2)/GAMMA(d1+1/2),d1 = a1,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`StruveL/infinity/aux/0/-Pi .. Pi`(a1,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `StruveL/infinity/aux/0/-Pi .. Pi`(a1,op(9,expr)),res) end proc:
`multiseries/function`[`StruveL/infinity/aux/1/-Pi .. Pi`, 0]:=proc (expr, scale, var, order, a1) local d1, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:19`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`StruveL/infinity/aux/1/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1); loc2 := limit(1/2*2^(1/2)/Pi^(1/2),d1 = a1,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`StruveL/infinity/aux/1/-Pi .. Pi`(a1,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `StruveL/infinity/aux/1/-Pi .. Pi`(a1,op(9,expr)),res) end proc:
`multiseries/function`[StruveL, 0, "BasisVector", _a1, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:11`; SERIES(scale,MultiSeries:-`multiseries/function`[StruveL,0,"CoeffProc",_a1+1,1,1](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`StruveL/0/BasisVector/_a1/0/0/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[StruveL, 0, "CoeffProc", -_a1, 0, 0]:=proc (n, a1) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:10`; if n = 0 then [1] elif n = 1 then [1, 0] elif n = 2 then [1, 0, -1/4/(a1-1)] else loc[0] := 1; loc[1] := 0; loc[2] := -1/4/(a1-1); for i1 from 3 to n do loc[i1] := normal(-loc[i1-2]/(2*a1-i1)/i1) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[StruveL, 0, "CoeffProc", _a1+1, 0, 0]:=proc (n, a1) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:08`; if n = 0 then [4*a1+4] elif n = 1 then [4*a1+4, 0] elif n = 2 then [4*a1+4, 0, 4/3*(a1+1)/(2*a1+3)] else loc[0] := 4*a1+4; loc[1] := 0; loc[2] := 4/3*(a1+1)/(2*a1+3); for i1 from 3 to n do loc[i1] := normal(loc[i1-2]/(1+2*a1+(2*a1+2+i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`StruveL/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, arg2, a1, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:13`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, 1/4*arg2] elif n = 3 then [arg0, arg1, 1/4*arg2, 1/12/xarg^4*(8*arg0*a1*xarg-4*arg0*xarg+16*arg1*a1*xarg^2-20*arg1*xarg^2+2*arg1+2*arg2*a1*xarg^3-7*arg2*xarg^3)] else loc[0] := arg0; loc[1] := arg1; loc[2] := 1/4*arg2; loc[3] := 1/12/xarg^4*(8*arg0*a1*xarg-4*arg0*xarg+16*arg1*a1*xarg^2-20*arg1*xarg^2+2*arg1+2*arg2*a1*xarg^3-7*arg2*xarg^3); for i1 from 4 to n do loc[i1] := (-(-9-6*a1)*loc[i1-4]-(-2*a1*xarg^3-5*xarg^3)*loc[i1-1]-(-19*xarg^2-10*a1*xarg^2+1)*loc[i1-2]-(-14*xarg*a1-23*xarg)*loc[i1-3]-((19*xarg+6*xarg*a1)*loc[i1-3]+(2*a1+6)*loc[i1-4]+(2*a1*xarg^3+9*xarg^3)*loc[i1-1]+(21*xarg^2+6*a1*xarg^2)*loc[i1-2]+(-6*xarg^2*loc[i1-2]-4*xarg*loc[i1-3]-loc[i1-4]-4*xarg^3*loc[i1-1])*i1)*i1)/(xarg^4-xarg^4*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`StruveL/infinity/aux/1/-Pi .. Pi`, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, arg2, a1, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:17`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, 1/4*arg2] elif n = 3 then [arg0, arg1, 1/4*arg2, 1/48/xarg^4*(-8*arg0*a1^2+2*arg0-2*arg0*a1*xarg+12*arg0*a1^2*xarg+8*arg0*a1^3*xarg-3*arg0*xarg-16*arg1+8*arg1*a1^2*xarg^2-42*arg1*xarg^2-16*arg1*a1*xarg^2+40*arg1*xarg+16*arg1*a1*xarg+12*arg2*xarg^2-22*arg2*xarg^3-4*arg2*a1*xarg^3)] else loc[0] := arg0; loc[1] := arg1; loc[2] := 1/4*arg2; loc[3] := 1/48/xarg^4*(-8*arg0*a1^2+2*arg0-2*arg0*a1*xarg+12*arg0*a1^2*xarg+8*arg0*a1^3*xarg-3*arg0*xarg-16*arg1+8*arg1*a1^2*xarg^2-42*arg1*xarg^2-16*arg1*a1*xarg^2+40*arg1*xarg+16*arg1*a1*xarg+12*arg2*xarg^2-22*arg2*xarg^3-4*arg2*a1*xarg^3); for i1 from 4 to n do loc[i1] := (-(-20*a1^2+8*a1^3+245-98*a1)*loc[i1-4]-(-8*a1^2+170+585*xarg-36*a1^2*xarg+8*a1^3*xarg-194*xarg*a1-48*a1)*loc[i1-3]-(-32*xarg*a1+32-16*a1^2*xarg^2+208*xarg-112*a1*xarg^2+444*xarg^2)*loc[i1-2]-(48*xarg^2+104*xarg^3-16*a1*xarg^3)*loc[i1-1]-((8*a1^2-238+56*a1)*loc[i1-4]+(16*a1^2*xarg-664*xarg+16*a1+136*xarg*a1-128)*loc[i1-3]+(104*a1*xarg^2+16*xarg*a1-630*xarg^2-200*xarg+8*a1^2*xarg^2-16)*loc[i1-2]+(-72*xarg^2+24*a1*xarg^3-220*xarg^3)*loc[i1-1]+((-8*a1+76)*loc[i1-4]+(252*xarg-24*xarg*a1+24)*loc[i1-3]+(300*xarg^2-24*a1*xarg^2+48*xarg)*loc[i1-2]+(-8*a1*xarg^3+148*xarg^3+24*xarg^2)*loc[i1-1]+(-8*loc[i1-4]-32*xarg*loc[i1-3]-48*xarg^2*loc[i1-2]-32*xarg^3*loc[i1-1])*i1)*i1)*i1)/(-16*xarg^4+(24*xarg^4-8*xarg^4*i1)*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[StruveL, 0, "BasisVector", _a1, 0, 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:09`; [a1, MultiSeries:-`multiseries/function`[StruveL,0,"CoeffProc",_a1+1,1,1](n,a1), MultiSeries:-`multiseries/function`[StruveL,0,"CoeffProc",_a1+1,1,0](n,a1)] end proc:
`multiseries/function`[`StruveL/infinity/aux/1/-Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:17`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`StruveL/infinity/aux/1/-Pi .. Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`StruveL/infinity/aux/1/-Pi .. Pi`(a1,_AnyFiniteOrdinaryPoint),D[2](`StruveL/infinity/aux/1/-Pi .. Pi`)(a1,_AnyFiniteOrdinaryPoint),2*D[2,2](`StruveL/infinity/aux/1/-Pi .. Pi`)(a1,_AnyFiniteOrdinaryPoint),a1,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`StruveL/infinity/aux/1/-Pi .. Pi`(a1,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`StruveL/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:14`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`StruveL/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`StruveL/infinity/aux/0/-Pi .. Pi`(a1,_AnyFiniteOrdinaryPoint),D[2](`StruveL/infinity/aux/0/-Pi .. Pi`)(a1,_AnyFiniteOrdinaryPoint),2*D[2,2](`StruveL/infinity/aux/0/-Pi .. Pi`)(a1,_AnyFiniteOrdinaryPoint),a1,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`StruveL/infinity/aux/0/-Pi .. Pi`(a1,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[StruveL, 0, "BasisVector", -_a1, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:12`; SERIES(scale,MultiSeries:-`multiseries/function`[StruveL,0,"CoeffProc",-_a1,0,0](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`StruveL/0/BasisVector/-_a1/0/0/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[StruveL, infinity, -Pi .. Pi]:=proc (expr, scale, var, order, a1, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:20`; res := MultiSeries:-`multiseries/add`([MultiSeries:-`multiseries/mul`([MultiSeries:-`multiseries/pow`(expr,1-a1,scale,var,order), MultiSeries:-`multiseries/function`[`StruveL/infinity/aux/0/-Pi .. Pi`](op(arglist))]), MultiSeries:-`multiseries/mul`([MultiSeries:-`multiseries/pow`(expr,1/2,scale,var,order), MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),1),scale,var,order), MultiSeries:-`multiseries/function`[`StruveL/infinity/aux/1/-Pi .. Pi`](op(arglist))])]) end proc:
`multiseries/function`[`StruveL/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c, a1) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:14`; if n = 0 then [normal(1)] elif n = 1 then [normal(1), normal(0)] else loc[0] := normal(1); loc[1] := normal(0); for i1 from 2 to n do loc[i1] := normal(-(-c^2+2*c-1+2*a1*c-2*a1+(2+2*a1-2*c-i1)*i1)*loc[i1-2]) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[StruveL, 0, "BasisVector", _a1, 1, 0, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:12`; [MultiSeries:-`multiseries/function`[StruveL,0,"BasisVector",_a1,1,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`StruveL/infinity/aux/1/-Pi .. Pi`, 0, "BasisVector", 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:18`; [0, MultiSeries:-`multiseries/function`[`StruveL/infinity/aux/1/-Pi .. Pi`,0,"CoeffProc"](n,0,a1)] end proc:
`multiseries/function`[StruveL, 0, "CoeffProc", _a1+1, 1, 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:08`; [`$`(0,n+1)] end proc:
`multiseries/function`[`StruveL/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:16`; [MultiSeries:-`multiseries/function`[`StruveL/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[StruveL, 0, "BasisVector", -_a1, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:13`; [MultiSeries:-`multiseries/function`[StruveL,0,"BasisVector",-_a1,0,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`StruveL/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:15`; MultiSeries:-`multiseries/function`[`StruveL/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0,a1) end proc:
`multiseries/function`[StruveL, 0, "BasisVector", _a1, 1, 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:21:12`; SERIES(scale,MultiSeries:-`multiseries/function`[StruveL,0,"CoeffProc",_a1+1,0,0](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`StruveL/0/BasisVector/_a1/1/0/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
