# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 1), "CoeffProc", 0]:=proc (n) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:19`; `multiseries/function`[arccsch,RootOf(1+_Z^2,index = 1),"CoeffProc"](n,0) end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 1), "CoeffProc", 1/2]:=proc (n) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:19`; `multiseries/function`[arccsch,RootOf(1+_Z^2,index = 1),"CoeffProc"](n,1/2) end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 1), "BasisVector", 1/2, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:19`; [`multiseries/function`[arccsch,RootOf(1+_Z^2,index = 1),"BasisVector",1/2,"MultiSeries",0](args)] end proc:
`multiseries/function`[arccsch]:=proc (expr, scale, var, order) local tmp, re, im, lim, lim2, argseq, res; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:20`; if expr = 0 then return `multiseries/Convert2SERIES`(arccsch(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := `multiseries/function`[arccsch,0](argseq) elif lim = infinity then res := `multiseries/function`[arccsch,infinity](argseq) elif lim = I or Testzero(lim-I) or lim = RootOf(1+_Z^2,index = 1) or Testzero(lim-RootOf(1+_Z^2,index = 1)) then res := `multiseries/function`[arccsch,RootOf(1+_Z^2,index = 1)](argseq) elif lim = -I or Testzero(lim+I) or lim = RootOf(1+_Z^2,index = 2) or Testzero(lim-RootOf(1+_Z^2,index = 2)) then res := `multiseries/function`[arccsch,RootOf(1+_Z^2,index = 2)](argseq) else res := eval(`multiseries/function`[arccsch,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; if _Envnobranchcut <> true then if `multiseries/IsOnBranchCut`([I, -I],expr,scale,var) then userinfo(2,MultiSeries,`branchcut:`,arccsch,[I, -I]); if lim = infinity then im := `multiseries/sign`(Im(`multiseries/MulSeriesCst`(expr,-I,algebraic))) else im := `multiseries/sign`(Im(`multiseries/MulSeriesCst`(`multiseries/AddDoit`(expr,-lim),-I,algebraic))) end if; if im = 1 then _Envnobranchcut := true; userinfo(2,MultiSeries,`jump:`,arccsch,`multiseries/run`(I*Pi-2*arccsch(expr),scale,var,order)); res := `multiseries/run`(I*Pi-2*arccsch(expr)+res,scale,var,order); _Envnobranchcut := false elif type(im,specfunc(anything,'signum')) or type(-im,specfunc(anything,signum)) then _Envnobranchcut := true; userinfo(2,MultiSeries,`jump:`,arccsch,`multiseries/run`(1/2*(im+1)*(I*Pi-2*arccsch(expr)),scale,var,order)); res := `multiseries/run`(1/2*(im+1)*(I*Pi-2*arccsch(expr))+res,scale,var,order); _Envnobranchcut := false end if end if end if; subsop(9 = ('arccsch')(op(9,expr)),res) end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 1), "BasisVector", 1/2]:=proc (n) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:19`; [1/2, `multiseries/function`[arccsch,RootOf(1+_Z^2,index = 1),"CoeffProc"](n,1/2)] end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 1)]:=proc (expr, scale, var, order) local loc1, loc2, loc3, res, res1, res2; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:19`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc3 := `multiseries/MulSeriesCst`(expr,-I,algebraic); loc1 := `multiseries/function`[arccsch,RootOf(1+_Z^2,index = 1),"BasisVector",0,"MultiSeries"](loc3,scale,var,order); loc2 := -1/2*I*Pi; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[loc3, scale, var, order],0,loc2,RootOf(1+_Z^2,index = 1)); loc1 := `multiseries/function`[arccsch,RootOf(1+_Z^2,index = 1),"BasisVector",1/2,"MultiSeries"](loc3,scale,var,order); loc2 := I*2^(1/2); res2 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[loc3, scale, var, order],1/2,loc2,RootOf(1+_Z^2,index = 1)); res := `multiseries/add`([res1, res2]); res := subsop(2 = subs(RootOf(1+_Z^2,index = 1) = I,op(2,res)),res); res := subsop(5 = subs(RootOf(1+_Z^2,index = 1) = I,op(5,res)),res); subsop(9 = ('arccsch')(op(9,expr)),res) end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 1), "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:19`; [`multiseries/function`[arccsch,RootOf(1+_Z^2,index = 1),"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 2), "CoeffProc", 0]:=proc (n) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:20`; `multiseries/function`[arccsch,RootOf(1+_Z^2,index = 2),"CoeffProc"](n,0) end proc:
`multiseries/function`[arccsch, 0, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:17`; [0, `multiseries/function`[arccsch,0,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[arccsch, 0, "BasisVector", 0, 0, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:19`; [`multiseries/function`[arccsch,0,"BasisVector",0,0,1,"MultiSeries",0](args), `multiseries/function`[arccsch,0,"BasisVector",0,0,1,"MultiSeries",1](args)] end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 2), "BasisVector", 1/2, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:20`; SERIES(scale,`multiseries/function`[arccsch,RootOf(1+_Z^2,index = 2),"CoeffProc",1/2](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`arccsch/RootOf(1+_Z^2,index = 2)/BasisVector/1/2/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[arccsch, 0, "CoeffProc", 0, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:17`; loc[0] := 1; loc[1] := 0; loc[2] := 0; for i1 from 3 to n do loc[i1] := -(2+(i1-3)*i1)*loc[i1-2]/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[arccsch, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, xarg) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:17`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, -1/2*arg1*(2*xarg^2+1)/xarg/(1+xarg^2)] else loc[0] := arg0; loc[1] := arg1; loc[2] := -1/2*arg1*(2*xarg^2+1)/xarg/(1+xarg^2); for i1 from 3 to n do loc[i1] := (-6*loc[i1-3]-(4*xarg^2+1)*loc[i1-1]-10*xarg*loc[i1-2]-(-5*loc[i1-3]-11*xarg*loc[i1-2]+(-2-7*xarg^2)*loc[i1-1]+(3*xarg*loc[i1-2]+loc[i1-3]+(1+3*xarg^2)*loc[i1-1])*i1)*i1)/(-xarg-xarg^3+(xarg+xarg^3)*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 1), "BasisVector", 1/2, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:19`; SERIES(scale,`multiseries/function`[arccsch,RootOf(1+_Z^2,index = 1),"CoeffProc",1/2](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`arccsch/RootOf(1+_Z^2,index = 1)/BasisVector/1/2/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 2), "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:20`; SERIES(scale,`multiseries/function`[arccsch,RootOf(1+_Z^2,index = 2),"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`arccsch/RootOf(1+_Z^2,index = 2)/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[arccsch, 0, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:18`; [`multiseries/function`[arccsch,0,"BasisVector",0,0,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[arccsch, 0, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:18`; SERIES(scale,`multiseries/function`[arccsch,0,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`arccsch/0/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 2), "CoeffProc", 1/2]:=proc (n) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:20`; `multiseries/function`[arccsch,RootOf(1+_Z^2,index = 2),"CoeffProc"](n,1/2) end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 1), "BasisVector", 0]:=proc (n) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:19`; [0, `multiseries/function`[arccsch,RootOf(1+_Z^2,index = 1),"CoeffProc"](n,0)] end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 1), "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:19`; if n = 0 then [1] elif n = 1 then [1, -c*(3*c+1)/(2*c^2+3*c+1)] else loc[0] := 1; loc[1] := -c*(3*c+1)/(2*c^2+3*c+1); for i1 from 2 to n do loc[i1] := (-(-c^2+3*c-2)*loc[i1-2]-(-3*c^2+5*c-2)*loc[i1-1]-((-2*c+3)*loc[i1-2]+(-6*c+5)*loc[i1-1]+(-loc[i1-2]-3*loc[i1-1])*i1)*i1)/(c-2*c^2+(-4*c+1-2*i1)*i1) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[arccsch, infinity, "CoeffProc"]:=proc (n, arg0, arg1) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:17`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] else loc[0] := arg0; loc[1] := arg1; for i1 from 2 to n do loc[i1] := -(i1-2)^2*loc[i1-2]/(i1-1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 2)]:=proc (expr, scale, var, order) local loc1, loc2, loc3, res, res1, res2; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:20`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc3 := `multiseries/MulSeriesCst`(expr,I,algebraic); loc1 := `multiseries/function`[arccsch,RootOf(1+_Z^2,index = 2),"BasisVector",0,"MultiSeries"](loc3,scale,var,order); loc2 := 1/2*I*Pi; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[loc3, scale, var, order],0,loc2,RootOf(1+_Z^2,index = 2)); loc1 := `multiseries/function`[arccsch,RootOf(1+_Z^2,index = 2),"BasisVector",1/2,"MultiSeries"](loc3,scale,var,order); loc2 := -I*2^(1/2); res2 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[loc3, scale, var, order],1/2,loc2,RootOf(1+_Z^2,index = 2)); res := `multiseries/add`([res1, res2]); res := subsop(2 = subs(RootOf(1+_Z^2,index = 2) = -I,op(2,res)),res); res := subsop(5 = subs(RootOf(1+_Z^2,index = 2) = -I,op(5,res)),res); subsop(9 = ('arccsch')(op(9,expr)),res) end proc:
`multiseries/function`[arccsch, infinity]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:17`; `multiseries/compose`(SERIES(scale,`multiseries/function`[arccsch,infinity,"CoeffProc"](order,0,1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),arccsch(1/eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 1), "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:19`; SERIES(scale,`multiseries/function`[arccsch,RootOf(1+_Z^2,index = 1),"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`arccsch/RootOf(1+_Z^2,index = 1)/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 2), "BasisVector", 0]:=proc (n) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:20`; [0, `multiseries/function`[arccsch,RootOf(1+_Z^2,index = 2),"CoeffProc"](n,0)] end proc:
`multiseries/function`[arccsch, 0, "BasisVector", 0, 0, 1]:=proc (n) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:18`; [0, `multiseries/function`[arccsch,0,"CoeffProc",0,0,1](n), `multiseries/function`[arccsch,0,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[arccsch, 0, "BasisVector", 0, 0, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:18`; SERIES(scale,`multiseries/function`[arccsch,0,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`arccsch/0/BasisVector/0/0/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 2), "BasisVector", 1/2, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:20`; [`multiseries/function`[arccsch,RootOf(1+_Z^2,index = 2),"BasisVector",1/2,"MultiSeries",0](args)] end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 2), "BasisVector", 1/2]:=proc (n) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:20`; [1/2, `multiseries/function`[arccsch,RootOf(1+_Z^2,index = 2),"CoeffProc"](n,1/2)] end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 2), "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:20`; [`multiseries/function`[arccsch,RootOf(1+_Z^2,index = 2),"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[arccsch, 0, "CoeffProc", 0, 0, 1]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:17`; xxloc1 := `multiseries/function`[arccsch,0,"CoeffProc",0,0,0](n); loc[0] := 0; loc[1] := 0; loc[2] := -1/4; for i1 from 3 to n do loc[i1] := (-(-3+2*i1)*op(i1-1,xxloc1)-2*i1*op(i1+1,xxloc1)-(2+(i1-3)*i1)*loc[i1-2])/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[arccsch, RootOf(1+_Z^2,index = 2), "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:20`; if n = 0 then [1] elif n = 1 then [1, -c*(3*c+1)/(2*c^2+3*c+1)] else loc[0] := 1; loc[1] := -c*(3*c+1)/(2*c^2+3*c+1); for i1 from 2 to n do loc[i1] := (-(-c^2+3*c-2)*loc[i1-2]-(-3*c^2+5*c-2)*loc[i1-1]-((-2*c+3)*loc[i1-2]+(-6*c+5)*loc[i1-1]+(-loc[i1-2]-3*loc[i1-1])*i1)*i1)/(c-2*c^2+(-4*c+1-2*i1)*i1) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[arccsch, 0, "BasisVector", 0, 0, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:18`; SERIES(scale,`multiseries/function`[arccsch,0,"CoeffProc",0,0,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`arccsch/0/BasisVector/0/0/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[arccsch, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:17`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[arccsch,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,arccsch(_AnyFiniteOrdinaryPoint),-1/_AnyFiniteOrdinaryPoint^2/(1+1/_AnyFiniteOrdinaryPoint^2)^(1/2),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),arccsch(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[arccsch, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1, res2; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:19`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[arccsch,0,"BasisVector",0,0,0,"MultiSeries"](expr,scale,var,order); loc2 := ln(2); res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); loc1 := `multiseries/function`[arccsch,0,"BasisVector",0,0,1,"MultiSeries"](expr,scale,var,order); loc2 := -1; res2 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := `multiseries/add`([res1, res2]); subsop(9 = ('arccsch')(op(9,expr)),res) end proc:
