# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[BesselY, 0, (2*_a1)::integer, "CoeffProc", _a1, 2*_a1, 1, "Shifted"]:=proc (n, a1, THETA, c0, c1) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:40`; xxloc1 := `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,2*_a1,0](n+THETA,a1); if n = 0 then [c0] elif n = 1 then [c0, c1] else loc[0] := c0; loc[1] := c1; for i1 from 2 to n do loc[i1] := normal((-(-2*a1+2*i1+2*THETA)*op(i1+1+THETA,xxloc1)-loc[i1-2])/(-2*THETA*a1+THETA^2+(-2*a1+2*THETA+i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[BesselY, 0, "Generic", "BasisVector", -_a1, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:49`; SERIES(scale,`multiseries/function`[BesselY,0,"Generic","CoeffProc",-_a1](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`BesselY/0/Generic/BasisVector/-_a1/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, "CoeffProc", _a1, 0, 0, "Symbolic"]:=proc (n, a1) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:37`; if n = 0 then [4*GAMMA(4*a1)*a1] elif n = 1 then [4*GAMMA(4*a1)*a1, 0] elif n = 2 then [4*GAMMA(4*a1)*a1, 0, -GAMMA(4*a1)*a1/(a1+1)] else loc[0] := 4*GAMMA(4*a1)*a1; loc[1] := 0; loc[2] := -GAMMA(4*a1)*a1/(a1+1); for i1 from 3 to n do loc[i1] := normal(-loc[i1-2]/(2*a1+i1)/i1) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`BesselY/infinity/aux/0/-Pi .. Pi`, 0]:=proc (expr, scale, var, order, a1) local d1, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:53`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[`BesselY/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1); loc2 := limit(1/2*I*2^(1/2)/Pi^(1/2)*exp(1/4*I*Pi*(2*d1+1)),d1 = a1,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`BesselY/infinity/aux/0/-Pi .. Pi`(a1,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `BesselY/infinity/aux/0/-Pi .. Pi`(a1,op(9,expr)),res) end proc:
`multiseries/function`[`BesselY/infinity/aux/1/-Pi .. Pi`]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:56`; if nops(exprlist) <> 2 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return `multiseries/Convert2SERIES`(`BesselY/infinity/aux/1/-Pi .. Pi`(paramseq,0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := `multiseries/function`[`BesselY/infinity/aux/1/-Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(`multiseries/function`[`BesselY/infinity/aux/1/-Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `BesselY/infinity/aux/1/-Pi .. Pi`(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[BesselY, 0, "Generic", "BasisVector", _a1, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:49`; SERIES(scale,`multiseries/function`[BesselY,0,"Generic","CoeffProc",_a1](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`BesselY/0/Generic/BasisVector/_a1/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[BesselY, 0, "Generic"]:=proc (expr, scale, var, order, a1) local d1, loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:50`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[BesselY,0,"Generic","BasisVector",_a1,"MultiSeries"](expr,scale,var,order,a1); loc2 := limit(1/GAMMA(d1+1)/(2^d1)*cos(d1*Pi)/sin(d1*Pi),d1 = a1,'left'); res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],a1,loc2,0); loc1 := `multiseries/function`[BesselY,0,"Generic","BasisVector",-_a1,"MultiSeries"](expr,scale,var,order,a1); loc2 := limit(-1/GAMMA(1-d1)/(2^(-d1))/sin(d1*Pi),d1 = a1,'left'); res2 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],-a1,loc2,0); res := `multiseries/add`([res1, res2]); subsop(9 = BesselY(a1,op(9,expr)),res) end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, "CoeffProc", _a1, 2*_a1, 0, "Shifted"]:=proc (n, a1, THETA, c0, c1) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:39`; if n = 0 then [c0] elif n = 1 then [c0, c1] else loc[0] := c0; loc[1] := c1; for i1 from 2 to n do loc[i1] := normal(-loc[i1-2]/(-2*THETA*a1+THETA^2+(-2*a1+2*THETA+i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`BesselY/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:51`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[`BesselJ/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`BesselY/infinity/aux/0/-Pi .. Pi`(a1,_AnyFiniteOrdinaryPoint),D[2](`BesselY/infinity/aux/0/-Pi .. Pi`)(a1,_AnyFiniteOrdinaryPoint),a1,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`BesselY/infinity/aux/0/-Pi .. Pi`(a1,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`BesselY/infinity/aux/1/-Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:54`; `multiseries/function`[`BesselY/infinity/aux/1/-Pi .. Pi`,0,"CoeffProc"](n,0,a1) end proc:
`multiseries/function`[BesselY, 0, "Generic", "BasisVector", -_a1]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:48`; [-a1, `multiseries/function`[BesselY,0,"Generic","CoeffProc"](n,-a1,a1)] end proc:
`multiseries/function`[`BesselY/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:52`; `multiseries/function`[`BesselY/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0,a1) end proc:
`multiseries/function`[BesselY, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:33`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[BesselJ,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,BesselY(a1,_AnyFiniteOrdinaryPoint),-BesselY(a1+1,_AnyFiniteOrdinaryPoint)+a1/_AnyFiniteOrdinaryPoint*BesselY(a1,_AnyFiniteOrdinaryPoint),a1,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),BesselY(a1,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[BesselY, 0, _a1::0, "BasisVector", 0, 0, 1, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:35`; SERIES(scale,`multiseries/function`[BesselY,0,_a1::0,"CoeffProc",0,0,1](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`BesselY/0/_a1::0/BasisVector/0/0/1/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[BesselY, 0, _a1::0, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:35`; [`multiseries/function`[BesselY,0,_a1::0,"BasisVector",0,0,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`BesselY/infinity/aux/1/-Pi .. Pi`, 0, "BasisVector", 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:54`; [0, `multiseries/function`[`BesselY/infinity/aux/1/-Pi .. Pi`,0,"CoeffProc"](n,0,a1)] end proc:
`multiseries/function`[BesselY, 0, _a1::0, "CoeffProc", 0, 0, 0]:=proc (n, a1) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:33`; if n = 0 then [1] elif n = 1 then [1, 0] elif n = 2 then [1, 0, 1/(a1^2-4)] else loc[0] := 1; loc[1] := 0; loc[2] := 1/(a1^2-4); for i1 from 3 to n do loc[i1] := normal(-loc[i1-2]/(-a1^2+i1^2)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[BesselY, 0, "Generic", "BasisVector", _a1, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:49`; [`multiseries/function`[BesselY,0,"Generic","BasisVector",_a1,"MultiSeries",0](args)] end proc:
`multiseries/function`[BesselY, 0, _a1::0]:=proc (expr, scale, var, order, a1) local d1, loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:36`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[BesselY,0,_a1::0,"BasisVector",0,0,0,"MultiSeries"](expr,scale,var,order,a1); loc2 := limit(-2*(-gamma+ln(2))/Pi,d1 = a1,'left'); res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); loc1 := `multiseries/function`[BesselY,0,_a1::0,"BasisVector",0,0,1,"MultiSeries"](expr,scale,var,order,a1); loc2 := limit(2/Pi,d1 = a1,'left'); res2 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := `multiseries/add`([res1, res2]); subsop(9 = BesselY(a1,op(9,expr)),res) end proc:
`multiseries/function`[`BesselY/infinity/aux/0/-Pi .. Pi`]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:53`; if nops(exprlist) <> 2 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return `multiseries/Convert2SERIES`(`BesselY/infinity/aux/0/-Pi .. Pi`(paramseq,0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := `multiseries/function`[`BesselY/infinity/aux/0/-Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(`multiseries/function`[`BesselY/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `BesselY/infinity/aux/0/-Pi .. Pi`(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, "CoeffProc", _a1, 2*_a1, 0, "Limit"]:=proc (n, c1) local loc, loc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:39`; loc := `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,2*_a1,0,"Symbolic"](n,loc1); if type(c1,symbol) then loc := subs(loc1 = c1,loc) else loc := map(limit,loc,loc1 = c1) end if; loc end proc:
`multiseries/function`[BesselY, 0, "Generic", "CoeffProc", -_a1]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:48`; `multiseries/function`[BesselY,0,"Generic","CoeffProc"](n,-a1,a1) end proc:
`multiseries/function`[BesselY, 0, _a1::0, "BasisVector", 0, 0, 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:34`; [0, `multiseries/function`[BesselY,0,_a1::0,"CoeffProc",0,0,0](n,a1)] end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, "CoeffProc", _a1, 2*_a1, 1, "Limit"]:=proc (n, c1) local loc, loc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:40`; loc := `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,2*_a1,1,"Symbolic"](n,loc1); if type(c1,symbol) then loc := subs(loc1 = c1,loc) else loc := map(limit,loc,loc1 = c1) end if; loc end proc:
`multiseries/function`[BesselY, infinity, -Pi .. Pi]:=proc (expr, scale, var, order, a1, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:56`; res := `multiseries/add`([`multiseries/mul`([`multiseries/pow`(expr,1/2,scale,var,order), `multiseries/function`[exp](`multiseries/MulDoit`(`multiseries/pow`(expr,-1,scale,var,order),-I),scale,var,order), `multiseries/function`[`BesselY/infinity/aux/0/-Pi .. Pi`](op(arglist))]), `multiseries/mul`([`multiseries/pow`(expr,1/2,scale,var,order), `multiseries/function`[exp](`multiseries/MulDoit`(`multiseries/pow`(expr,-1,scale,var,order),I),scale,var,order), `multiseries/function`[`BesselY/infinity/aux/1/-Pi .. Pi`](op(arglist))])]) end proc:
`multiseries/function`[BesselY, 0, _a1::0, "CoeffProc", 0, 0, 1]:=proc (n, a1) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:34`; xxloc1 := `multiseries/function`[BesselY,0,_a1::0,"CoeffProc",0,0,0](n,a1); if n = 0 then [0] elif n = 1 then [0, 0] elif n = 2 then [0, 0, 4/(a1^4-8*a1^2+16)] else loc[0] := 0; loc[1] := 0; loc[2] := 4/(a1^4-8*a1^2+16); for i1 from 3 to n do loc[i1] := normal((-2*i1*op(i1+1,xxloc1)-loc[i1-2])/(-a1^2+i1^2)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[BesselY, 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:50`; if is(a1::0) then userinfo(2,BesselY,`maincase:`,a1::0); `multiseries/function`[BesselY,0,_a1::0](expr,scale,var,order,a1) elif is((2*a1)::integer) then if is((2*a1)::LinearProp(2,integer,0)) then userinfo(2,BesselY,`maincase:`,(2*a1)::integer,`subcase:`,(2*a1)::LinearProp(2,integer,0)); `multiseries/function`[BesselY,0,(2*_a1)::integer,(2*_a1)::LinearProp(2,integer,0)](expr,scale,var,order,a1) elif is((2*a1)::LinearProp(2,integer,1)) then userinfo(2,BesselY,`maincase:`,(2*a1)::integer,`subcase:`,(2*a1)::LinearProp(2,integer,1)); `multiseries/function`[BesselY,0,(2*_a1)::integer,(2*_a1)::LinearProp(2,integer,1)](expr,scale,var,order,a1) else error "need to determine whether", (2*a1)::LinearProp(2,integer,0), "or", (2*a1)::LinearProp(2,integer,1) end if else userinfo(2,BesselY,`generic case`); `multiseries/function`[BesselY,0,"Generic"](expr,scale,var,order,a1) end if end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, "CoeffProc", _a1, 2*_a1, 1]:=proc (n, a1) local loc1, loc2, loc3, i; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:40`; if type(2*a1,integer) then loc1 := max(2*a1,2); if n <= loc1 then `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,2*_a1,1,"Limit"](args) else loc2 := `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,2*_a1,1,"Limit"](loc1,a1); loc3 := `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,2*_a1,1,"Shifted"](n-loc1+1,a1,loc1-1,seq(loc2[i],i = loc1 .. loc1+1)); [op(1 .. loc1-1,loc2), op(loc3)] end if else `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,2*_a1,1,"Limit"](args) end if end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, "CoeffProc", _a1, 2*_a1, 1, "Symbolic"]:=proc (n, a1) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:40`; xxloc1 := `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,2*_a1,0](n,a1); if n = 0 then [-GAMMA(2*a1)*(1-a1*Psi(-2*a1)+Psi(2*a1)*a1)/GAMMA(-2*a1)/a1] elif n = 1 then [-GAMMA(2*a1)*(1-a1*Psi(-2*a1)+Psi(2*a1)*a1)/GAMMA(-2*a1)/a1, 0] elif n = 2 then [-GAMMA(2*a1)*(1-a1*Psi(-2*a1)+Psi(2*a1)*a1)/GAMMA(-2*a1)/a1, 0, -1/8*GAMMA(2*a1)*(-a1^2+4*a1-2-2*a1^2*Psi(-2*a1)+2*a1*Psi(-2*a1)+2*Psi(2*a1)*a1^2-2*Psi(2*a1)*a1)/GAMMA(-2*a1)/a1/(a1^2-2*a1+1)] else loc[0] := -GAMMA(2*a1)*(1-a1*Psi(-2*a1)+Psi(2*a1)*a1)/GAMMA(-2*a1)/a1; loc[1] := 0; loc[2] := -1/8*GAMMA(2*a1)*(-a1^2+4*a1-2-2*a1^2*Psi(-2*a1)+2*a1*Psi(-2*a1)+2*Psi(2*a1)*a1^2-2*Psi(2*a1)*a1)/GAMMA(-2*a1)/a1/(a1^2-2*a1+1); for i1 from 3 to n do loc[i1] := normal((-(-2*a1+2*i1)*op(i1+1,xxloc1)-loc[i1-2])/(-2*a1+i1)/i1) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, "BasisVector", -_a1, 2*_a1, 0, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:42`; [`multiseries/function`[BesselY,0,(2*_a1)::integer,"BasisVector",-_a1,2*_a1,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, "BasisVector", -_a1, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:42`; [`multiseries/function`[BesselY,0,(2*_a1)::integer,"BasisVector",-_a1,0,0,"MultiSeries",0](args), `multiseries/function`[BesselY,0,(2*_a1)::integer,"BasisVector",-_a1,0,0,"MultiSeries",1](args)] end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, "BasisVector", -_a1, 0, 0, "MultiSeries", 1]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:41`; SERIES(scale,`multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,2*_a1,0](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`BesselY/0/(2*_a1)::integer/BasisVector/-_a1/0/0/MultiSeries/1`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, "CoeffProc", _a1, 2*_a1, 0]:=proc (n, a1) local loc1, loc2, loc3, i; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:39`; if type(2*a1,integer) then loc1 := max(2*a1,2); if n <= loc1 then `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,2*_a1,0,"Limit"](args) else loc2 := `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,2*_a1,0,"Limit"](loc1,a1); loc3 := `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,2*_a1,0,"Shifted"](n-loc1+1,a1,loc1-1,seq(loc2[i],i = loc1 .. loc1+1)); [op(1 .. loc1-1,loc2), op(loc3)] end if else `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,2*_a1,0,"Limit"](args) end if end proc:
`multiseries/function`[BesselY, 0, "Generic", "BasisVector", _a1]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:48`; [a1, `multiseries/function`[BesselY,0,"Generic","CoeffProc"](n,a1,a1)] end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, (2*_a1)::LinearProp(2,integer,0)]:=proc (expr, scale, var, order, a1) local d1, loc1, loc2, loc3, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:45`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[BesselY,0,(2*_a1)::integer,"BasisVector",-_a1,2*_a1,0,"MultiSeries"](expr,scale,var,order,a1); loc2 := limit(1/8*(2*(1/2)^(-d1)*GAMMA(d1)*d1*(-1/4)^d1*GAMMA(1-d1)*2^d1*Psi(2*d1)+2*(1/2)^(-d1)*GAMMA(d1)*(-1/4)^d1*GAMMA(1-d1)*2^d1+(1/2)^(-d1)*GAMMA(d1)*d1*(-1/4)^d1*GAMMA(1-d1)*2^d1*Psi(1-d1)-2*(1/2)^(-d1)*GAMMA(d1)*d1*(-1/4)^d1*GAMMA(1-d1)*2^d1*Psi(-2*d1)-(1/2)^(-d1)*GAMMA(d1)*d1*(-1/4)^d1*GAMMA(1-d1)*2^d1*Psi(d1+1)+2*(1/2)^d1*2^d1*gamma*d1*Psi(2*d1)+2*(1/2)^d1*2^d1*gamma-2*(1/2)^d1*2^d1*gamma*d1*Psi(-2*d1)-2*(1/2)^d1*2^d1*Psi(d1+1)*d1*Psi(2*d1)-2*(1/2)^d1*2^d1*Psi(d1+1)+2*(1/2)^d1*2^d1*Psi(d1+1)*d1*Psi(-2*d1)-4*ln(2)*d1*Psi(2*d1)-4*ln(2)+4*ln(2)*d1*Psi(-2*d1))/d1/GAMMA(4*d1)/GAMMA(d1+1)/Pi/(2^d1)/(d1*Psi(2*d1)+1-d1*Psi(-2*d1)),d1 = a1,'left'); res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],a1,loc2,0); loc1 := `multiseries/function`[BesselY,0,(2*_a1)::integer,"BasisVector",-_a1,0,0,"MultiSeries"](expr,scale,var,order,a1); loc2 := limit((1/2)^(-d1)*GAMMA(d1)*d1*GAMMA(-2*d1)/GAMMA(2*d1)/Pi/(d1*Psi(2*d1)+1-d1*Psi(-2*d1)),d1 = a1,'left'); res2 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],-a1,loc2,0); res := `multiseries/add`([res1, res2]); subsop(9 = BesselY(a1,op(9,expr)),res) end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, "CoeffProc", _a1, 0, 0, "Shifted"]:=proc (n, a1, THETA, c0, c1) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:37`; if n = 0 then [c0] elif n = 1 then [c0, c1] else loc[0] := c0; loc[1] := c1; for i1 from 2 to n do loc[i1] := normal(-loc[i1-2]/(2*THETA*a1+THETA^2+(2*a1+2*THETA+i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, "BasisVector", -_a1, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:41`; SERIES(scale,`multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,2*_a1,1](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`BesselY/0/(2*_a1)::integer/BasisVector/-_a1/0/0/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, "CoeffProc", _a1, 0, 0]:=proc (n, a1) local loc1, loc2, loc3, i; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:38`; if type(2*a1,integer) then loc1 := max(2*a1,2); if n <= loc1 then `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,0,0,"Limit"](args) else loc2 := `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,0,0,"Limit"](loc1,a1); loc3 := `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,0,0,"Shifted"](n-loc1+1,a1,loc1-1,seq(loc2[i],i = loc1 .. loc1+1)); [op(1 .. loc1-1,loc2), op(loc3)] end if else `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,0,0,"Limit"](args) end if end proc:
`multiseries/function`[`BesselY/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:52`; [`multiseries/function`[`BesselY/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[BesselY, 0, _a1::0, "BasisVector", 0, 0, 1]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:34`; [0, `multiseries/function`[BesselY,0,_a1::0,"CoeffProc",0,0,1](n,a1), `multiseries/function`[BesselY,0,_a1::0,"CoeffProc",0,0,0](n,a1)] end proc:
`multiseries/function`[`BesselY/infinity/aux/1/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:55`; SERIES(scale,`multiseries/function`[`BesselY/infinity/aux/1/-Pi .. Pi`,0,"CoeffProc",0](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`BesselY/infinity/aux/1/-Pi .. Pi/0/BasisVector/0/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[BesselY, 0, "Generic", "CoeffProc"]:=proc (n, c, a1) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:47`; if n = 0 then [normal(1)] elif n = 1 then [normal(1), normal(0)] else loc[0] := normal(1); loc[1] := normal(0); for i1 from 2 to n do loc[i1] := normal(-loc[i1-2]/(-a1^2+c^2+(2*c+i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, "BasisVector", -_a1, 0, 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:41`; [-a1, `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,2*_a1,1](n,a1), `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,2*_a1,0](n,a1)] end proc:
`multiseries/function`[`BesselY/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c, a1) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:51`; if n = 0 then [normal(1)] else loc[0] := normal(1); for i1 to n do loc[i1] := normal(-(-4*a1^2+1-4*c+4*c^2+(8*c-4+4*i1)*i1)*loc[i1-1]/(8*I*c+8*I*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`BesselY/infinity/aux/1/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:55`; [`multiseries/function`[`BesselY/infinity/aux/1/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[BesselY, 0, _a1::0, "BasisVector", 0, 0, 1, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:36`; [`multiseries/function`[BesselY,0,_a1::0,"BasisVector",0,0,1,"MultiSeries",0](args), `multiseries/function`[BesselY,0,_a1::0,"BasisVector",0,0,1,"MultiSeries",1](args)] end proc:
`multiseries/function`[`BesselY/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:52`; SERIES(scale,`multiseries/function`[`BesselY/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc",0](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`BesselY/infinity/aux/0/-Pi .. Pi/0/BasisVector/0/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, "BasisVector", -_a1, 2*_a1, 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:41`; [a1, `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,0,0](n,a1)] end proc:
`multiseries/function`[`BesselY/infinity/aux/1/-Pi .. Pi`, 0]:=proc (expr, scale, var, order, a1) local d1, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:55`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[`BesselY/infinity/aux/1/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1); loc2 := limit(-1/2*I*2^(1/2)/Pi^(1/2)*exp(-1/4*I*Pi*(2*d1+1)),d1 = a1,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`BesselY/infinity/aux/1/-Pi .. Pi`(a1,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `BesselY/infinity/aux/1/-Pi .. Pi`(a1,op(9,expr)),res) end proc:
`multiseries/function`[BesselY, 0, _a1::0, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:35`; SERIES(scale,`multiseries/function`[BesselY,0,_a1::0,"CoeffProc",0,0,0](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`BesselY/0/_a1::0/BasisVector/0/0/0/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[`BesselY/infinity/aux/1/-Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:53`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[`BesselJ/infinity/aux/1/-Pi .. Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`BesselY/infinity/aux/1/-Pi .. Pi`(a1,_AnyFiniteOrdinaryPoint),D[2](`BesselY/infinity/aux/1/-Pi .. Pi`)(a1,_AnyFiniteOrdinaryPoint),a1,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`BesselY/infinity/aux/1/-Pi .. Pi`(a1,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[BesselY, 0, "Generic", "BasisVector", -_a1, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:50`; [`multiseries/function`[BesselY,0,"Generic","BasisVector",-_a1,"MultiSeries",0](args)] end proc:
`multiseries/function`[BesselY, 0, "Generic", "CoeffProc", _a1]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:48`; `multiseries/function`[BesselY,0,"Generic","CoeffProc"](n,a1,a1) end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, (2*_a1)::LinearProp(2,integer,1)]:=proc (expr, scale, var, order, a1) local d1, loc1, loc2, loc3, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:47`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[BesselY,0,(2*_a1)::integer,"BasisVector",-_a1,0,0,"MultiSeries"](expr,scale,var,order,a1); loc2 := limit((1/2)^(-d1)*GAMMA(d1)*d1*GAMMA(-2*d1)/GAMMA(2*d1)/Pi/(d1*Psi(2*d1)+1-d1*Psi(-2*d1)),d1 = a1,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*BesselY(a1,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],-a1,loc2,0); res := res1; subsop(9 = BesselY(a1,op(9,expr)),res) end proc:
`multiseries/function`[BesselY, 0, _a1::0, "BasisVector", 0, 0, 1, "MultiSeries", 1]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:36`; SERIES(scale,`multiseries/function`[BesselY,0,_a1::0,"CoeffProc",0,0,0](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`BesselY/0/_a1::0/BasisVector/0/0/1/MultiSeries/1`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[`BesselY/infinity/aux/1/-Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c, a1) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:54`; if n = 0 then [normal(1)] else loc[0] := normal(1); for i1 to n do loc[i1] := normal(-(-4*a1^2+1-4*c+4*c^2+(8*c-4+4*i1)*i1)*loc[i1-1]/(-8*I*c-8*I*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, "BasisVector", -_a1, 2*_a1, 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:42`; SERIES(scale,`multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,0,0](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`BesselY/0/(2*_a1)::integer/BasisVector/-_a1/2*_a1/0/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, "CoeffProc", _a1, 2*_a1, 0, "Symbolic"]:=proc (n, a1) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:38`; if n = 0 then [-GAMMA(2*a1)/GAMMA(-2*a1)] elif n = 1 then [-GAMMA(2*a1)/GAMMA(-2*a1), 0] elif n = 2 then [-GAMMA(2*a1)/GAMMA(-2*a1), 0, -1/4*GAMMA(2*a1)/GAMMA(-2*a1)/(a1-1)] else loc[0] := -GAMMA(2*a1)/GAMMA(-2*a1); loc[1] := 0; loc[2] := -1/4*GAMMA(2*a1)/GAMMA(-2*a1)/(a1-1); for i1 from 3 to n do loc[i1] := normal(-loc[i1-2]/(-2*a1+i1)/i1) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`BesselY/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:51`; [0, `multiseries/function`[`BesselY/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0,a1)] end proc:
`multiseries/function`[BesselY, 0, (2*_a1)::integer, "CoeffProc", _a1, 0, 0, "Limit"]:=proc (n, c1) local loc, loc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:37`; loc := `multiseries/function`[BesselY,0,(2*_a1)::integer,"CoeffProc",_a1,0,0,"Symbolic"](n,loc1); if type(c1,symbol) then loc := subs(loc1 = c1,loc) else loc := map(limit,loc,loc1 = c1) end if; loc end proc:
`multiseries/function`[BesselY]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:12:56`; if nops(exprlist) <> 2 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return `multiseries/Convert2SERIES`(BesselY(paramseq,0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := `multiseries/function`[BesselY,0](argseq) elif lim = infinity then res := `multiseries/function`[BesselY,infinity,-Pi .. Pi](argseq,[[op(1 .. -2,exprlist), op(1,[argseq])], scale, var, order]) else res := eval(`multiseries/function`[BesselY,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = BesselY(paramseq,op(9,expr)),res) end proc:
