# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[CylinderD, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, a1, xarg) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:16:46`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, -1/2*a1*arg0-1/4*arg0+1/8*arg0*xarg^2] elif n = 3 then [arg0, arg1, -1/2*a1*arg0-1/4*arg0+1/8*arg0*xarg^2, 1/12*arg0*xarg-1/6*arg1*a1-1/12*arg1+1/24*arg1*xarg^2] else loc[0] := arg0; loc[1] := arg1; loc[2] := -1/2*a1*arg0-1/4*arg0+1/8*arg0*xarg^2; loc[3] := 1/12*arg0*xarg-1/6*arg1*a1-1/12*arg1+1/24*arg1*xarg^2; for i1 from 4 to n do loc[i1] := (loc[i1-4]+2*xarg*loc[i1-3]-(4*a1+2-xarg^2)*loc[i1-2])/i1/(4*i1-4) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`CylinderD/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, a1, xarg) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:16:46`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, -1/2/xarg^3*(arg0*a1^2*xarg-arg0*a1*xarg+2*arg1*xarg^2-2*arg1*a1*xarg^2+arg1)] else loc[0] := arg0; loc[1] := arg1; loc[2] := -1/2/xarg^3*(arg0*a1^2*xarg-arg0*a1*xarg+2*arg1*xarg^2-2*arg1*a1*xarg^2+arg1); for i1 from 3 to n do loc[i1] := (-(a1^2+5*a1+6)*loc[i1-3]-(4*xarg^2+2*a1*xarg^2-1)*loc[i1-1]-(a1^2*xarg+7*a1*xarg+10*xarg)*loc[i1-2]-((-2*a1-5)*loc[i1-3]+(-4*a1*xarg-11*xarg)*loc[i1-2]+(-7*xarg^2+1-2*a1*xarg^2)*loc[i1-1]+(3*xarg*loc[i1-2]+loc[i1-3]+3*xarg^2*loc[i1-1])*i1)*i1)/(-xarg^3+xarg^3*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`CylinderD/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n, a1) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:16:47`; `multiseries/function`[`CylinderD/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0,a1) end proc:
`multiseries/function`[CylinderD, infinity, -Pi .. Pi]:=proc (expr, scale, var, order, a1, arglist) local res; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:16:47`; res := `multiseries/add`([`multiseries/mul`([`multiseries/pow`(expr,-a1,scale,var,order), `multiseries/function`[exp](`multiseries/MulDoit`(`multiseries/pow`(expr,-2,scale,var,order),-1/4),scale,var,order), `multiseries/function`[`CylinderD/infinity/aux/0/-Pi .. Pi`](op(arglist))])]) end proc:
`multiseries/function`[CylinderD, 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:16:46`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[CylinderD,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,2^(1/2*a1)*Pi^(1/2)/GAMMA(1/2-1/2*a1),-2^(1/2*a1)*Pi^(1/2)/GAMMA(-1/2*a1)*2^(1/2),a1,0)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),CylinderD(a1,eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`CylinderD/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:16:47`; SERIES(scale,`multiseries/function`[`CylinderD/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc",0](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`CylinderD/infinity/aux/0/-Pi .. Pi/0/BasisVector/0/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[`CylinderD/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:16:47`; [`multiseries/function`[`CylinderD/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`CylinderD/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0]:=proc (n, a1) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:16:46`; [0, `multiseries/function`[`CylinderD/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0,a1)] end proc:
`multiseries/function`[`CylinderD/infinity/aux/0/-Pi .. Pi`]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:16:47`; if nops(exprlist) <> 2 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return `multiseries/Convert2SERIES`(`CylinderD/infinity/aux/0/-Pi .. Pi`(paramseq,0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := `multiseries/function`[`CylinderD/infinity/aux/0/-Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(`multiseries/function`[`CylinderD/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = ('`CylinderD/infinity/aux/0/-Pi .. Pi`')(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[`CylinderD/infinity/aux/0/-Pi .. Pi`, 0]:=proc (expr, scale, var, order, a1) local d1, loc1, loc2, res, res1; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:16:47`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[`CylinderD/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1); loc2 := 1; if type(a1,'numeric') then loc2 := eval(loc2,d1 = a1) else loc2 := limit(loc2,d1 = a1,'left') end if; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*('`CylinderD/infinity/aux/0/-Pi .. Pi`')(a1,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = ('`CylinderD/infinity/aux/0/-Pi .. Pi`')(a1,op(9,expr)),res) end proc:
`multiseries/function`[`CylinderD/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c, a1) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:16:46`; if n = 0 then [normal(1)] elif n = 1 then [normal(1), normal(0)] else loc[0] := normal(1); loc[1] := normal(0); for i1 from 2 to n do loc[i1] := normal(-(a1^2+3*a1-3*c+2-2*a1*c+c^2+(-3+2*c-2*a1+i1)*i1)*loc[i1-2]/(c+i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[CylinderD]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:16:47`; if nops(exprlist) <> 2 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return `multiseries/Convert2SERIES`(CylinderD(paramseq,0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := `multiseries/function`[CylinderD,0](argseq) elif lim = infinity then res := `multiseries/function`[CylinderD,infinity,-Pi .. Pi](argseq,[[op(1 .. -2,exprlist), op(1,[argseq])], scale, var, order]) else res := eval(`multiseries/function`[CylinderD,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = ('CylinderD')(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[`CylinderD/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:16:46`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[`CylinderD/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`CylinderD/infinity/aux/0/-Pi .. Pi`(a1,_AnyFiniteOrdinaryPoint),D[2](`CylinderD/infinity/aux/0/-Pi .. Pi`)(a1,_AnyFiniteOrdinaryPoint),a1,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`CylinderD/infinity/aux/0/-Pi .. Pi`(a1,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[CylinderD, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:16:46`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[CylinderD,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,CylinderD(a1,_AnyFiniteOrdinaryPoint),1/2*_AnyFiniteOrdinaryPoint*CylinderD(a1,_AnyFiniteOrdinaryPoint)-CylinderD(a1+1,_AnyFiniteOrdinaryPoint),a1,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),CylinderD(a1,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
