# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[`dawson/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, xarg) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:40`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, -1/xarg^3*(xarg*arg0+2*arg1*xarg^2-arg1)] else loc[0] := arg0; loc[1] := arg1; loc[2] := -1/xarg^3*(xarg*arg0+2*arg1*xarg^2-arg1); for i1 from 3 to n do loc[i1] := (2*loc[i1-3]+4*xarg*loc[i1-2]-(-2*xarg^2-2)*loc[i1-1]-(loc[i1-3]+3*xarg*loc[i1-2]+3*xarg^2*loc[i1-1])*i1)/xarg^3/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`dawson/infinity/aux/0/-Pi .. Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:41`; if expr = 0 then return `multiseries/Convert2SERIES`(`dawson/infinity/aux/0/-Pi .. Pi`(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := `multiseries/function`[`dawson/infinity/aux/0/-Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(`multiseries/function`[`dawson/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = ('`dawson/infinity/aux/0/-Pi .. Pi`')(op(9,expr)),res) end proc:
`multiseries/function`[`dawson/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:41`; if n = 0 then [1] elif n = 1 then [1, 0] else loc[0] := 1; loc[1] := 0; for i1 from 2 to n do loc[i1] := 1/2*(c-1+i1)*loc[i1-2] end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`dawson/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:41`; [`multiseries/function`[`dawson/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[dawson, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:40`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[dawson,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,dawson(_AnyFiniteOrdinaryPoint),1-2*_AnyFiniteOrdinaryPoint*dawson(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),dawson(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[dawson, 0]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:40`; `multiseries/compose`(SERIES(scale,`multiseries/function`[dawson,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,0,1,0),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),dawson(eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`dawson/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:41`; SERIES(scale,`multiseries/function`[`dawson/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dawson/infinity/aux/0/-Pi .. Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[dawson, infinity, -Pi .. Pi]:=proc (expr, scale, var, order, arglist) local res; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:41`; res := `multiseries/add`([`multiseries/mul`([expr, `multiseries/function`[`dawson/infinity/aux/0/-Pi .. Pi`](op(arglist))]), `multiseries/mul`([`multiseries/function`[exp](`multiseries/MulDoit`(`multiseries/pow`(expr,-2,scale,var,order),-1),scale,var,order), `multiseries/Convert2SERIES`(-1/2*I*Pi^(1/2),scale,var,false)])]) end proc:
`multiseries/function`[`dawson/infinity/aux/0/-Pi .. Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:41`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[`dawson/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := 1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*('`dawson/infinity/aux/0/-Pi .. Pi`')(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = ('`dawson/infinity/aux/0/-Pi .. Pi`')(op(9,expr)),res) end proc:
`multiseries/function`[dawson, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, xarg) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:40`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] else loc[0] := arg0; loc[1] := arg1; for i1 from 2 to n do loc[i1] := (-2*loc[i1-2]-2*xarg*loc[i1-1])/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`dawson/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:41`; `multiseries/function`[`dawson/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[`dawson/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:40`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[`dawson/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`dawson/infinity/aux/0/-Pi .. Pi`(_AnyFiniteOrdinaryPoint),diff(`dawson/infinity/aux/0/-Pi .. Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`dawson/infinity/aux/0/-Pi .. Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[dawson]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:41`; if expr = 0 then return `multiseries/Convert2SERIES`(dawson(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := `multiseries/function`[dawson,0](argseq) elif lim = infinity then res := `multiseries/function`[dawson,infinity,-Pi .. Pi](argseq,[op(1,[argseq]), scale, var, order]) else res := eval(`multiseries/function`[dawson,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = ('dawson')(op(9,expr)),res) end proc:
`multiseries/function`[`dawson/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 11:19:41`; [0, `multiseries/function`[`dawson/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0)] end proc:
