# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[WhittakerM, 0, "CoeffProc", _a2+1/2]:=proc (n, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:47:59`; `multiseries/function`[WhittakerM,0,"CoeffProc"](n,a2+1/2,a1,a2) end proc:
`multiseries/function`[`WhittakerM/infinity/aux/0/-Pi .. Pi`, 0]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:01`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[`WhittakerM/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := GAMMA(2*d2+1)/GAMMA(1/2+d2-d1); if type([a1, a2],list('numeric')) then loc2 := eval(loc2,[d1 = a1, d2 = a2]) else loc2 := limit(limit(GAMMA(2*d2+1)/GAMMA(1/2+d2-d1),d1 = a1,'left'),d2 = a2,'left') end if; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*('`WhittakerM/infinity/aux/0/-Pi .. Pi`')(a1,a2,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = ('`WhittakerM/infinity/aux/0/-Pi .. Pi`')(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[`WhittakerM/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c, a1, a2) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:00`; if n = 0 then [normal(1)] else loc[0] := normal(1); for i1 to n do loc[i1] := normal(-(-4*a2^2-4*a1+4*a1^2+1-4*c+4*c^2+8*a1*c+(-4+8*c+8*a1+4*i1)*i1)*loc[i1-1]/(-4*c-4*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[WhittakerM, 0, "BasisVector", -_a2+1/2, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:00`; [`multiseries/function`[WhittakerM,0,"BasisVector",-_a2+1/2,"MultiSeries",0](args)] end proc:
`multiseries/function`[WhittakerM, 0, "BasisVector", -_a2+1/2]:=proc (n, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:47:59`; [-a2+1/2, `multiseries/function`[WhittakerM,0,"CoeffProc"](n,-a2+1/2,a1,a2)] end proc:
`multiseries/function`[WhittakerM, 0, "BasisVector", _a2+1/2, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:47:59`; [`multiseries/function`[WhittakerM,0,"BasisVector",_a2+1/2,"MultiSeries",0](args)] end proc:
`multiseries/function`[WhittakerM, infinity, -Pi .. Pi]:=proc (expr, scale, var, order, a1, a2, arglist) local res; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:01`; res := `multiseries/add`([`multiseries/mul`([`multiseries/pow`(expr,a1,scale,var,order), `multiseries/function`[exp](`multiseries/MulDoit`(`multiseries/pow`(expr,-1,scale,var,order),1/2),scale,var,order), `multiseries/function`[`WhittakerM/infinity/aux/0/-Pi .. Pi`](op(arglist))])]) end proc:
`multiseries/function`[`WhittakerM/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, a1, a2, xarg) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:00`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] else loc[0] := arg0; loc[1] := arg1; for i1 from 2 to n do loc[i1] := (-(-4*a2^2-12*a1+4*a1^2+9)*loc[i1-2]-(8*xarg-8*a1*xarg+4)*loc[i1-1]-((-12+8*a1)*loc[i1-2]+(-16*xarg-4+8*a1*xarg)*loc[i1-1]+(4*loc[i1-2]+8*xarg*loc[i1-1])*i1)*i1)/(-4*xarg^2+4*xarg^2*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[WhittakerM]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:01`; if nops(exprlist) <> 3 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return `multiseries/Convert2SERIES`(WhittakerM(paramseq,0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := `multiseries/function`[WhittakerM,0](argseq) elif lim = infinity then res := `multiseries/function`[WhittakerM,infinity,-Pi .. Pi](argseq,[[op(1 .. -2,exprlist), op(1,[argseq])], scale, var, order]) else res := eval(`multiseries/function`[WhittakerM,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = ('WhittakerM')(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[WhittakerM, 0, "CoeffProc", -_a2+1/2]:=proc (n, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:47:59`; `multiseries/function`[WhittakerM,0,"CoeffProc"](n,-a2+1/2,a1,a2) end proc:
`multiseries/function`[`WhittakerM/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:00`; `multiseries/function`[`WhittakerM/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0,a1,a2) end proc:
`multiseries/function`[WhittakerM, 0, "BasisVector", _a2+1/2]:=proc (n, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:47:59`; [a2+1/2, `multiseries/function`[WhittakerM,0,"CoeffProc"](n,a2+1/2,a1,a2)] end proc:
`multiseries/function`[`WhittakerM/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0]:=proc (n, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:00`; [0, `multiseries/function`[`WhittakerM/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0,a1,a2)] end proc:
`multiseries/function`[`WhittakerM/infinity/aux/0/-Pi .. Pi`]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:01`; if nops(exprlist) <> 3 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return `multiseries/Convert2SERIES`(`WhittakerM/infinity/aux/0/-Pi .. Pi`(paramseq,0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := `multiseries/function`[`WhittakerM/infinity/aux/0/-Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(`multiseries/function`[`WhittakerM/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = ('`WhittakerM/infinity/aux/0/-Pi .. Pi`')(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[`WhittakerM/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:00`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[`WhittakerM/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`WhittakerM/infinity/aux/0/-Pi .. Pi`(a1,a2,_AnyFiniteOrdinaryPoint),D[3](`WhittakerM/infinity/aux/0/-Pi .. Pi`)(a1,a2,_AnyFiniteOrdinaryPoint),a1,a2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`WhittakerM/infinity/aux/0/-Pi .. Pi`(a1,a2,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[WhittakerM, 0, "CoeffProc"]:=proc (n, c, a1, a2) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:47:59`; if n = 0 then [normal(1)] elif n = 1 then [normal(1), normal(4*a1/(-4*c^2-4*c-1+4*a2^2))] else loc[0] := normal(1); loc[1] := normal(4*a1/(-4*c^2-4*c-1+4*a2^2)); for i1 from 2 to n do loc[i1] := normal((loc[i1-2]-4*a1*loc[i1-1])/(4*c^2+1-4*a2^2-4*c+(8*c-4+4*i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`WhittakerM/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:00`; SERIES(scale,`multiseries/function`[`WhittakerM/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc",0](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`WhittakerM/infinity/aux/0/-Pi .. Pi/0/BasisVector/0/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[WhittakerM, 0, "BasisVector", -_a2+1/2, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:47:59`; SERIES(scale,`multiseries/function`[WhittakerM,0,"CoeffProc",-_a2+1/2](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`WhittakerM/0/BasisVector/-_a2+1/2/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[WhittakerM, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:47:59`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[WhittakerM,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,WhittakerM(a1,a2,_AnyFiniteOrdinaryPoint),(1/2-a1/_AnyFiniteOrdinaryPoint)*WhittakerM(a1,a2,_AnyFiniteOrdinaryPoint)+(1/2+a2+a1)/_AnyFiniteOrdinaryPoint*WhittakerM(a1+1,a2,_AnyFiniteOrdinaryPoint),a1,a2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),WhittakerM(a1,a2,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[WhittakerM, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, a1, a2, xarg) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:47:59`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, -1/8*arg0*(-xarg^2+4*a1*xarg+1-4*a2^2)/xarg^2] elif n = 3 then [arg0, arg1, -1/8*arg0*(-xarg^2+4*a1*xarg+1-4*a2^2)/xarg^2, 1/24*(4*arg0*a1*xarg+arg1*xarg^3-4*arg1*a1*xarg^2-arg1*xarg+4*arg1*a2^2*xarg+2*arg0-8*arg0*a2^2)/xarg^3] else loc[0] := arg0; loc[1] := arg1; loc[2] := -1/8*arg0*(-xarg^2+4*a1*xarg+1-4*a2^2)/xarg^2; loc[3] := 1/24*(4*arg0*a1*xarg+arg1*xarg^3-4*arg1*a1*xarg^2-arg1*xarg+4*arg1*a2^2*xarg+2*arg0-8*arg0*a2^2)/xarg^3; for i1 from 4 to n do loc[i1] := (loc[i1-4]-(-2*xarg+4*a1)*loc[i1-3]-(-xarg^2+4*a1*xarg+25-4*a2^2)*loc[i1-2]-16*xarg*loc[i1-1]-(-20*loc[i1-2]-24*xarg*loc[i1-1]+(4*loc[i1-2]+8*xarg*loc[i1-1])*i1)*i1)/(-4*xarg^2+4*xarg^2*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[WhittakerM, 0, "BasisVector", _a2+1/2, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:47:59`; SERIES(scale,`multiseries/function`[WhittakerM,0,"CoeffProc",_a2+1/2](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`WhittakerM/0/BasisVector/_a2+1/2/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[WhittakerM, 0]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:00`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[WhittakerM,0,"BasisVector",_a2+1/2,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := 1; if type([a1, a2],list('numeric')) then loc2 := eval(loc2,[d1 = a1, d2 = a2]) else loc2 := limit(limit(1,d1 = a1,'left'),d2 = a2,'left') end if; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*('WhittakerM')(a1,a2,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],a2+1/2,loc2,0); res := res1; subsop(9 = ('WhittakerM')(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[`WhittakerM/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:00`; [`multiseries/function`[`WhittakerM/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
