# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[WhittakerW, 0, _a2::0, "BasisVector", 1/2, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:03`; SERIES(scale,`multiseries/function`[WhittakerW,0,_a2::0,"CoeffProc",1/2,0,0](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`WhittakerW/0/_a2::0/BasisVector/1/2/0/0/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[WhittakerW, 0, _a2::0, "CoeffProc", 1/2, 0, 0]:=proc (n, a1, a2) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:02`; if n = 0 then [1] elif n = 1 then [1, a1/(-1+a2^2)] elif n = 2 then [1, a1/(-1+a2^2), 1/4*(1-a2^2+4*a1^2)/(4-5*a2^2+a2^4)] else loc[0] := 1; loc[1] := a1/(-1+a2^2); loc[2] := 1/4*(1-a2^2+4*a1^2)/(4-5*a2^2+a2^4); for i1 from 3 to n do loc[i1] := normal((loc[i1-2]-4*a1*loc[i1-1])/(4*i1^2-4*a2^2)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[WhittakerW]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:08`; if nops(exprlist) <> 3 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return `multiseries/Convert2SERIES`(WhittakerW(paramseq,0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := `multiseries/function`[WhittakerW,0](argseq) elif lim = infinity then res := `multiseries/function`[WhittakerW,infinity,-Pi .. Pi](argseq,[[op(1 .. -2,exprlist), op(1,[argseq])], scale, var, order]) else res := eval(`multiseries/function`[WhittakerW,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = ('WhittakerW')(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[`WhittakerW/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0]:=proc (n, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:07`; [0, `multiseries/function`[`WhittakerW/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0,a1,a2)] end proc:
`multiseries/function`[WhittakerW, 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:05`; if is(a2::0) then userinfo(2,WhittakerW,`maincase:`,a2::0); `multiseries/function`[WhittakerW,0,_a2::0](expr,scale,var,order,a1,a2) else userinfo(2,WhittakerW,`generic case`); `multiseries/function`[WhittakerW,0,"Generic"](expr,scale,var,order,a1,a2) end if end proc:
`multiseries/function`[WhittakerW, 0, "Generic", "BasisVector", _a2+1/2, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:04`; [`multiseries/function`[WhittakerW,0,"Generic","BasisVector",_a2+1/2,"MultiSeries",0](args)] end proc:
`multiseries/function`[`WhittakerW/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:06`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[`WhittakerW/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`WhittakerW/infinity/aux/0/-Pi .. Pi`(a1,a2,_AnyFiniteOrdinaryPoint),D[3](`WhittakerW/infinity/aux/0/-Pi .. Pi`)(a1,a2,_AnyFiniteOrdinaryPoint),a1,a2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`WhittakerW/infinity/aux/0/-Pi .. Pi`(a1,a2,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`WhittakerW/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c, a1, a2) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:06`; if n = 0 then [normal(1)] else loc[0] := normal(1); for i1 to n do loc[i1] := normal(-(-4*a2^2+4*a1+4*a1^2+1-4*c+4*c^2-8*a1*c+(-4+8*c-8*a1+4*i1)*i1)*loc[i1-1]/(4*c+4*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`WhittakerW/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:07`; SERIES(scale,`multiseries/function`[`WhittakerW/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc",0](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`WhittakerW/infinity/aux/0/-Pi .. Pi/0/BasisVector/0/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[WhittakerW, 0, "Generic", "BasisVector", -_a2+1/2, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:04`; SERIES(scale,`multiseries/function`[WhittakerW,0,"Generic","CoeffProc",-_a2+1/2](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`WhittakerW/0/Generic/BasisVector/-_a2+1/2/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[WhittakerW, 0, "Generic", "CoeffProc", -_a2+1/2]:=proc (n, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:04`; `multiseries/function`[WhittakerW,0,"Generic","CoeffProc"](n,-a2+1/2,a1,a2) end proc:
`multiseries/function`[WhittakerW, 0, "Generic", "BasisVector", -_a2+1/2]:=proc (n, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:04`; [-a2+1/2, `multiseries/function`[WhittakerW,0,"Generic","CoeffProc"](n,-a2+1/2,a1,a2)] end proc:
`multiseries/function`[WhittakerW, infinity, -Pi .. Pi]:=proc (expr, scale, var, order, a1, a2, arglist) local res; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:08`; res := `multiseries/add`([`multiseries/mul`([`multiseries/pow`(expr,-a1,scale,var,order), `multiseries/function`[exp](`multiseries/MulDoit`(`multiseries/pow`(expr,-1,scale,var,order),-1/2),scale,var,order), `multiseries/function`[`WhittakerW/infinity/aux/0/-Pi .. Pi`](op(arglist))])]) end proc:
`multiseries/function`[WhittakerW, 0, _a2::0, "BasisVector", 1/2, 0, 1, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:03`; [`multiseries/function`[WhittakerW,0,_a2::0,"BasisVector",1/2,0,1,"MultiSeries",0](args), `multiseries/function`[WhittakerW,0,_a2::0,"BasisVector",1/2,0,1,"MultiSeries",1](args)] end proc:
`multiseries/function`[WhittakerW, 0, _a2::0, "BasisVector", 1/2, 0, 1, "MultiSeries", 1]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:03`; SERIES(scale,`multiseries/function`[WhittakerW,0,_a2::0,"CoeffProc",1/2,0,0](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`WhittakerW/0/_a2::0/BasisVector/1/2/0/1/MultiSeries/1`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[WhittakerW, 0, _a2::0, "CoeffProc", 1/2, 0, 1]:=proc (n, a1, a2) local i1, loc, xxloc1; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:02`; xxloc1 := `multiseries/function`[WhittakerW,0,_a2::0,"CoeffProc",1/2,0,0](n,a1,a2); if n = 0 then [0] elif n = 1 then [0, 2*a1/(1-2*a2^2+a2^4)] elif n = 2 then [0, 2*a1/(1-2*a2^2+a2^4), (-12*a1^2+6*a1^2*a2^2-1+2*a2^2-a2^4)/(16-40*a2^2+33*a2^4-10*a2^6+a2^8)] else loc[0] := 0; loc[1] := 2*a1/(1-2*a2^2+a2^4); loc[2] := (-12*a1^2+6*a1^2*a2^2-1+2*a2^2-a2^4)/(16-40*a2^2+33*a2^4-10*a2^6+a2^8); for i1 from 3 to n do loc[i1] := normal((-8*i1*op(i1+1,xxloc1)+loc[i1-2]-4*a1*loc[i1-1])/(4*i1^2-4*a2^2)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[WhittakerW, 0, "Generic"]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1, res2; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:05`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[WhittakerW,0,"Generic","BasisVector",_a2+1/2,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := Pi/sin(Pi*(2*d2+1))/GAMMA(2*d2+1)/GAMMA(1/2-d2-d1); if type([a1, a2],list('numeric')) then loc2 := eval(loc2,[d1 = a1, d2 = a2]) else loc2 := limit(limit(Pi/sin(Pi*(2*d2+1))/GAMMA(2*d2+1)/GAMMA(1/2-d2-d1),d1 = a1,'left'),d2 = a2,'left') end if; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],a2+1/2,loc2,0); loc1 := `multiseries/function`[WhittakerW,0,"Generic","BasisVector",-_a2+1/2,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := Pi/sin(Pi*(2*d2+1))/GAMMA(1-2*d2)/GAMMA(1/2+d2-d1); if type([a1, a2],list('numeric')) then loc2 := eval(loc2,[d1 = a1, d2 = a2]) else loc2 := limit(limit(Pi/sin(Pi*(2*d2+1))/GAMMA(1-2*d2)/GAMMA(1/2+d2-d1),d1 = a1,'left'),d2 = a2,'left') end if; res2 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],-a2+1/2,loc2,0); res := `multiseries/add`([res1, res2]); subsop(9 = ('WhittakerW')(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[WhittakerW, 0, "Generic", "CoeffProc"]:=proc (n, c, a1, a2) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:03`; if n = 0 then [normal(1)] elif n = 1 then [normal(1), normal(4*a1/(-4*c^2-4*c-1+4*a2^2))] else loc[0] := normal(1); loc[1] := normal(4*a1/(-4*c^2-4*c-1+4*a2^2)); for i1 from 2 to n do loc[i1] := normal((loc[i1-2]-4*a1*loc[i1-1])/(4*c^2+1-4*a2^2-4*c+(8*c-4+4*i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[WhittakerW, 0, "Generic", "CoeffProc", _a2+1/2]:=proc (n, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:04`; `multiseries/function`[WhittakerW,0,"Generic","CoeffProc"](n,a2+1/2,a1,a2) end proc:
`multiseries/function`[`WhittakerW/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, a1, a2, xarg) local i1, loc; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:05`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] else loc[0] := arg0; loc[1] := arg1; for i1 from 2 to n do loc[i1] := (-(-4*a2^2+12*a1+4*a1^2+9)*loc[i1-2]-(8*xarg+8*a1*xarg-4)*loc[i1-1]-((-12-8*a1)*loc[i1-2]+(-16*xarg+4-8*a1*xarg)*loc[i1-1]+(4*loc[i1-2]+8*xarg*loc[i1-1])*i1)*i1)/(-4*xarg^2+4*xarg^2*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[WhittakerW, 0, "Generic", "BasisVector", -_a2+1/2, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:05`; [`multiseries/function`[WhittakerW,0,"Generic","BasisVector",-_a2+1/2,"MultiSeries",0](args)] end proc:
`multiseries/function`[WhittakerW, 0, _a2::0, "BasisVector", 1/2, 0, 1]:=proc (n, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:03`; [1/2, `multiseries/function`[WhittakerW,0,_a2::0,"CoeffProc",1/2,0,1](n,a1,a2), `multiseries/function`[WhittakerW,0,_a2::0,"CoeffProc",1/2,0,0](n,a1,a2)] end proc:
`multiseries/function`[`WhittakerW/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:07`; `multiseries/function`[`WhittakerW/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0,a1,a2) end proc:
`multiseries/function`[WhittakerW, 0, "Generic", "BasisVector", _a2+1/2, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:04`; SERIES(scale,`multiseries/function`[WhittakerW,0,"Generic","CoeffProc",_a2+1/2](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`WhittakerW/0/Generic/BasisVector/_a2+1/2/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[`WhittakerW/infinity/aux/0/-Pi .. Pi`, 0]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:08`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[`WhittakerW/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := 1; if type([a1, a2],list('numeric')) then loc2 := eval(loc2,[d1 = a1, d2 = a2]) else loc2 := limit(limit(1,d1 = a1,'left'),d2 = a2,'left') end if; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*('`WhittakerW/infinity/aux/0/-Pi .. Pi`')(a1,a2,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = ('`WhittakerW/infinity/aux/0/-Pi .. Pi`')(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[WhittakerW, 0, _a2::0]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1, res2; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:03`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[WhittakerW,0,_a2::0,"BasisVector",1/2,0,0,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := -(Psi(1/2-d1)+2*gamma)/GAMMA(1/2-d1); if type([a1, a2],list('numeric')) then loc2 := eval(loc2,[d1 = a1, d2 = a2]) else loc2 := limit(limit(-(Psi(1/2-d1)+2*gamma)/GAMMA(1/2-d1),d1 = a1,'left'),d2 = a2,'left') end if; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],1/2,loc2,0); loc1 := `multiseries/function`[WhittakerW,0,_a2::0,"BasisVector",1/2,0,1,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := -1/GAMMA(1/2-d1); if type([a1, a2],list('numeric')) then loc2 := eval(loc2,[d1 = a1, d2 = a2]) else loc2 := limit(limit(-1/GAMMA(1/2-d1),d1 = a1,'left'),d2 = a2,'left') end if; res2 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],1/2,loc2,0); res := `multiseries/add`([res1, res2]); subsop(9 = ('WhittakerW')(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[WhittakerW, 0, "Generic", "BasisVector", _a2+1/2]:=proc (n, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:03`; [a2+1/2, `multiseries/function`[WhittakerW,0,"Generic","CoeffProc"](n,a2+1/2,a1,a2)] end proc:
`multiseries/function`[WhittakerW, 0, _a2::0, "BasisVector", 1/2, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:03`; [`multiseries/function`[WhittakerW,0,_a2::0,"BasisVector",1/2,0,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`WhittakerW/infinity/aux/0/-Pi .. Pi`]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:08`; if nops(exprlist) <> 3 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return `multiseries/Convert2SERIES`(`WhittakerW/infinity/aux/0/-Pi .. Pi`(paramseq,0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := `multiseries/function`[`WhittakerW/infinity/aux/0/-Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(`multiseries/function`[`WhittakerW/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = ('`WhittakerW/infinity/aux/0/-Pi .. Pi`')(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[WhittakerW, 0, _a2::0, "BasisVector", 1/2, 0, 1, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:03`; SERIES(scale,`multiseries/function`[WhittakerW,0,_a2::0,"CoeffProc",1/2,0,1](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`WhittakerW/0/_a2::0/BasisVector/1/2/0/1/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[WhittakerW, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:01`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[WhittakerM,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,WhittakerW(a1,a2,_AnyFiniteOrdinaryPoint),(1/2-a1/_AnyFiniteOrdinaryPoint)*WhittakerW(a1,a2,_AnyFiniteOrdinaryPoint)-1/_AnyFiniteOrdinaryPoint*WhittakerW(a1+1,a2,_AnyFiniteOrdinaryPoint),a1,a2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),WhittakerW(a1,a2,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`WhittakerW/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:07`; [`multiseries/function`[`WhittakerW/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[WhittakerW, 0, _a2::0, "BasisVector", 1/2, 0, 0]:=proc (n, a1, a2) option `Copyright (c) 2006 by the Algorithms Project, INRIA. All rights reserved. - generated 05/16/2006 @ 12:48:03`; [1/2, `multiseries/function`[WhittakerW,0,_a2::0,"CoeffProc",1/2,0,0](n,a1,a2)] end proc:
