# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:22`; `multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[AiryAi, 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:21`; `multiseries/compose`(SERIES(scale,`multiseries/function`[AiryAi,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,1/3*3^(1/3)/GAMMA(2/3),-1/2*3^(1/6)/Pi*GAMMA(2/3),0),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),AiryAi(eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[AiryAi, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:21`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, 1/2*xarg*arg0] else loc[0] := arg0; loc[1] := arg1; loc[2] := 1/2*xarg*arg0; for i1 from 3 to n do loc[i1] := (loc[i1-3]+xarg*loc[i1-2])/i1/(i1-1) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[AiryAi]:=proc (expr, scale, var, order) local lim, lim2, asymptdir, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:23`; if expr = 0 then return `multiseries/Convert2SERIES`(AiryAi(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then if has(lim,exp) then asymptdir := op(select(type,lim,specfunc(anything,exp))) elif 1 < nops(lim) then asymptdir := argument(subs(infinity = 1,lim)) else asymptdir := 0 end if; lim := infinity else asymptdir := argument(lim) end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := `multiseries/function`[AiryAi,0](argseq) elif lim = infinity then if evalb(signum(-1/3*Pi-asymptdir) <> 1) and evalb(signum(1/3*Pi-asymptdir) <> -1) then res := `multiseries/function`[AiryAi,infinity,-1/3*Pi .. 1/3*Pi](argseq,[op(1,[argseq]), scale, var, order]) else error "unable to compute series" end if else res := eval(`multiseries/function`[AiryAi,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = AiryAi(op(9,expr)),res) end proc:
`multiseries/function`[AiryAi, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:21`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[AiryAi,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,AiryAi(_AnyFiniteOrdinaryPoint),AiryAi(1,_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),AiryAi(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:22`; [0, `multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:22`; SERIES(scale,`multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:22`; [`multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:23`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := 1/2/Pi^(1/2); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[AiryAi, infinity, -1/3*Pi .. 1/3*Pi]:=proc (expr, scale, var, order, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:23`; res := `multiseries/add`([`multiseries/mul`([`multiseries/compose`(`multiseries/pow`(SERIES(scale,[1],0,integer,[1],infinity,integer,eval(scale['variable'],1),eval(scale['variable'],1)),1/2,scale,var,order),`multiseries/pow`(expr,1/2,scale,var,order),scale,var,order), `multiseries/function`[exp](`multiseries/MulDoit`(`multiseries/pow`(`multiseries/pow`(expr,1/2,scale,var,order),-3,scale,var,order),-2/3),scale,var,order), `multiseries/compose`(`multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`](SERIES(scale,[1],0,integer,[1],infinity,integer,eval(scale['variable'],1),eval(scale['variable'],1)),scale,[eval(scale['variable'],1)],order),`multiseries/pow`(expr,1/2,scale,var,order),scale,var,order)])]) end proc:
`multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:22`; if n = 0 then [1] elif n = 1 then [1, 0] elif n = 2 then [1, 0, 0] else loc[0] := 1; loc[1] := 0; loc[2] := 0; for i1 from 3 to n do loc[i1] := -(5-12*c+4*c^2+(8*c-12+4*i1)*i1)*loc[i1-3]/(16*c+16*i1) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:23`; if expr = 0 then return `multiseries/Convert2SERIES`(`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := `multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(`multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:21`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, -1/8/xarg^4*(5*xarg^2*arg0+16*arg1*xarg^3+16*arg1)] elif n = 3 then [arg0, arg1, -1/8/xarg^4*(5*xarg^2*arg0+16*arg1*xarg^3+16*arg1), 1/24*(30*xarg^5*arg0+75*xarg^6*arg1+192*arg1*xarg^3+20*xarg^2*arg0+64*arg1)/xarg^8] else loc[0] := arg0; loc[1] := arg1; loc[2] := -1/8/xarg^4*(5*xarg^2*arg0+16*arg1*xarg^3+16*arg1); loc[3] := 1/24*(30*xarg^5*arg0+75*xarg^6*arg1+192*arg1*xarg^3+20*xarg^2*arg0+64*arg1)/xarg^8; for i1 from 4 to n do loc[i1] := (-21*loc[i1-4]-(16*xarg^3-16)*loc[i1-1]-53*xarg^2*loc[i1-2]-58*xarg*loc[i1-3]-(-64*xarg*loc[i1-3]-20*loc[i1-4]+(16-32*xarg^3)*loc[i1-1]-72*xarg^2*loc[i1-2]+(24*xarg^2*loc[i1-2]+16*xarg*loc[i1-3]+4*loc[i1-4]+16*xarg^3*loc[i1-1])*i1)*i1)/(-4*xarg^4+4*xarg^4*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:11:22`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(_AnyFiniteOrdinaryPoint),diff(`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
