# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[arccsc, -1, "BasisVector", 1/2, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:58`; SERIES(scale,`multiseries/function`[arccsc,-1,"CoeffProc",1/2](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`arccsc/-1/BasisVector/1/2/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[arccsc, -1, "BasisVector", 1/2, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:58`; [`multiseries/function`[arccsc,-1,"BasisVector",1/2,"MultiSeries",0](args)] end proc:
`multiseries/function`[arccsc, -1, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:56`; `multiseries/function`[arccsc,-1,"CoeffProc"](n,0) end proc:
`multiseries/function`[arccsc, 0, "CoeffProc", 0, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:49`; loc[0] := 1; loc[1] := 0; loc[2] := 0; for i1 from 3 to n do loc[i1] := (2+(i1-3)*i1)*loc[i1-2]/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[arccsc, 1, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:52`; if n = 0 then [1] elif n = 1 then [1, -c*(3*c+1)/(2*c^2+3*c+1)] else loc[0] := 1; loc[1] := -c*(3*c+1)/(2*c^2+3*c+1); for i1 from 2 to n do loc[i1] := (-(c^2-3*c+2)*loc[i1-2]-(3*c^2-5*c+2)*loc[i1-1]-((2*c-3)*loc[i1-2]+(6*c-5)*loc[i1-1]+(loc[i1-2]+3*loc[i1-1])*i1)*i1)/(-c+2*c^2+(4*c-1+2*i1)*i1) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[arccsc, -1, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:58`; [`multiseries/function`[arccsc,-1,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[arccsc, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:52`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[arccsc,0,"BasisVector",0,0,0,"MultiSeries"](expr,scale,var,order); loc2 := -I*ln(2)+1/2*Pi; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); loc1 := `multiseries/function`[arccsc,0,"BasisVector",0,0,1,"MultiSeries"](expr,scale,var,order); loc2 := I; res2 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := `multiseries/add`([res1, res2]); subsop(9 = arccsc(op(9,expr)),res) end proc:
`multiseries/function`[arccsc, 0, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:50`; SERIES(scale,`multiseries/function`[arccsc,0,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`arccsc/0/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[arccsc, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:48`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[arccsc,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,arccsc(_AnyFiniteOrdinaryPoint),-1/_AnyFiniteOrdinaryPoint^2/(1-1/_AnyFiniteOrdinaryPoint^2)^(1/2),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),arccsc(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[arccsc, 0, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:51`; [`multiseries/function`[arccsc,0,"BasisVector",0,0,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[arccsc, 1, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:54`; [`multiseries/function`[arccsc,1,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[arccsc, 1, "BasisVector", 1/2, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:55`; [`multiseries/function`[arccsc,1,"BasisVector",1/2,"MultiSeries",0](args)] end proc:
`multiseries/function`[arccsc, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:47`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, -1/2*arg1*(2*xarg^2-1)/xarg/(xarg^2-1)] else loc[0] := arg0; loc[1] := arg1; loc[2] := -1/2*arg1*(2*xarg^2-1)/xarg/(xarg^2-1); for i1 from 3 to n do loc[i1] := (-6*loc[i1-3]-(4*xarg^2-1)*loc[i1-1]-10*xarg*loc[i1-2]-(-5*loc[i1-3]-11*xarg*loc[i1-2]+(2-7*xarg^2)*loc[i1-1]+(3*xarg*loc[i1-2]+loc[i1-3]+(-1+3*xarg^2)*loc[i1-1])*i1)*i1)/(xarg-xarg^3+(-xarg+xarg^3)*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[arccsc, -1, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:56`; [0, `multiseries/function`[arccsc,-1,"CoeffProc"](n,0)] end proc:
`multiseries/function`[arccsc, 1, "BasisVector", 1/2, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:55`; SERIES(scale,`multiseries/function`[arccsc,1,"CoeffProc",1/2](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`arccsc/1/BasisVector/1/2/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[arccsc, -1, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:57`; SERIES(scale,`multiseries/function`[arccsc,-1,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`arccsc/-1/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[arccsc, 1]:=proc (expr, scale, var, order) local loc1, loc2, loc3, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:55`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc3 := `multiseries/MulSeriesCst`(expr,1,algebraic); loc1 := `multiseries/function`[arccsc,1,"BasisVector",0,"MultiSeries"](loc3,scale,var,order); loc2 := 1/2*Pi; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[loc3, scale, var, order],0,loc2,1); loc1 := `multiseries/function`[arccsc,1,"BasisVector",1/2,"MultiSeries"](loc3,scale,var,order); loc2 := -2^(1/2); res2 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[loc3, scale, var, order],1/2,loc2,1); res := `multiseries/add`([res1, res2]); subsop(9 = arccsc(op(9,expr)),res) end proc:
`multiseries/function`[arccsc, 0, "BasisVector", 0, 0, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:52`; [`multiseries/function`[arccsc,0,"BasisVector",0,0,1,"MultiSeries",0](args), `multiseries/function`[arccsc,0,"BasisVector",0,0,1,"MultiSeries",1](args)] end proc:
`multiseries/function`[arccsc]:=proc (expr, scale, var, order) local tmp, re, im, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:59`; if expr = 0 then return `multiseries/Convert2SERIES`(arccsc(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = -1 or Testzero(lim+1) then res := `multiseries/function`[arccsc,-1](argseq) elif lim = 0 then res := `multiseries/function`[arccsc,0](argseq) elif lim = 1 or Testzero(lim-1) then res := `multiseries/function`[arccsc,1](argseq) elif lim = infinity then res := `multiseries/function`[arccsc,infinity](argseq) else res := eval(`multiseries/function`[arccsc,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; if _Envnobranchcut <> true then if `multiseries/IsOnBranchCut`([-1, 1],expr,scale,var) then userinfo(2,MultiSeries,`branchcut:`,arccsc,[-1, 1]); if lim = infinity then im := `multiseries/sign`(Im(`multiseries/MulSeriesCst`(expr,-1,algebraic))) else im := `multiseries/sign`(Im(`multiseries/MulSeriesCst`(`multiseries/AddDoit`(expr,-lim),-1,algebraic))) end if; if im = 1 then _Envnobranchcut := true; userinfo(2,MultiSeries,`jump:`,arccsc,`multiseries/run`(Pi-2*arccsc(expr),scale,var,order)); res := `multiseries/run`(Pi-2*arccsc(expr)+res,scale,var,order); _Envnobranchcut := false elif type(im,specfunc(anything,'signum')) or type(-im,specfunc(anything,signum)) then _Envnobranchcut := true; userinfo(2,MultiSeries,`jump:`,arccsc,`multiseries/run`(1/2*(im+1)*(Pi-2*arccsc(expr)),scale,var,order)); res := `multiseries/run`(1/2*(im+1)*(Pi-2*arccsc(expr))+res,scale,var,order); _Envnobranchcut := false end if end if end if; subsop(9 = arccsc(op(9,expr)),res) end proc:
`multiseries/function`[arccsc, 0, "BasisVector", 0, 0, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:50`; [0, `multiseries/function`[arccsc,0,"CoeffProc",0,0,1](n), `multiseries/function`[arccsc,0,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[arccsc, -1, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:56`; if n = 0 then [1] elif n = 1 then [1, -c*(3*c+1)/(2*c^2+3*c+1)] else loc[0] := 1; loc[1] := -c*(3*c+1)/(2*c^2+3*c+1); for i1 from 2 to n do loc[i1] := (-(c^2-3*c+2)*loc[i1-2]-(3*c^2-5*c+2)*loc[i1-1]-((2*c-3)*loc[i1-2]+(6*c-5)*loc[i1-1]+(loc[i1-2]+3*loc[i1-1])*i1)*i1)/(-c+2*c^2+(4*c-1+2*i1)*i1) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[arccsc, 0, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:50`; [0, `multiseries/function`[arccsc,0,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[arccsc, 1, "CoeffProc", 1/2]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:54`; `multiseries/function`[arccsc,1,"CoeffProc"](n,1/2) end proc:
`multiseries/function`[arccsc, 0, "BasisVector", 0, 0, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:51`; SERIES(scale,`multiseries/function`[arccsc,0,"CoeffProc",0,0,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`arccsc/0/BasisVector/0/0/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[arccsc, 1, "BasisVector", 1/2]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:53`; [1/2, `multiseries/function`[arccsc,1,"CoeffProc"](n,1/2)] end proc:
`multiseries/function`[arccsc, 0, "CoeffProc", 0, 0, 1]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:49`; xxloc1 := `multiseries/function`[arccsc,0,"CoeffProc",0,0,0](n); loc[0] := 0; loc[1] := 0; loc[2] := 1/4; for i1 from 3 to n do loc[i1] := -(-(-3+2*i1)*op(i1-1,xxloc1)+2*i1*op(i1+1,xxloc1)-(2+(i1-3)*i1)*loc[i1-2])/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[arccsc, 0, "BasisVector", 0, 0, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:51`; SERIES(scale,`multiseries/function`[arccsc,0,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`arccsc/0/BasisVector/0/0/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[arccsc, infinity]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:48`; `multiseries/compose`(SERIES(scale,`multiseries/function`[arccsc,infinity,"CoeffProc"](order,0,1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),arccsc(1/eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[arccsc, -1, "BasisVector", 1/2]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:57`; [1/2, `multiseries/function`[arccsc,-1,"CoeffProc"](n,1/2)] end proc:
`multiseries/function`[arccsc, 1, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:53`; [0, `multiseries/function`[arccsc,1,"CoeffProc"](n,0)] end proc:
`multiseries/function`[arccsc, -1]:=proc (expr, scale, var, order) local loc1, loc2, loc3, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:59`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc3 := `multiseries/MulSeriesCst`(expr,-1,algebraic); loc1 := `multiseries/function`[arccsc,-1,"BasisVector",0,"MultiSeries"](loc3,scale,var,order); loc2 := -1/2*Pi; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[loc3, scale, var, order],0,loc2,-1); loc1 := `multiseries/function`[arccsc,-1,"BasisVector",1/2,"MultiSeries"](loc3,scale,var,order); loc2 := 2^(1/2); res2 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[loc3, scale, var, order],1/2,loc2,-1); res := `multiseries/add`([res1, res2]); subsop(9 = arccsc(op(9,expr)),res) end proc:
`multiseries/function`[arccsc, -1, "CoeffProc", 1/2]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:57`; `multiseries/function`[arccsc,-1,"CoeffProc"](n,1/2) end proc:
`multiseries/function`[arccsc, infinity, "CoeffProc"]:=proc (n, arg0, arg1) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:48`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] else loc[0] := arg0; loc[1] := arg1; for i1 from 2 to n do loc[i1] := (i1-2)^2*loc[i1-2]/(i1-1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[arccsc, 1, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:53`; `multiseries/function`[arccsc,1,"CoeffProc"](n,0) end proc:
`multiseries/function`[arccsc, 1, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:22:54`; SERIES(scale,`multiseries/function`[arccsc,1,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`arccsc/1/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
