# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[EllipticCK, infinity, "BasisVector", 1, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:25`; [`multiseries/function`[EllipticCK,infinity,"BasisVector",1,0,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[EllipticCK, 0, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:17`; [0, `multiseries/function`[EllipticCK,0,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[EllipticCK, 0, "BasisVector", 0, 0, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:17`; [0, `multiseries/function`[EllipticCK,0,"CoeffProc",0,0,1](n), `multiseries/function`[EllipticCK,0,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[EllipticCK, infinity, "BasisVector", 1, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:25`; SERIES(scale,`multiseries/function`[EllipticCK,infinity,"CoeffProc",1,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCK/infinity/BasisVector/1/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCK, 1, "CoeffProc", 0, 0, 1]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:20`; xxloc1 := `multiseries/function`[EllipticCK,1,"CoeffProc",0,0,0](n); loc[0] := 0; loc[1] := -1/2; loc[2] := 7/16; for i1 from 3 to n do loc[i1] := 1/2*(-(2*i1-2)*op(i1-1,xxloc1)-(-3+6*i1)*op(i1,xxloc1)-4*i1*op(i1+1,xxloc1)-loc[i1-2]-loc[i1-1]-(-2*loc[i1-2]-3*loc[i1-1]+(loc[i1-2]+3*loc[i1-1])*i1)*i1)/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticCK, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:19`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[EllipticCK,0,"BasisVector",0,0,0,"MultiSeries"](expr,scale,var,order); loc2 := 2*ln(2); res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); loc1 := `multiseries/function`[EllipticCK,0,"BasisVector",0,0,1,"MultiSeries"](expr,scale,var,order); loc2 := -1; res2 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := `multiseries/add`([res1, res2]); subsop(9 = EllipticCK(op(9,expr)),res) end proc:
`multiseries/function`[EllipticCK, 0, "BasisVector", 0, 0, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:19`; SERIES(scale,`multiseries/function`[EllipticCK,0,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCK/0/BasisVector/0/0/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCK, -1, "CoeffProc", 0, 0, 1]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:28`; xxloc1 := `multiseries/function`[EllipticCK,-1,"CoeffProc",0,0,0](n); loc[0] := 0; loc[1] := 1/2; loc[2] := 7/16; for i1 from 3 to n do loc[i1] := 1/2*(-(2*i1-2)*op(i1-1,xxloc1)-(3-6*i1)*op(i1,xxloc1)-4*i1*op(i1+1,xxloc1)-loc[i1-2]+loc[i1-1]-(-2*loc[i1-2]+3*loc[i1-1]+(loc[i1-2]-3*loc[i1-1])*i1)*i1)/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticCK, infinity, "CoeffProc", 1, 0, 1]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:24`; xxloc1 := `multiseries/function`[EllipticCK,infinity,"CoeffProc",1,0,0](n); loc[0] := 0; loc[1] := 0; loc[2] := 1/4; for i1 from 3 to n do loc[i1] := (-(2-2*i1)*op(i1-1,xxloc1)-2*i1*op(i1+1,xxloc1)-(-1+(-i1+2)*i1)*loc[i1-2])/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticCK, infinity, "BasisVector", 1, 0, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:26`; SERIES(scale,`multiseries/function`[EllipticCK,infinity,"CoeffProc",1,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCK/infinity/BasisVector/1/0/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCK, infinity, "BasisVector", 1, 0, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:25`; [1, `multiseries/function`[EllipticCK,infinity,"CoeffProc",1,0,1](n), `multiseries/function`[EllipticCK,infinity,"CoeffProc",1,0,0](n)] end proc:
`multiseries/function`[EllipticCK, 1, "BasisVector", 0, 0, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:21`; [0, `multiseries/function`[EllipticCK,1,"CoeffProc",0,0,1](n), `multiseries/function`[EllipticCK,1,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[EllipticCK, 1, "BasisVector", 0, 0, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:22`; SERIES(scale,`multiseries/function`[EllipticCK,1,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCK/1/BasisVector/0/0/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCK, -1, "BasisVector", 0, 0, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:30`; [`multiseries/function`[EllipticCK,-1,"BasisVector",0,0,1,"MultiSeries",0](args), `multiseries/function`[EllipticCK,-1,"BasisVector",0,0,1,"MultiSeries",1](args)] end proc:
`multiseries/function`[EllipticCK, 1, "BasisVector", 0, 0, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:23`; [`multiseries/function`[EllipticCK,1,"BasisVector",0,0,1,"MultiSeries",0](args), `multiseries/function`[EllipticCK,1,"BasisVector",0,0,1,"MultiSeries",1](args)] end proc:
`multiseries/function`[EllipticCK, 1, "CoeffProc", 0, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:20`; loc[0] := 1; loc[1] := -1/2; loc[2] := 5/16; for i1 from 3 to n do loc[i1] := 1/2*(-loc[i1-2]-loc[i1-1]-(-2*loc[i1-2]-3*loc[i1-1]+(loc[i1-2]+3*loc[i1-1])*i1)*i1)/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticCK, 1, "BasisVector", 0, 0, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:22`; SERIES(scale,`multiseries/function`[EllipticCK,1,"CoeffProc",0,0,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCK/1/BasisVector/0/0/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCK, -1, "BasisVector", 0, 0, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:28`; [0, `multiseries/function`[EllipticCK,-1,"CoeffProc",0,0,1](n), `multiseries/function`[EllipticCK,-1,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[EllipticCK, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:16`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[EllipticCK,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,EllipticCK(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint/(1-_AnyFiniteOrdinaryPoint^2)*EllipticCK(_AnyFiniteOrdinaryPoint)-EllipticCE(_AnyFiniteOrdinaryPoint)/_AnyFiniteOrdinaryPoint/(1-_AnyFiniteOrdinaryPoint^2),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),EllipticCK(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[EllipticCK, 0, "BasisVector", 0, 0, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:18`; SERIES(scale,`multiseries/function`[EllipticCK,0,"CoeffProc",0,0,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCK/0/BasisVector/0/0/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCK, 0, "CoeffProc", 0, 0, 1]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:17`; xxloc1 := `multiseries/function`[EllipticCK,0,"CoeffProc",0,0,0](n); loc[0] := 0; loc[1] := 0; loc[2] := 1/4; for i1 from 3 to n do loc[i1] := -(-(2*i1-2)*op(i1-1,xxloc1)+2*i1*op(i1+1,xxloc1)-(1+(i1-2)*i1)*loc[i1-2])/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticCK, infinity, "BasisVector", 1, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:24`; [1, `multiseries/function`[EllipticCK,infinity,"CoeffProc",1,0,0](n)] end proc:
`multiseries/function`[EllipticCK, -1, "BasisVector", 0, 0, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:30`; SERIES(scale,`multiseries/function`[EllipticCK,-1,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCK/-1/BasisVector/0/0/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCK, -1, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:29`; [`multiseries/function`[EllipticCK,-1,"BasisVector",0,0,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[EllipticCK, infinity, "BasisVector", 1, 0, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:26`; [`multiseries/function`[EllipticCK,infinity,"BasisVector",1,0,1,"MultiSeries",0](args), `multiseries/function`[EllipticCK,infinity,"BasisVector",1,0,1,"MultiSeries",1](args)] end proc:
`multiseries/function`[EllipticCK, 0, "BasisVector", 0, 0, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:19`; [`multiseries/function`[EllipticCK,0,"BasisVector",0,0,1,"MultiSeries",0](args), `multiseries/function`[EllipticCK,0,"BasisVector",0,0,1,"MultiSeries",1](args)] end proc:
`multiseries/function`[EllipticCK, 1, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:21`; SERIES(scale,`multiseries/function`[EllipticCK,1,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCK/1/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCK, 0, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:18`; SERIES(scale,`multiseries/function`[EllipticCK,0,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCK/0/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCK, -1, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:29`; SERIES(scale,`multiseries/function`[EllipticCK,-1,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCK/-1/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCK, infinity]:=proc (expr, scale, var, order) local loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:27`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[EllipticCK,infinity,"BasisVector",1,0,0,"MultiSeries"](expr,scale,var,order); loc2 := 2*ln(2); res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],1,loc2,infinity); loc1 := `multiseries/function`[EllipticCK,infinity,"BasisVector",1,0,1,"MultiSeries"](expr,scale,var,order); loc2 := -1; res2 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],1,loc2,infinity); res := `multiseries/add`([res1, res2]); subsop(9 = EllipticCK(op(9,expr)),res) end proc:
`multiseries/function`[EllipticCK, infinity, "CoeffProc", 1, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:24`; loc[0] := 1; loc[1] := 0; loc[2] := 1/4; for i1 from 3 to n do loc[i1] := -(-1+(-i1+2)*i1)*loc[i1-2]/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticCK, -1, "CoeffProc", 0, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:27`; loc[0] := 1; loc[1] := 1/2; loc[2] := 5/16; for i1 from 3 to n do loc[i1] := 1/2*(-loc[i1-2]+loc[i1-1]-(-2*loc[i1-2]+3*loc[i1-1]+(loc[i1-2]-3*loc[i1-1])*i1)*i1)/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticCK, 1, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:21`; [0, `multiseries/function`[EllipticCK,1,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[EllipticCK, -1, "BasisVector", 0, 0, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:29`; SERIES(scale,`multiseries/function`[EllipticCK,-1,"CoeffProc",0,0,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCK/-1/BasisVector/0/0/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCK]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:31`; if expr = 0 then return `multiseries/Convert2SERIES`(EllipticCK(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = -1 or Testzero(lim+1) then res := `multiseries/function`[EllipticCK,-1](argseq) elif lim = 0 then res := `multiseries/function`[EllipticCK,0](argseq) elif lim = 1 or Testzero(lim-1) then res := `multiseries/function`[EllipticCK,1](argseq) elif lim = infinity then res := `multiseries/function`[EllipticCK,infinity](argseq) else res := eval(`multiseries/function`[EllipticCK,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = EllipticCK(op(9,expr)),res) end proc:
`multiseries/function`[EllipticCK, -1]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:30`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[EllipticCK,-1,"BasisVector",0,0,0,"MultiSeries"](expr,scale,var,order); loc2 := 1/2*Pi; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*EllipticCK(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,-1); res := res1; subsop(9 = EllipticCK(op(9,expr)),res) end proc:
`multiseries/function`[EllipticCK, infinity, "BasisVector", 1, 0, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:26`; SERIES(scale,`multiseries/function`[EllipticCK,infinity,"CoeffProc",1,0,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticCK/infinity/BasisVector/1/0/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticCK, 1]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:23`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[EllipticCK,1,"BasisVector",0,0,0,"MultiSeries"](expr,scale,var,order); loc2 := 1/2*Pi; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*EllipticCK(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,1); res := res1; subsop(9 = EllipticCK(op(9,expr)),res) end proc:
`multiseries/function`[EllipticCK, 0, "CoeffProc", 0, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:16`; loc[0] := 1; loc[1] := 0; loc[2] := 1/4; for i1 from 3 to n do loc[i1] := (1+(i1-2)*i1)*loc[i1-2]/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticCK, 1, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:22`; [`multiseries/function`[EllipticCK,1,"BasisVector",0,0,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[EllipticCK, -1, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:28`; [0, `multiseries/function`[EllipticCK,-1,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[EllipticCK, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:15`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, -1/2*(xarg*arg0+3*arg1*xarg^2-arg1)/xarg/(xarg^2-1)] else loc[0] := arg0; loc[1] := arg1; loc[2] := -1/2*(xarg*arg0+3*arg1*xarg^2-arg1)/xarg/(xarg^2-1); for i1 from 3 to n do loc[i1] := (-4*loc[i1-3]-(-1+3*xarg^2)*loc[i1-1]-7*xarg*loc[i1-2]-(-4*loc[i1-3]-9*xarg*loc[i1-2]+(2-6*xarg^2)*loc[i1-1]+(3*xarg*loc[i1-2]+loc[i1-3]+(-1+3*xarg^2)*loc[i1-1])*i1)*i1)/(xarg-xarg^3+(-xarg+xarg^3)*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[EllipticCK, 0, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:15:18`; [`multiseries/function`[EllipticCK,0,"BasisVector",0,0,0,"MultiSeries",0](args)] end proc:
