# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[GegenbauerC, -1, "BasisVector", -_a2+1/2, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:15`; SERIES(scale,`multiseries/function`[GegenbauerC,-1,"CoeffProc",-_a2+1/2](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`GegenbauerC/-1/BasisVector/-_a2+1/2/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[GegenbauerC, 1, "BasisVector", 0]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:06`; [0, `multiseries/function`[GegenbauerC,1,"CoeffProc"](n,0,a1,a2)] end proc:
`multiseries/function`[GegenbauerC, 1, "CoeffProc", 0]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:07`; `multiseries/function`[GegenbauerC,1,"CoeffProc"](n,0,a1,a2) end proc:
`multiseries/function`[GegenbauerC, infinity, "BasisVector", -_a1]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:10`; [-a1, `multiseries/function`[GegenbauerC,infinity,"CoeffProc"](n,-a1,a1,a2)] end proc:
`multiseries/function`[GegenbauerC, infinity, "BasisVector", -_a1, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:11`; SERIES(scale,`multiseries/function`[GegenbauerC,infinity,"CoeffProc",-_a1](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`GegenbauerC/infinity/BasisVector/-_a1/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[GegenbauerC, -1, "CoeffProc", -_a2+1/2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:14`; `multiseries/function`[GegenbauerC,-1,"CoeffProc"](n,-a2+1/2,a1,a2) end proc:
`multiseries/function`[GegenbauerC, -1, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:14`; SERIES(scale,`multiseries/function`[GegenbauerC,-1,"CoeffProc",0](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`GegenbauerC/-1/BasisVector/0/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[GegenbauerC, -1, "BasisVector", -_a2+1/2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:13`; [-a2+1/2, `multiseries/function`[GegenbauerC,-1,"CoeffProc"](n,-a2+1/2,a1,a2)] end proc:
`multiseries/function`[GegenbauerC, 1]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:09`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[GegenbauerC,1,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit(GAMMA(d1+2*d2)/GAMMA(2*d2)/GAMMA(d1+1),d1 = a1,'left'),d2 = a2,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*GegenbauerC(a1,a2,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,1); res := res1; subsop(9 = GegenbauerC(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[GegenbauerC, 1, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:08`; [`multiseries/function`[GegenbauerC,1,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[GegenbauerC]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:16`; if nops(exprlist) <> 3 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return `multiseries/Convert2SERIES`(GegenbauerC(paramseq,0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = -1 or Testzero(lim+1) then res := `multiseries/function`[GegenbauerC,-1](argseq) elif lim = 0 then res := `multiseries/function`[GegenbauerC,0](argseq) elif lim = 1 or Testzero(lim-1) then res := `multiseries/function`[GegenbauerC,1](argseq) elif lim = infinity then res := `multiseries/function`[GegenbauerC,infinity](argseq) else res := eval(`multiseries/function`[GegenbauerC,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = GegenbauerC(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[GegenbauerC, infinity, "BasisVector", -_a1, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:12`; [`multiseries/function`[GegenbauerC,infinity,"BasisVector",-_a1,"MultiSeries",0](args)] end proc:
`multiseries/function`[GegenbauerC, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, a1, a2, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:05`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] else loc[0] := arg0; loc[1] := arg1; for i1 from 2 to n do loc[i1] := (-(a1^2+2*a1*a2+4*a2-4)*loc[i1-2]-(-3*xarg+2*xarg*a2)*loc[i1-1]-((-2*a2+4)*loc[i1-2]+(-2*xarg*a2+5*xarg)*loc[i1-1]+(-loc[i1-2]-2*xarg*loc[i1-1])*i1)*i1)/(-1+xarg^2+(1-xarg^2)*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[GegenbauerC, -1, "CoeffProc"]:=proc (n, c, a1, a2) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:12`; if n = 0 then [normal(1)] else loc[0] := normal(1); for i1 to n do loc[i1] := normal(-(a1^2+2*a1*a2-2*a2*c+2*a2-1-c^2+2*c+(-2*c-2*a2+2-i1)*i1)*loc[i1-1]/(2*a2*c-c+2*c^2+(2*a2-1+4*c+2*i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[GegenbauerC, 1, "CoeffProc"]:=proc (n, c, a1, a2) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:06`; if n = 0 then [normal(1)] else loc[0] := normal(1); for i1 to n do loc[i1] := normal(-(a1^2+2*a1*a2-2*a2*c+2*a2-1-c^2+2*c+(-2*c-2*a2+2-i1)*i1)*loc[i1-1]/(-2*a2*c+c-2*c^2+(-2*a2+1-4*c-2*i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[GegenbauerC, 1, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:08`; SERIES(scale,`multiseries/function`[GegenbauerC,1,"CoeffProc",0](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`GegenbauerC/1/BasisVector/0/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[GegenbauerC, infinity, "CoeffProc", _a1+2*_a2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:10`; `multiseries/function`[GegenbauerC,infinity,"CoeffProc"](n,a1+2*a2,a1,a2) end proc:
`multiseries/function`[GegenbauerC, infinity, "BasisVector", _a1+2*_a2, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:11`; SERIES(scale,`multiseries/function`[GegenbauerC,infinity,"CoeffProc",_a1+2*_a2](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`GegenbauerC/infinity/BasisVector/_a1+2*_a2/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[GegenbauerC, -1]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:15`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[GegenbauerC,-1,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit(cos(Pi*(d1+d2))*sec(Pi*d2)*GAMMA(d1+2*d2)/GAMMA(d1+1)/GAMMA(2*d2),d1 = a1,'left'),d2 = a2,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*GegenbauerC(a1,a2,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,-1); res := res1; subsop(9 = GegenbauerC(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[GegenbauerC, infinity, "BasisVector", _a1+2*_a2, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:11`; [`multiseries/function`[GegenbauerC,infinity,"BasisVector",_a1+2*_a2,"MultiSeries",0](args)] end proc:
`multiseries/function`[GegenbauerC, infinity, "CoeffProc", -_a1]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:10`; `multiseries/function`[GegenbauerC,infinity,"CoeffProc"](n,-a1,a1,a2) end proc:
`multiseries/function`[GegenbauerC, -1, "BasisVector", 0]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:13`; [0, `multiseries/function`[GegenbauerC,-1,"CoeffProc"](n,0,a1,a2)] end proc:
`multiseries/function`[GegenbauerC, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:05`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[GegenbauerC,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,GegenbauerC(a1,a2,_AnyFiniteOrdinaryPoint),-a1*_AnyFiniteOrdinaryPoint/(1-_AnyFiniteOrdinaryPoint^2)*GegenbauerC(a1,a2,_AnyFiniteOrdinaryPoint)+(a1+2*a2-1)/(1-_AnyFiniteOrdinaryPoint^2)*GegenbauerC(a1-1,a2,_AnyFiniteOrdinaryPoint),a1,a2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),GegenbauerC(a1,a2,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[GegenbauerC, infinity]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:12`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := `multiseries/function`[GegenbauerC,infinity,"BasisVector",-_a1,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit(2^d1*GAMMA(d1+d2)/GAMMA(d2)/GAMMA(d1+1),d1 = a1,'left'),d2 = a2,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*GegenbauerC(a1,a2,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := `multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],-a1,loc2,infinity); res := res1; subsop(9 = GegenbauerC(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[GegenbauerC, 1, "BasisVector", -_a2+1/2, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:08`; SERIES(scale,`multiseries/function`[GegenbauerC,1,"CoeffProc",-_a2+1/2](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`GegenbauerC/1/BasisVector/-_a2+1/2/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[GegenbauerC, infinity, "CoeffProc"]:=proc (n, c, a1, a2) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:09`; if n = 0 then [normal(1)] elif n = 1 then [normal(1), normal(0)] else loc[0] := normal(1); loc[1] := normal(0); for i1 from 2 to n do loc[i1] := normal(-(-3*c+2+c^2+(-3+2*c+i1)*i1)*loc[i1-2]/(a1^2+2*a1*a2+2*a2*c-c^2+(2*a2-2*c-i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[GegenbauerC, -1, "BasisVector", -_a2+1/2, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:15`; [`multiseries/function`[GegenbauerC,-1,"BasisVector",-_a2+1/2,"MultiSeries",0](args)] end proc:
`multiseries/function`[GegenbauerC, -1, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:14`; [`multiseries/function`[GegenbauerC,-1,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[GegenbauerC, 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:05`; `multiseries/compose`(SERIES(scale,map(normal,`multiseries/function`[GegenbauerC,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,2^a1*Pi^(1/2)*GAMMA(a2+1/2*a1)/GAMMA(a2)/GAMMA(a1+1)/GAMMA(1/2-1/2*a1),-2^(a1+1)*Pi^(1/2)*GAMMA(a2+1/2*a1+1/2)/GAMMA(a1+1)/GAMMA(a2)/GAMMA(-1/2*a1),a1,a2,0)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),GegenbauerC(a1,a2,eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[GegenbauerC, -1, "CoeffProc", 0]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:13`; `multiseries/function`[GegenbauerC,-1,"CoeffProc"](n,0,a1,a2) end proc:
`multiseries/function`[GegenbauerC, 1, "BasisVector", -_a2+1/2, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:08`; [`multiseries/function`[GegenbauerC,1,"BasisVector",-_a2+1/2,"MultiSeries",0](args)] end proc:
`multiseries/function`[GegenbauerC, 1, "BasisVector", -_a2+1/2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:07`; [-a2+1/2, `multiseries/function`[GegenbauerC,1,"CoeffProc"](n,-a2+1/2,a1,a2)] end proc:
`multiseries/function`[GegenbauerC, 1, "CoeffProc", -_a2+1/2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:07`; `multiseries/function`[GegenbauerC,1,"CoeffProc"](n,-a2+1/2,a1,a2) end proc:
`multiseries/function`[GegenbauerC, infinity, "BasisVector", _a1+2*_a2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 10/26/2004 @ 23:18:10`; [a1+2*a2, `multiseries/function`[GegenbauerC,infinity,"CoeffProc"](n,a1+2*a2,a1,a2)] end proc:
