# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:34:57`; [0, MultiSeries:-`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[AiryBi, infinity, -1/3*Pi .. 1/3*Pi]:=proc (expr, scale, var, order, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:34:58`; res := `multiseries/add`([`multiseries/mul`([`multiseries/compose`(`multiseries/pow`(SERIES(scale,[1],0,integer,[1],infinity,integer,eval(scale['variable'],1),eval(scale['variable'],1)),1/2,scale,var,order),`multiseries/MulDoit`(`multiseries/pow`(expr,1/2,scale,var,order),I),scale,var,order), MultiSeries:-`multiseries/function`[exp](`multiseries/MulDoit`(`multiseries/pow`(`multiseries/MulDoit`(`multiseries/pow`(expr,1/2,scale,var,order),I),-3,scale,var,order),-2/3),scale,var,order), `multiseries/compose`(MultiSeries:-`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`](SERIES(scale,[1],0,integer,[1],infinity,integer,eval(scale['variable'],1),eval(scale['variable'],1)),scale,[eval(scale['variable'],1)],order),`multiseries/MulDoit`(`multiseries/pow`(expr,1/2,scale,var,order),I),scale,var,order)])]) end proc:
`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:34:57`; SERIES(scale,MultiSeries:-`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[AiryBi, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:34:56`; `multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[AiryAi,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,AiryBi(_AnyFiniteOrdinaryPoint),AiryBi(1,_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),AiryBi(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:34:57`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := -I/Pi^(1/2); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:34:57`; MultiSeries:-`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:34:56`; `multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`AiryAi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(_AnyFiniteOrdinaryPoint),diff(`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[AiryBi, 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:34:56`; `multiseries/compose`(SERIES(scale,MultiSeries:-`multiseries/function`[AiryAi,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,1/3*3^(5/6)/GAMMA(2/3),1/2*3^(2/3)/Pi*GAMMA(2/3),0),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),AiryBi(eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:34:57`; if n = 0 then [1] elif n = 1 then [1, 0] elif n = 2 then [1, 0, 0] else loc[0] := 1; loc[1] := 0; loc[2] := 0; for i1 from 3 to n do loc[i1] := -(5-12*c+4*c^2+(8*c-12+4*i1)*i1)*loc[i1-3]/(16*c+16*i1) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:34:58`; if expr = 0 then return `multiseries/Convert2SERIES`(`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:34:57`; [MultiSeries:-`multiseries/function`[`AiryBi/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[AiryBi]:=proc (expr, scale, var, order) local k, f, x, xx; option `Copyright (c) 2002-2004 by the Algorithms Project, INRIA`; if not type(expr,list) then `multiseries/function/AiryBiunivar`(args) else k := expr[1]; if k = 0 then procname(expr[2],args[2 .. -1]) else k := `multiseries/Series2Expr`(k) end if; if not type(k,nonnegint) then error "Cannot expand AiryBi with first argument %1", k end if; if k = 1 then `multiseries/function`[`D(AiryBi)`](expr[2],args[2 .. -1]) else f := collect(eval(AiryBi(k,x)),AiryBi); xx := expr[2]; `multiseries/run`(subs(x = xx,coeff(f,AiryBi(x)))*`multiseries/function`[AiryBi](xx,args[2 .. -1])+coeff(f,AiryBi(1,x))*`multiseries/function`[`D(AiryBi)`](xx,args[2 .. -1]),args[2 .. -1]) end if end if end proc:
