# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:33`; [MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:31`; SERIES(scale,MultiSeries:-`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Chi, 0, "CoeffProc", 1, 1, 1]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:27`; loc[0] := 1; loc[1] := 0; loc[2] := 0; loc[3] := 0; for i1 from 4 to n do loc[i1] := -(-i1+2)*loc[i1-2]/i1^2/(i1-1) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[Chi]:=proc (expr, scale, var, order) local lim, lim2, asymptdir, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:42`; if expr = 0 then return `multiseries/Convert2SERIES`(Chi(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then if has(lim,exp) then asymptdir := op(select(type,lim,specfunc(anything,exp))) elif 1 < nops(lim) then asymptdir := argument(subs(infinity = 1,lim)) else asymptdir := 0 end if; lim := infinity else asymptdir := argument(lim) end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := `multiseries/function`[Chi,0](argseq) elif lim = infinity then if evalb(signum(1/2*Pi-asymptdir) <> 1) and evalb(signum(Pi-asymptdir) <> -1) then res := `multiseries/function`[Chi,infinity,1/2*Pi .. Pi](argseq,[op(1,[argseq]), scale, var, order]) elif evalb(signum(-1/2*Pi-asymptdir) <> 1) and evalb(signum(1/2*Pi-asymptdir) <> -1) then res := `multiseries/function`[Chi,infinity,-1/2*Pi .. 1/2*Pi](argseq,[op(1,[argseq]), scale, var, order]) elif evalb(signum(-Pi-asymptdir) <> 1) and evalb(signum(-1/2*Pi-asymptdir) <> -1) then res := `multiseries/function`[Chi,infinity,-Pi .. -1/2*Pi](argseq,[op(1,[argseq]), scale, var, order]) end if else res := eval(`multiseries/function`[Chi,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = Chi(op(9,expr)),res) end proc:
`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:33`; SERIES(scale,MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Chi/infinity/aux/1/-Pi .. -1/2*Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:35`; MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-Pi .. -1/2*Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[Chi, 0, "CoeffProc", 1, 1, 2]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:27`; xxloc1 := MultiSeries:-`multiseries/function`[Chi,0,"CoeffProc",1,1,1](n); loc[0] := 4; loc[1] := 0; loc[2] := 1/2; loc[3] := 0; for i1 from 4 to n do loc[i1] := (2*op(i1-1,xxloc1)-2*(-i1+i1^2+i1*(2*i1-1))*op(i1+1,xxloc1)-(-i1+2)*loc[i1-2])/i1^2/(i1-1) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[`Chi/infinity/aux/2/-Pi .. -1/2*Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:37`; MultiSeries:-`multiseries/function`[`Chi/infinity/aux/2/-Pi .. -1/2*Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:33`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := -1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[Chi, 0, "CoeffProc", 1, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:26`; loc[0] := 4; loc[1] := 0; loc[2] := 2/9; for i1 from 3 to n do loc[i1] := -(1-i1)*loc[i1-2]/(1+(i1+2)*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[`Chi/infinity/aux/2/-Pi .. -1/2*Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:37`; [0, MultiSeries:-`multiseries/function`[`Chi/infinity/aux/2/-Pi .. -1/2*Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:32`; if n = 0 then [1] elif n = 1 then [1, -3/2*c-1] else loc[0] := 1; loc[1] := -3/2*c-1; for i1 from 2 to n do loc[i1] := 1/2*(-c^2+2*c-1)*loc[i1-2]+1/2*(1-3*c)*loc[i1-1]+1/2*((-2*c+2)*loc[i1-2]-3*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[Chi, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:29`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[Chi,0,"BasisVector",0,0,0,"MultiSeries"](expr,scale,var,order); loc2 := gamma-2; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); loc1 := MultiSeries:-`multiseries/function`[Chi,0,"BasisVector",0,0,1,"MultiSeries"](expr,scale,var,order); loc2 := 1/2; res2 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := `multiseries/add`([res1, res2]); subsop(9 = Chi(op(9,expr)),res) end proc:
`multiseries/function`[Chi, infinity, 1/2*Pi .. Pi]:=proc (expr, scale, var, order, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:42`; res := `multiseries/add`([`multiseries/Convert2SERIES`(I*Pi,scale,var,false), `multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](`multiseries/MulDoit`(`multiseries/pow`(expr,-1,scale,var,order),1),scale,var,order), MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/1/2*Pi .. Pi`](op(arglist))]), `multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](`multiseries/MulDoit`(`multiseries/pow`(expr,-1,scale,var,order),-1),scale,var,order), MultiSeries:-`multiseries/function`[`Chi/infinity/aux/2/1/2*Pi .. Pi`](op(arglist))])]) end proc:
`multiseries/function`[`Chi/infinity/aux/1/1/2*Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:38`; `multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Chi/infinity/aux/1/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint),diff(`Chi/infinity/aux/1/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Chi/infinity/aux/1/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Chi/infinity/aux/1/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`Chi/infinity/aux/2/1/2*Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:41`; MultiSeries:-`multiseries/function`[`Chi/infinity/aux/2/1/2*Pi .. Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[Chi, infinity, -1/2*Pi .. 1/2*Pi]:=proc (expr, scale, var, order, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:34`; res := `multiseries/add`([`multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](`multiseries/MulDoit`(`multiseries/pow`(expr,-1,scale,var,order),1),scale,var,order), MultiSeries:-`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`](op(arglist))]), `multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](`multiseries/MulDoit`(`multiseries/pow`(expr,-1,scale,var,order),-1),scale,var,order), MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`](op(arglist))])]) end proc:
`multiseries/function`[`Chi/infinity/aux/1/-Pi .. -1/2*Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:34`; `multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Chi/infinity/aux/1/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint),diff(`Chi/infinity/aux/1/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Chi/infinity/aux/1/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Chi/infinity/aux/1/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`Chi/infinity/aux/1/1/2*Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:39`; SERIES(scale,MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/1/2*Pi .. Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Chi/infinity/aux/1/1/2*Pi .. Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Chi, 0, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:27`; [0, MultiSeries:-`multiseries/function`[Chi,0,"CoeffProc",1,1,1](n), MultiSeries:-`multiseries/function`[Chi,0,"CoeffProc",1,1,0](n)] end proc:
`multiseries/function`[Chi, 0, "BasisVector", 0, 1, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:29`; SERIES(scale,MultiSeries:-`multiseries/function`[Chi,0,"CoeffProc",1,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Chi/0/BasisVector/0/1/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Chi, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, arg2, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:25`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, 1/4*arg2] else loc[0] := arg0; loc[1] := arg1; loc[2] := 1/4*arg2; for i1 from 3 to n do loc[i1] := (-3*loc[i1-3]-2*xarg*loc[i1-2]+2*loc[i1-1]-(-loc[i1-3]-xarg*loc[i1-2]+5*loc[i1-1]+(-4*loc[i1-1]+loc[i1-1]*i1)*i1)*i1)/(2*xarg+(-3*xarg+xarg*i1)*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`Chi/infinity/aux/2/1/2*Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:42`; [MultiSeries:-`multiseries/function`[`Chi/infinity/aux/2/1/2*Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`Chi/infinity/aux/2/-Pi .. -1/2*Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:38`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Chi/infinity/aux/2/-Pi .. -1/2*Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := 1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Chi/infinity/aux/2/-Pi .. -1/2*Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Chi/infinity/aux/2/-Pi .. -1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Chi/infinity/aux/1/1/2*Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:40`; [MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/1/2*Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, arg2, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:30`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, 1/4*arg2] elif n = 3 then [arg0, arg1, 1/4*arg2, -1/12*(4*arg0*xarg-4*arg0+20*arg1*xarg^2-16*arg1*xarg+4*arg1+7*arg2*xarg^3-3*arg2*xarg^2)/xarg^4] else loc[0] := arg0; loc[1] := arg1; loc[2] := 1/4*arg2; loc[3] := -1/12*(4*arg0*xarg-4*arg0+20*arg1*xarg^2-16*arg1*xarg+4*arg1+7*arg2*xarg^3-3*arg2*xarg^2)/xarg^4; for i1 from 4 to n do loc[i1] := (9*loc[i1-4]-(-5*xarg^3-3*xarg^2)*loc[i1-1]-(-19*xarg^2-10*xarg-2)*loc[i1-2]-(-23*xarg-7)*loc[i1-3]-((19*xarg+3)*loc[i1-3]+6*loc[i1-4]+(9*xarg^3+3*xarg^2)*loc[i1-1]+(6*xarg+21*xarg^2)*loc[i1-2]+(-6*xarg^2*loc[i1-2]-4*xarg*loc[i1-3]-loc[i1-4]-4*xarg^3*loc[i1-1])*i1)*i1)/(xarg^4-xarg^4*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[Chi, 0, "BasisVector", 0, 0, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:27`; [0, MultiSeries:-`multiseries/function`[Chi,0,"CoeffProc",1,1,2](n), 2*MultiSeries:-`multiseries/function`[Chi,0,"CoeffProc",1,1,1](n), MultiSeries:-`multiseries/function`[Chi,0,"CoeffProc",1,1,0](n)] end proc:
`multiseries/function`[`Chi/infinity/aux/2/1/2*Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:41`; SERIES(scale,MultiSeries:-`multiseries/function`[`Chi/infinity/aux/2/1/2*Pi .. Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Chi/infinity/aux/2/1/2*Pi .. Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Chi, infinity, -Pi .. -1/2*Pi]:=proc (expr, scale, var, order, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:38`; res := `multiseries/add`([`multiseries/Convert2SERIES`(I*Pi,scale,var,false), `multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](`multiseries/MulDoit`(`multiseries/pow`(expr,-1,scale,var,order),-1),scale,var,order), MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-Pi .. -1/2*Pi`](op(arglist))]), `multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](`multiseries/MulDoit`(`multiseries/pow`(expr,-1,scale,var,order),1),scale,var,order), MultiSeries:-`multiseries/function`[`Chi/infinity/aux/2/-Pi .. -1/2*Pi`](op(arglist))])]) end proc:
`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:31`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := 1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Chi/infinity/aux/2/1/2*Pi .. Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:41`; [0, MultiSeries:-`multiseries/function`[`Chi/infinity/aux/2/1/2*Pi .. Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[Chi, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:25`; `multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[Chi,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,Chi(_AnyFiniteOrdinaryPoint),cosh(_AnyFiniteOrdinaryPoint)/_AnyFiniteOrdinaryPoint,2*sinh(_AnyFiniteOrdinaryPoint)/_AnyFiniteOrdinaryPoint-2*cosh(_AnyFiniteOrdinaryPoint)/_AnyFiniteOrdinaryPoint^2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),Chi(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`Chi/infinity/aux/2/1/2*Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:41`; if n = 0 then [1] elif n = 1 then [1, -3/2*c-1] else loc[0] := 1; loc[1] := -3/2*c-1; for i1 from 2 to n do loc[i1] := 1/2*(-c^2+2*c-1)*loc[i1-2]+1/2*(1-3*c)*loc[i1-1]+1/2*((-2*c+2)*loc[i1-2]-3*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:31`; [MultiSeries:-`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:31`; MultiSeries:-`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[`Chi/infinity/aux/2/-Pi .. -1/2*Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:36`; if n = 0 then [1] elif n = 1 then [1, 3/2*c+1] else loc[0] := 1; loc[1] := 3/2*c+1; for i1 from 2 to n do loc[i1] := 1/2*(-c^2+2*c-1)*loc[i1-2]+1/2*(-1+3*c)*loc[i1-1]+1/2*((-2*c+2)*loc[i1-2]+3*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:30`; if n = 0 then [1] elif n = 1 then [1, 3/2*c+1] else loc[0] := 1; loc[1] := 3/2*c+1; for i1 from 2 to n do loc[i1] := 1/2*(-c^2+2*c-1)*loc[i1-2]+1/2*(-1+3*c)*loc[i1-1]+1/2*((-2*c+2)*loc[i1-2]+3*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:33`; if expr = 0 then return `multiseries/Convert2SERIES`(`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Chi/infinity/aux/2/-Pi .. -1/2*Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:37`; SERIES(scale,MultiSeries:-`multiseries/function`[`Chi/infinity/aux/2/-Pi .. -1/2*Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Chi/infinity/aux/2/-Pi .. -1/2*Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Chi/infinity/aux/1/1/2*Pi .. Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:39`; [0, MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/1/2*Pi .. Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`Chi/infinity/aux/1/-Pi .. -1/2*Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:35`; [MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-Pi .. -1/2*Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`Chi/infinity/aux/1/-Pi .. -1/2*Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:34`; if n = 0 then [1] elif n = 1 then [1, -3/2*c-1] else loc[0] := 1; loc[1] := -3/2*c-1; for i1 from 2 to n do loc[i1] := 1/2*(-c^2+2*c-1)*loc[i1-2]+1/2*(1-3*c)*loc[i1-1]+1/2*((-2*c+2)*loc[i1-2]-3*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[Chi, 0, "BasisVector", 0, 1, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:27`; [1, MultiSeries:-`multiseries/function`[Chi,0,"CoeffProc",1,0,0](n)] end proc:
`multiseries/function`[`Chi/infinity/aux/1/-Pi .. -1/2*Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:36`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-Pi .. -1/2*Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := -1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Chi/infinity/aux/1/-Pi .. -1/2*Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Chi/infinity/aux/1/-Pi .. -1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:30`; `multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint),diff(`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, arg2, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:32`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, 1/4*arg2] elif n = 3 then [arg0, arg1, 1/4*arg2, -1/12*(4*arg0*xarg+4*arg0+20*arg1*xarg^2+16*arg1*xarg+4*arg1+7*arg2*xarg^3+3*arg2*xarg^2)/xarg^4] else loc[0] := arg0; loc[1] := arg1; loc[2] := 1/4*arg2; loc[3] := -1/12*(4*arg0*xarg+4*arg0+20*arg1*xarg^2+16*arg1*xarg+4*arg1+7*arg2*xarg^3+3*arg2*xarg^2)/xarg^4; for i1 from 4 to n do loc[i1] := (9*loc[i1-4]-(-5*xarg^3+3*xarg^2)*loc[i1-1]-(-19*xarg^2+10*xarg-2)*loc[i1-2]-(-23*xarg+7)*loc[i1-3]-((19*xarg-3)*loc[i1-3]+6*loc[i1-4]+(9*xarg^3-3*xarg^2)*loc[i1-1]+(-6*xarg+21*xarg^2)*loc[i1-2]+(-6*xarg^2*loc[i1-2]-4*xarg*loc[i1-3]-loc[i1-4]-4*xarg^3*loc[i1-1])*i1)*i1)/(xarg^4-xarg^4*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[Chi, 0, "BasisVector", 0, 0, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:28`; SERIES(scale,2*MultiSeries:-`multiseries/function`[Chi,0,"CoeffProc",1,1,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Chi/0/BasisVector/0/0/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Chi/infinity/aux/2/1/2*Pi .. Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:42`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Chi/infinity/aux/2/1/2*Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := -1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Chi/infinity/aux/2/1/2*Pi .. Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Chi/infinity/aux/2/1/2*Pi .. Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Chi/infinity/aux/1/1/2*Pi .. Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:40`; ASSERT(`multiseries/limit`(expr,scale,var) = 0 or Testzero(`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/1/2*Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := 1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Chi/infinity/aux/1/1/2*Pi .. Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Chi/infinity/aux/1/1/2*Pi .. Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Chi/infinity/aux/1/-Pi .. -1/2*Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:35`; [0, MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-Pi .. -1/2*Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`Chi/infinity/aux/1/-Pi .. -1/2*Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:36`; if expr = 0 then return `multiseries/Convert2SERIES`(`Chi/infinity/aux/1/-Pi .. -1/2*Pi`(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-Pi .. -1/2*Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-Pi .. -1/2*Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Chi/infinity/aux/1/-Pi .. -1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Chi/infinity/aux/2/-Pi .. -1/2*Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:38`; if expr = 0 then return `multiseries/Convert2SERIES`(`Chi/infinity/aux/2/-Pi .. -1/2*Pi`(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Chi/infinity/aux/2/-Pi .. -1/2*Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Chi/infinity/aux/2/-Pi .. -1/2*Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Chi/infinity/aux/2/-Pi .. -1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[Chi, 0, "BasisVector", 0, 1, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:29`; [MultiSeries:-`multiseries/function`[Chi,0,"BasisVector",0,1,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:31`; if expr = 0 then return `multiseries/Convert2SERIES`(`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Chi/infinity/aux/2/-Pi .. -1/2*Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:36`; `multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Chi/infinity/aux/2/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint),diff(`Chi/infinity/aux/2/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Chi/infinity/aux/2/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Chi/infinity/aux/2/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[Chi, 0, "CoeffProc", 1, 1, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:27`; [`$`(0,n+1)] end proc:
`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:32`; `multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint),diff(`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:33`; MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[Chi, 0, "BasisVector", 0, 0, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:28`; SERIES(scale,MultiSeries:-`multiseries/function`[Chi,0,"CoeffProc",1,1,2](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Chi/0/BasisVector/0/0/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Chi, 0, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:28`; SERIES(scale,MultiSeries:-`multiseries/function`[Chi,0,"CoeffProc",1,1,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Chi/0/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Chi, 0, "BasisVector", 0, 0, 1, "MultiSeries", 2]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:29`; SERIES(scale,MultiSeries:-`multiseries/function`[Chi,0,"CoeffProc",1,1,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Chi/0/BasisVector/0/0/1/MultiSeries/2`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Chi/infinity/aux/2/1/2*Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:40`; `multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Chi/infinity/aux/2/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint),diff(`Chi/infinity/aux/2/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Chi/infinity/aux/2/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Chi/infinity/aux/2/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[Chi, 0, "BasisVector", 0, 0, 0, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:28`; SERIES(scale,MultiSeries:-`multiseries/function`[Chi,0,"CoeffProc",1,1,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Chi/0/BasisVector/0/0/0/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Chi/infinity/aux/1/1/2*Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:39`; if n = 0 then [1] elif n = 1 then [1, 3/2*c+1] else loc[0] := 1; loc[1] := 3/2*c+1; for i1 from 2 to n do loc[i1] := 1/2*(-c^2+2*c-1)*loc[i1-2]+1/2*(-1+3*c)*loc[i1-1]+1/2*((-2*c+2)*loc[i1-2]+3*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`Chi/infinity/aux/1/1/2*Pi .. Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:40`; if expr = 0 then return `multiseries/Convert2SERIES`(`Chi/infinity/aux/1/1/2*Pi .. Pi`(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/1/2*Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/1/2*Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Chi/infinity/aux/1/1/2*Pi .. Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Chi/infinity/aux/2/-Pi .. -1/2*Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:38`; [MultiSeries:-`multiseries/function`[`Chi/infinity/aux/2/-Pi .. -1/2*Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:33`; [0, MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`Chi/infinity/aux/2/1/2*Pi .. Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:42`; if expr = 0 then return `multiseries/Convert2SERIES`(`Chi/infinity/aux/2/1/2*Pi .. Pi`(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Chi/infinity/aux/2/1/2*Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Chi/infinity/aux/2/1/2*Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Chi/infinity/aux/2/1/2*Pi .. Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Chi/infinity/aux/1/-Pi .. -1/2*Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:35`; SERIES(scale,MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/-Pi .. -1/2*Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Chi/infinity/aux/1/-Pi .. -1/2*Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Chi, 0, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:28`; [MultiSeries:-`multiseries/function`[Chi,0,"BasisVector",0,0,0,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[Chi,0,"BasisVector",0,0,0,"MultiSeries",1](args)] end proc:
`multiseries/function`[`Chi/infinity/aux/1/1/2*Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:39`; MultiSeries:-`multiseries/function`[`Chi/infinity/aux/1/1/2*Pi .. Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[Chi, 0, "BasisVector", 0, 0, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:29`; [MultiSeries:-`multiseries/function`[Chi,0,"BasisVector",0,0,1,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[Chi,0,"BasisVector",0,0,1,"MultiSeries",1](args), MultiSeries:-`multiseries/function`[Chi,0,"BasisVector",0,0,1,"MultiSeries",2](args)] end proc:
`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:36:30`; [0, MultiSeries:-`multiseries/function`[`Chi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,0,"CoeffProc"](n,0)] end proc:
