# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[`CylinderU/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:18`; [0, MultiSeries:-`multiseries/function`[`CylinderU/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0,a1)] end proc:
`multiseries/function`[`CylinderU/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c, a1) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:17`; if n = 0 then [normal(1)] elif n = 1 then [normal(1), normal(0)] else loc[0] := normal(1); loc[1] := normal(0); for i1 from 2 to n do loc[i1] := normal(-(4*a1^2-8*a1+3+8*a1*c-8*c+4*c^2+(8*a1+8*c-8+4*i1)*i1)*loc[i1-2]/(4*c+4*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`CylinderU/infinity/aux/0/-Pi .. Pi`]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:19`; if nops(exprlist) <> 2 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`CylinderU/infinity/aux/0/-Pi .. Pi`(paramseq,0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`CylinderU/infinity/aux/0/-Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`CylinderU/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `CylinderU/infinity/aux/0/-Pi .. Pi`(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[`CylinderU/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:18`; MultiSeries:-`multiseries/function`[`CylinderU/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0,a1) end proc:
`multiseries/function`[`CylinderU/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:17`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`CylinderU/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`CylinderU/infinity/aux/0/-Pi .. Pi`(a1,_AnyFiniteOrdinaryPoint),D[2](`CylinderU/infinity/aux/0/-Pi .. Pi`)(a1,_AnyFiniteOrdinaryPoint),a1,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`CylinderU/infinity/aux/0/-Pi .. Pi`(a1,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`CylinderU/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, a1, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:17`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, -1/8/xarg^3*(4*arg0*a1^2*xarg+8*arg0*a1*xarg+3*arg0*xarg+8*arg1*a1*xarg^2+12*arg1*xarg^2+4*arg1)] else loc[0] := arg0; loc[1] := arg1; loc[2] := -1/8/xarg^3*(4*arg0*a1^2*xarg+8*arg0*a1*xarg+3*arg0*xarg+8*arg1*a1*xarg^2+12*arg1*xarg^2+4*arg1); for i1 from 3 to n do loc[i1] := (-(4*a1^2-16*a1+15)*loc[i1-3]-(-8*a1*xarg^2+12*xarg^2-4)*loc[i1-1]-(4*a1^2*xarg-24*a1*xarg+27*xarg)*loc[i1-2]-((8*a1-16)*loc[i1-3]+(16*a1*xarg-36*xarg)*loc[i1-2]+(8*a1*xarg^2+4-24*xarg^2)*loc[i1-1]+(12*xarg*loc[i1-2]+4*loc[i1-3]+12*xarg^2*loc[i1-1])*i1)*i1)/(-4*xarg^3+4*xarg^3*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[CylinderU, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, a1, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:16`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, 1/2*a1*arg0+1/8*arg0*xarg^2] elif n = 3 then [arg0, arg1, 1/2*a1*arg0+1/8*arg0*xarg^2, 1/12*arg0*xarg+1/6*arg1*a1+1/24*arg1*xarg^2] else loc[0] := arg0; loc[1] := arg1; loc[2] := 1/2*a1*arg0+1/8*arg0*xarg^2; loc[3] := 1/12*arg0*xarg+1/6*arg1*a1+1/24*arg1*xarg^2; for i1 from 4 to n do loc[i1] := (loc[i1-4]+2*xarg*loc[i1-3]-(-4*a1-xarg^2)*loc[i1-2])/i1/(4*i1-4) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`CylinderU/infinity/aux/0/-Pi .. Pi`, 0]:=proc (expr, scale, var, order, a1) local d1, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:19`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`CylinderU/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1); loc2 := limit(1,d1 = a1,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`CylinderU/infinity/aux/0/-Pi .. Pi`(a1,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `CylinderU/infinity/aux/0/-Pi .. Pi`(a1,op(9,expr)),res) end proc:
`multiseries/function`[CylinderU, 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:16`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[CylinderU,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,2^(-3/4-1/2*a1)*(cos(1/2*a1*Pi)-sin(1/2*a1*Pi))/Pi^(1/2)*GAMMA(1/4-1/2*a1),-2^(-1/4-1/2*a1)*(sin(1/2*a1*Pi)+cos(1/2*a1*Pi))/Pi^(1/2)*GAMMA(3/4-1/2*a1),a1,0)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),CylinderU(a1,eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[CylinderU, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:16`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[CylinderU,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,CylinderU(a1,_AnyFiniteOrdinaryPoint),-1/2*_AnyFiniteOrdinaryPoint*CylinderU(a1,_AnyFiniteOrdinaryPoint)-(a1+1/2)*CylinderU(a1+1,_AnyFiniteOrdinaryPoint),a1,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),CylinderU(a1,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`CylinderU/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:18`; SERIES(scale,MultiSeries:-`multiseries/function`[`CylinderU/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc",0](order,a1),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`CylinderU/infinity/aux/0/-Pi .. Pi/0/BasisVector/0/MultiSeries/0`(a1,eval(scale['variable'],1))) end proc:
`multiseries/function`[CylinderU, infinity, -Pi .. Pi]:=proc (expr, scale, var, order, a1, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:19`; res := MultiSeries:-`multiseries/add`([MultiSeries:-`multiseries/mul`([MultiSeries:-`multiseries/pow`(expr,a1+1/2,scale,var,order), MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-2,scale,var,order),-1/4),scale,var,order), MultiSeries:-`multiseries/function`[`CylinderU/infinity/aux/0/-Pi .. Pi`](op(arglist))])]) end proc:
`multiseries/function`[`CylinderU/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:18`; [MultiSeries:-`multiseries/function`[`CylinderU/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[CylinderU]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:19`; if nops(exprlist) <> 2 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return `multiseries/Convert2SERIES`(CylinderU(paramseq,0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := `multiseries/function`[CylinderU,0](argseq) elif lim = infinity then res := `multiseries/function`[CylinderU,infinity,-Pi .. Pi](argseq,[[op(1 .. -2,exprlist), op(1,[argseq])], scale, var, order]) else res := eval(`multiseries/function`[CylinderU,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = CylinderU(paramseq,op(9,expr)),res) end proc:
