# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:49`; if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`D(AiryBi)`, 0, "CoeffProc", 2, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:44`; loc[0] := 24; loc[1] := 0; loc[2] := 0; loc[3] := 8/5; for i1 from 4 to n do loc[i1] := loc[i1-3]/i1/(i1+2) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[`D(AiryBi)`]:=proc (expr, scale, var, order) local lim, lim2, asymptdir, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:49`; if expr = 0 then return `multiseries/Convert2SERIES`(`D(AiryBi)`(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then if has(lim,exp) then asymptdir := op(select(type,lim,specfunc(anything,exp))) elif 1 < nops(lim) then asymptdir := argument(subs(infinity = 1,lim)) else asymptdir := 0 end if; lim := infinity else asymptdir := argument(lim) end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := `multiseries/function`[`D(AiryBi)`,0](argseq) elif lim = infinity then if evalb(signum(-1/3*Pi-asymptdir) <> 1) and evalb(signum(1/3*Pi-asymptdir) <> -1) then res := `multiseries/function`[`D(AiryBi)`,infinity,-1/3*Pi .. 1/3*Pi](argseq,[op(1,[argseq]), scale, var, order]) else error "unable to compute series" end if else res := eval(`multiseries/function`[`D(AiryBi)`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `D(AiryBi)`(op(9,expr)),res) end proc:
`multiseries/function`[`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:48`; MultiSeries:-`multiseries/function`[`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[`D(AiryBi)`, 0, "BasisVector", 0, 2, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:46`; SERIES(scale,MultiSeries:-`multiseries/function`[`D(AiryBi)`,0,"CoeffProc",2,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`D(AiryBi)/0/BasisVector/0/2/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`D(AiryBi)`, 0, "BasisVector", 0, 2, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:45`; [2, MultiSeries:-`multiseries/function`[`D(AiryBi)`,0,"CoeffProc",2,0,0](n)] end proc:
`multiseries/function`[`D(AiryBi)`, 0, "CoeffProc", 2, 2, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:44`; [`$`(0,n+1)] end proc:
`multiseries/function`[`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:47`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`D(AiryAi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(_AnyFiniteOrdinaryPoint),diff(`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:48`; SERIES(scale,MultiSeries:-`multiseries/function`[`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:48`; [0, MultiSeries:-`multiseries/function`[`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`D(AiryBi)`, 0, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:46`; SERIES(scale,MultiSeries:-`multiseries/function`[`D(AiryBi)`,0,"CoeffProc",2,2,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`D(AiryBi)/0/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`D(AiryBi)`, 0, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:45`; [0, MultiSeries:-`multiseries/function`[`D(AiryBi)`,0,"CoeffProc",2,2,1](n), MultiSeries:-`multiseries/function`[`D(AiryBi)`,0,"CoeffProc",2,2,0](n)] end proc:
`multiseries/function`[`D(AiryBi)`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:47`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`D(AiryBi)`,0,"BasisVector",0,0,0,"MultiSeries"](expr,scale,var,order); loc2 := -1/4*3^(2/3)/Pi*GAMMA(2/3); res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); loc1 := MultiSeries:-`multiseries/function`[`D(AiryBi)`,0,"BasisVector",0,2,0,"MultiSeries"](expr,scale,var,order); loc2 := 1/144*3^(5/6)/GAMMA(2/3); res2 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],2,loc2,0); res := MultiSeries:-`multiseries/add`([res1, res2]); subsop(9 = `D(AiryBi)`(op(9,expr)),res) end proc:
`multiseries/function`[`D(AiryBi)`, infinity, -1/3*Pi .. 1/3*Pi]:=proc (expr, scale, var, order, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:49`; res := MultiSeries:-`multiseries/add`([MultiSeries:-`multiseries/mul`([MultiSeries:-`multiseries/compose`(MultiSeries:-`multiseries/pow`(SERIES(scale,[1],0,integer,[1],infinity,integer,eval(scale['variable'],1),eval(scale['variable'],1)),-1/2,scale,var,order),MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,1/2,scale,var,order),I),scale,var,order), MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,1/2,scale,var,order),I),-3,scale,var,order),-2/3),scale,var,order), MultiSeries:-`multiseries/compose`(MultiSeries:-`multiseries/function`[`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`](SERIES(scale,[1],0,integer,[1],infinity,integer,eval(scale['variable'],1),eval(scale['variable'],1)),scale,[eval(scale['variable'],1)],order),MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,1/2,scale,var,order),I),scale,var,order)])]) end proc:
`multiseries/function`[`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:48`; if n = 0 then [1] elif n = 1 then [1, 0] elif n = 2 then [1, 0, 0] else loc[0] := 1; loc[1] := 0; loc[2] := 0; for i1 from 3 to n do loc[i1] := -(-7-12*c+4*c^2+(8*c-12+4*i1)*i1)*loc[i1-3]/(16*c+16*i1) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`D(AiryBi)`, 0, "BasisVector", 0, 2, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:47`; [MultiSeries:-`multiseries/function`[`D(AiryBi)`,0,"BasisVector",0,2,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`D(AiryBi)`, 0, "BasisVector", 0, 0, 0, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:46`; SERIES(scale,MultiSeries:-`multiseries/function`[`D(AiryBi)`,0,"CoeffProc",2,2,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`D(AiryBi)/0/BasisVector/0/0/0/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`D(AiryBi)`, 0, "CoeffProc", 2, 2, 1]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:45`; loc[0] := -2; loc[1] := 0; loc[2] := 0; loc[3] := -2/3; loc[4] := 0; loc[5] := 0; for i1 from 6 to n do loc[i1] := loc[i1-3]/i1/(i1-2) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:49`; [MultiSeries:-`multiseries/function`[`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`D(AiryBi)`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:43`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`D(AiryAi)`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`D(AiryBi)`(_AnyFiniteOrdinaryPoint),diff(`D(AiryBi)`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`D(AiryBi)`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:49`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := I/Pi^(1/2); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `D(AiryBi)/infinity/aux/0/-1/3*Pi .. 1/3*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`D(AiryBi)`, 0, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/22/2004 @ 22:49:46`; [MultiSeries:-`multiseries/function`[`D(AiryBi)`,0,"BasisVector",0,0,0,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[`D(AiryBi)`,0,"BasisVector",0,0,0,"MultiSeries",1](args)] end proc:
