# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[`Ei/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:43`; SERIES(scale,MultiSeries:-`multiseries/function`[`Ei/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ei/infinity/aux/0/-Pi .. Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Ei, 0, "BasisVector", 0, 0, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:39`; [0, MultiSeries:-`multiseries/function`[Ei,0,"CoeffProc",0,0,1](n), MultiSeries:-`multiseries/function`[Ei,0,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[Ei, 0, "BasisVector", 0, 0, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:40`; [MultiSeries:-`multiseries/function`[Ei,0,"BasisVector",0,0,1,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[Ei,0,"BasisVector",0,0,1,"MultiSeries",1](args)] end proc:
`multiseries/function`[`Ei/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:41`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] else loc[0] := arg0; loc[1] := arg1; for i1 from 2 to n do loc[i1] := (loc[i1-2]-(-xarg-1)*loc[i1-1]-(loc[i1-2]+2*xarg*loc[i1-1])*i1)/xarg^2/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[Ei, 0, "BasisVector", 0, 0, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:40`; SERIES(scale,MultiSeries:-`multiseries/function`[Ei,0,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ei/0/BasisVector/0/0/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Ei, 0, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:40`; [MultiSeries:-`multiseries/function`[Ei,0,"BasisVector",0,0,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[Ei]:=proc (expr, scale, var, order) local lim, argseq, res; option `Copyright (c) 2002-2004 by the Algorithms Project, INRIA`; if not type(expr,list) then if expr = 0 then return `multiseries/Convert2SERIES`(Ei(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := `multiseries/function`[Ei,0](argseq); if `multiseries/sign`(expr) = -1 then res := `multiseries/AddDoit`(res,-I*Pi) else res end if elif lim = infinity then res := `multiseries/function`[Ei,infinity,-Pi .. Pi](argseq,[op(1,[argseq]), scale, var, order]) else res := eval(`multiseries/function`[Ei,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = ('Ei')(op(9,expr)),res) else subsop(9 = ('Ei')(op(map2(op,9,expr))),`multiseries/MulDoit`(`multiseries/function`['exp'](`multiseries/MulDoit`(`multiseries/AddDoit`(expr[1],-1),`multiseries/function`['ln'](expr[2],args[2 .. -1])),args[2 .. -1]),`multiseries/function`['GAMMA']([`multiseries/AddDoit`(1,`multiseries/MulSeriesCst`(expr[1],-1,integer)), expr[2]],args[2 .. -1]))) end if end proc:
`multiseries/function`[`Ei/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:43`; [MultiSeries:-`multiseries/function`[`Ei/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`Ei/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:41`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Ei/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Ei/infinity/aux/0/-Pi .. Pi`(_AnyFiniteOrdinaryPoint),diff(`Ei/infinity/aux/0/-Pi .. Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ei/infinity/aux/0/-Pi .. Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[Ei, 0, "CoeffProc", 0, 0, 1]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:38`; xxloc1 := MultiSeries:-`multiseries/function`[Ei,0,"CoeffProc",0,0,0](n); loc[0] := 0; loc[1] := 1; for i1 from 2 to n do loc[i1] := (op(i1,xxloc1)-2*i1*op(i1+1,xxloc1)-(1-i1)*loc[i1-1])/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[Ei, 0, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:39`; [0, MultiSeries:-`multiseries/function`[Ei,0,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[`Ei/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:42`; if n = 0 then [1] else loc[0] := 1; for i1 to n do loc[i1] := (c+i1)*loc[i1-1] end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`Ei/infinity/aux/0/-Pi .. Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:43`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Ei/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := 1; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Ei/infinity/aux/0/-Pi .. Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Ei/infinity/aux/0/-Pi .. Pi`(op(9,expr)),res) end proc:
`multiseries/function`[Ei, 0, "CoeffProc", 0, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:38`; loc[0] := 1; loc[1] := 0; for i1 from 2 to n do loc[i1] := -(1-i1)*loc[i1-1]/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[`Ei/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:42`; [0, MultiSeries:-`multiseries/function`[`Ei/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[Ei, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:37`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] else loc[0] := arg0; loc[1] := arg1; for i1 from 2 to n do loc[i1] := (-2*loc[i1-2]-(xarg+1)*loc[i1-1]-(-loc[i1-2]+(-xarg-2)*loc[i1-1]+loc[i1-1]*i1)*i1)/(-xarg+i1*xarg)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[Ei, infinity, -Pi .. Pi]:=proc (expr, scale, var, order, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:43`; res := MultiSeries:-`multiseries/add`([MultiSeries:-`multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),1),scale,var,order), MultiSeries:-`multiseries/function`[`Ei/infinity/aux/0/-Pi .. Pi`](op(arglist))])]) end proc:
`multiseries/function`[Ei, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:37`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[Ei,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,Ei(_AnyFiniteOrdinaryPoint),exp(_AnyFiniteOrdinaryPoint)/_AnyFiniteOrdinaryPoint,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),Ei(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[Ei, 0, "BasisVector", 0, 0, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:40`; SERIES(scale,MultiSeries:-`multiseries/function`[Ei,0,"CoeffProc",0,0,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ei/0/BasisVector/0/0/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Ei/infinity/aux/0/-Pi .. Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:43`; if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`Ei/infinity/aux/0/-Pi .. Pi`(0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Ei/infinity/aux/0/-Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Ei/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Ei/infinity/aux/0/-Pi .. Pi`(op(9,expr)),res) end proc:
`multiseries/function`[Ei, 0, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:39`; SERIES(scale,MultiSeries:-`multiseries/function`[Ei,0,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ei/0/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Ei, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:41`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[Ei,0,"BasisVector",0,0,0,"MultiSeries"](expr,scale,var,order); loc2 := gamma; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); loc1 := MultiSeries:-`multiseries/function`[Ei,0,"BasisVector",0,0,1,"MultiSeries"](expr,scale,var,order); loc2 := 1; res2 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := MultiSeries:-`multiseries/add`([res1, res2]); subsop(9 = Ei(op(9,expr)),res) end proc:
`multiseries/function`[`Ei/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:37:42`; MultiSeries:-`multiseries/function`[`Ei/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0) end proc:
