# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[EllipticE, -1, "CoeffProc", 1, 0, 1]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:25`; xxloc1 := MultiSeries:-`multiseries/function`[EllipticE,-1,"CoeffProc",1,0,0](n); loc[0] := 6; loc[1] := 5; loc[2] := 27/8; for i1 from 3 to n do loc[i1] := (-(2*i1-2)*op(i1-1,xxloc1)-(1-6*i1)*op(i1,xxloc1)-(4*i1+2)*op(i1+1,xxloc1)-loc[i1-1]-(-2*loc[i1-2]+loc[i1-1]+(loc[i1-2]-3*loc[i1-1])*i1)*i1)/i1/(2*i1+2) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticE, -1, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:27`; [0, MultiSeries:-`multiseries/function`[EllipticE,-1,"CoeffProc",1,1,2](n), 2*MultiSeries:-`multiseries/function`[EllipticE,-1,"CoeffProc",1,1,1](n), MultiSeries:-`multiseries/function`[EllipticE,-1,"CoeffProc",1,1,0](n)] end proc:
`multiseries/function`[EllipticE, -1, "BasisVector", 0, 1, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:26`; [1, MultiSeries:-`multiseries/function`[EllipticE,-1,"CoeffProc",1,0,0](n)] end proc:
`multiseries/function`[EllipticE, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:14`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[EllipticE,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,EllipticE(_AnyFiniteOrdinaryPoint),EllipticE(_AnyFiniteOrdinaryPoint)/_AnyFiniteOrdinaryPoint-EllipticK(_AnyFiniteOrdinaryPoint)/_AnyFiniteOrdinaryPoint,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),EllipticE(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[EllipticE, 0, "BasisVector", 0, 0, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:17`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticE,0,"CoeffProc",0,0,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticE/0/BasisVector/0/0/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticE, -1, "BasisVector", 0, 1, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:26`; [1, MultiSeries:-`multiseries/function`[EllipticE,-1,"CoeffProc",1,0,1](n), MultiSeries:-`multiseries/function`[EllipticE,-1,"CoeffProc",1,0,0](n)] end proc:
`multiseries/function`[EllipticE, -1, "BasisVector", 0, 1, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:28`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticE,-1,"CoeffProc",1,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticE/-1/BasisVector/0/1/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticE, -1, "BasisVector", 0, 1, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:29`; [MultiSeries:-`multiseries/function`[EllipticE,-1,"BasisVector",0,1,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[EllipticE, 1, "BasisVector", 0, 1, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:23`; [MultiSeries:-`multiseries/function`[EllipticE,1,"BasisVector",0,1,1,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[EllipticE,1,"BasisVector",0,1,1,"MultiSeries",1](args)] end proc:
`multiseries/function`[EllipticE, -1, "BasisVector", 0, 1, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:30`; [MultiSeries:-`multiseries/function`[EllipticE,-1,"BasisVector",0,1,1,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[EllipticE,-1,"BasisVector",0,1,1,"MultiSeries",1](args)] end proc:
`multiseries/function`[EllipticE, 1, "CoeffProc", 1, 1, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:20`; loc[0] := 0; loc[1] := 1; loc[2] := -1/4; loc[3] := 3/16; for i1 from 4 to n do loc[i1] := (-3*loc[i1-2]-3*loc[i1-1]-(-4*loc[i1-2]-7*loc[i1-1]+(loc[i1-2]+3*loc[i1-1])*i1)*i1)/i1/(2*i1-2) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticE, 1, "CoeffProc", 1, 1, 2]:=proc (n) local i1, loc, xxloc1, xxloc2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:20`; xxloc1 := MultiSeries:-`multiseries/function`[EllipticE,1,"CoeffProc",1,1,1](n); xxloc2 := MultiSeries:-`multiseries/function`[EllipticE,1,"CoeffProc",1,1,0](n); loc[0] := 4; loc[1] := -6; loc[2] := 5/8; loc[3] := -37/96; for i1 from 4 to n do loc[i1] := (-4*(i1-2)*op(i1-1,xxloc1)-2*(-7+6*i1)*op(i1,xxloc1)-2*(-2+4*i1)*op(i1+1,xxloc1)-2*op(i1-1,xxloc2)-6*op(i1,xxloc2)-4*op(i1+1,xxloc2)-3*loc[i1-2]-3*loc[i1-1]-(-4*loc[i1-2]-7*loc[i1-1]+(loc[i1-2]+3*loc[i1-1])*i1)*i1)/i1/(2*i1-2) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticE, -1, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:28`; [MultiSeries:-`multiseries/function`[EllipticE,-1,"BasisVector",0,0,0,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[EllipticE,-1,"BasisVector",0,0,0,"MultiSeries",1](args), MultiSeries:-`multiseries/function`[EllipticE,-1,"BasisVector",0,0,0,"MultiSeries",2](args)] end proc:
`multiseries/function`[EllipticE, 0, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:17`; [MultiSeries:-`multiseries/function`[EllipticE,0,"BasisVector",0,0,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[EllipticE, -1, "CoeffProc", 1, 1, 2]:=proc (n) local i1, loc, xxloc1, xxloc2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:26`; xxloc1 := MultiSeries:-`multiseries/function`[EllipticE,-1,"CoeffProc",1,1,1](n); xxloc2 := MultiSeries:-`multiseries/function`[EllipticE,-1,"CoeffProc",1,1,0](n); loc[0] := 4; loc[1] := 6; loc[2] := 5/8; loc[3] := 37/96; for i1 from 4 to n do loc[i1] := (-4*(i1-2)*op(i1-1,xxloc1)-2*(7-6*i1)*op(i1,xxloc1)-2*(-2+4*i1)*op(i1+1,xxloc1)-2*op(i1-1,xxloc2)+6*op(i1,xxloc2)-4*op(i1+1,xxloc2)-3*loc[i1-2]+3*loc[i1-1]-(-4*loc[i1-2]+7*loc[i1-1]+(loc[i1-2]-3*loc[i1-1])*i1)*i1)/i1/(2*i1-2) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticE, 1, "BasisVector", 0, 1, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:23`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticE,1,"CoeffProc",1,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticE/1/BasisVector/0/1/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticE, -1, "CoeffProc", 1, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:24`; loc[0] := 4; loc[1] := 1; loc[2] := 3/4; for i1 from 3 to n do loc[i1] := (-loc[i1-1]-(-2*loc[i1-2]+loc[i1-1]+(loc[i1-2]-3*loc[i1-1])*i1)*i1)/i1/(2*i1+2) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticE, -1, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:27`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticE,-1,"CoeffProc",1,1,2](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticE/-1/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticE, 0, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:16`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticE,0,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticE/0/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticE, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:14`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, 1/2*(xarg*arg0-arg1*xarg^2+arg1)/(xarg^2-1)/xarg] else loc[0] := arg0; loc[1] := arg1; loc[2] := 1/2*(xarg*arg0-arg1*xarg^2+arg1)/(xarg^2-1)/xarg; for i1 from 3 to n do loc[i1] := (-8*loc[i1-3]-(5*xarg^2-1)*loc[i1-1]-13*xarg*loc[i1-2]-(-6*loc[i1-3]-13*xarg*loc[i1-2]+(2-8*xarg^2)*loc[i1-1]+(3*xarg*loc[i1-2]+loc[i1-3]+(-1+3*xarg^2)*loc[i1-1])*i1)*i1)/(xarg-xarg^3+(-xarg+xarg^3)*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[EllipticE, -1, "CoeffProc", 1, 1, 1]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:26`; xxloc1 := MultiSeries:-`multiseries/function`[EllipticE,-1,"CoeffProc",1,1,0](n); loc[0] := 2; loc[1] := -1; loc[2] := -5/8; loc[3] := -3/8; for i1 from 4 to n do loc[i1] := (-2*(i1-2)*op(i1-1,xxloc1)-(7-6*i1)*op(i1,xxloc1)-(-2+4*i1)*op(i1+1,xxloc1)-3*loc[i1-2]+3*loc[i1-1]-(-4*loc[i1-2]+7*loc[i1-1]+(loc[i1-2]-3*loc[i1-1])*i1)*i1)/i1/(2*i1-2) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticE, 1, "BasisVector", 0, 0, 0, "MultiSeries", 2]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:22`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticE,1,"CoeffProc",1,1,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticE/1/BasisVector/0/0/0/MultiSeries/2`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticE, -1, "BasisVector", 0, 0, 0, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:27`; SERIES(scale,2*MultiSeries:-`multiseries/function`[EllipticE,-1,"CoeffProc",1,1,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticE/-1/BasisVector/0/0/0/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticE, 1, "BasisVector", 0, 1, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:23`; [MultiSeries:-`multiseries/function`[EllipticE,1,"BasisVector",0,1,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[EllipticE, 0, "BasisVector", 0, 0, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:16`; [0, MultiSeries:-`multiseries/function`[EllipticE,0,"CoeffProc",0,0,1](n), MultiSeries:-`multiseries/function`[EllipticE,0,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[EllipticE, 1, "BasisVector", 0, 1, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:21`; [1, MultiSeries:-`multiseries/function`[EllipticE,1,"CoeffProc",1,0,1](n), MultiSeries:-`multiseries/function`[EllipticE,1,"CoeffProc",1,0,0](n)] end proc:
`multiseries/function`[EllipticE, 0, "BasisVector", 0, 0, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:18`; [MultiSeries:-`multiseries/function`[EllipticE,0,"BasisVector",0,0,1,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[EllipticE,0,"BasisVector",0,0,1,"MultiSeries",1](args)] end proc:
`multiseries/function`[EllipticE, 1, "BasisVector", 0, 0, 0, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:21`; SERIES(scale,2*MultiSeries:-`multiseries/function`[EllipticE,1,"CoeffProc",1,1,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticE/1/BasisVector/0/0/0/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticE, 1, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:22`; [MultiSeries:-`multiseries/function`[EllipticE,1,"BasisVector",0,0,0,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[EllipticE,1,"BasisVector",0,0,0,"MultiSeries",1](args), MultiSeries:-`multiseries/function`[EllipticE,1,"BasisVector",0,0,0,"MultiSeries",2](args)] end proc:
`multiseries/function`[EllipticE, 1, "BasisVector", 0, 1, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:23`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticE,1,"CoeffProc",1,0,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticE/1/BasisVector/0/1/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticE, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:18`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[EllipticE,0,"BasisVector",0,0,0,"MultiSeries"](expr,scale,var,order); loc2 := 1/2*Pi; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*EllipticE(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = EllipticE(op(9,expr)),res) end proc:
`multiseries/function`[EllipticE, 1, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:21`; [0, MultiSeries:-`multiseries/function`[EllipticE,1,"CoeffProc",1,1,2](n), 2*MultiSeries:-`multiseries/function`[EllipticE,1,"CoeffProc",1,1,1](n), MultiSeries:-`multiseries/function`[EllipticE,1,"CoeffProc",1,1,0](n)] end proc:
`multiseries/function`[EllipticE, 1]:=proc (expr, scale, var, order) local loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:24`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[EllipticE,1,"BasisVector",0,0,0,"MultiSeries"](expr,scale,var,order); loc2 := 1/4; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,1); loc1 := MultiSeries:-`multiseries/function`[EllipticE,1,"BasisVector",0,1,0,"MultiSeries"](expr,scale,var,order); loc2 := -3/8*ln(2)+1/2+1/8*I*Pi; res2 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],1,loc2,1); res := MultiSeries:-`multiseries/add`([res1, res2]); subsop(9 = EllipticE(op(9,expr)),res) end proc:
`multiseries/function`[EllipticE, 1, "CoeffProc", 1, 1, 1]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:20`; xxloc1 := MultiSeries:-`multiseries/function`[EllipticE,1,"CoeffProc",1,1,0](n); loc[0] := 2; loc[1] := 1; loc[2] := -5/8; loc[3] := 3/8; for i1 from 4 to n do loc[i1] := (-2*(i1-2)*op(i1-1,xxloc1)-(-7+6*i1)*op(i1,xxloc1)-(-2+4*i1)*op(i1+1,xxloc1)-3*loc[i1-2]-3*loc[i1-1]-(-4*loc[i1-2]-7*loc[i1-1]+(loc[i1-2]+3*loc[i1-1])*i1)*i1)/i1/(2*i1-2) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticE, 0, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:16`; [0, MultiSeries:-`multiseries/function`[EllipticE,0,"CoeffProc",0,0,0](n)] end proc:
`multiseries/function`[EllipticE, 0, "CoeffProc", 0, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:15`; loc[0] := 1; loc[1] := 0; loc[2] := -1/4; for i1 from 3 to n do loc[i1] := (3+(i1-4)*i1)*loc[i1-2]/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticE, 1, "CoeffProc", 1, 0, 1]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:19`; xxloc1 := MultiSeries:-`multiseries/function`[EllipticE,1,"CoeffProc",1,0,0](n); loc[0] := 6; loc[1] := -5; loc[2] := 27/8; for i1 from 3 to n do loc[i1] := (-(2*i1-2)*op(i1-1,xxloc1)-(-1+6*i1)*op(i1,xxloc1)-(4*i1+2)*op(i1+1,xxloc1)+loc[i1-1]-(-2*loc[i1-2]-loc[i1-1]+(loc[i1-2]+3*loc[i1-1])*i1)*i1)/i1/(2*i1+2) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticE, 1, "BasisVector", 0, 1, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:20`; [1, MultiSeries:-`multiseries/function`[EllipticE,1,"CoeffProc",1,0,0](n)] end proc:
`multiseries/function`[EllipticE, -1, "CoeffProc", 1, 1, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:25`; loc[0] := 0; loc[1] := -1; loc[2] := -1/4; loc[3] := -3/16; for i1 from 4 to n do loc[i1] := (-3*loc[i1-2]+3*loc[i1-1]-(-4*loc[i1-2]+7*loc[i1-1]+(loc[i1-2]-3*loc[i1-1])*i1)*i1)/i1/(2*i1-2) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticE, -1, "BasisVector", 0, 0, 0, "MultiSeries", 2]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:28`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticE,-1,"CoeffProc",1,1,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticE/-1/BasisVector/0/0/0/MultiSeries/2`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticE, -1, "BasisVector", 0, 1, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:29`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticE,-1,"CoeffProc",1,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticE/-1/BasisVector/0/1/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticE, -1]:=proc (expr, scale, var, order) local loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:30`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[EllipticE,-1,"BasisVector",0,0,0,"MultiSeries"](expr,scale,var,order); loc2 := 1/4; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,-1); loc1 := MultiSeries:-`multiseries/function`[EllipticE,-1,"BasisVector",0,1,0,"MultiSeries"](expr,scale,var,order); loc2 := 3/8*ln(2)-1/2; res2 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],1,loc2,-1); res := MultiSeries:-`multiseries/add`([res1, res2]); subsop(9 = EllipticE(op(9,expr)),res) end proc:
`multiseries/function`[EllipticE, 0, "CoeffProc", 0, 0, 1]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:15`; xxloc1 := MultiSeries:-`multiseries/function`[EllipticE,0,"CoeffProc",0,0,0](n); loc[0] := 0; loc[1] := 0; loc[2] := 1/4; for i1 from 3 to n do loc[i1] := -(-2*(i1-2)*op(i1-1,xxloc1)+2*i1*op(i1+1,xxloc1)-(3+(i1-4)*i1)*loc[i1-2])/i1^2 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticE]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:30`; if expr = 0 then return `multiseries/Convert2SERIES`(EllipticE(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = -1 or Testzero(lim+1) then res := `multiseries/function`[EllipticE,-1](argseq) elif lim = 0 then res := `multiseries/function`[EllipticE,0](argseq) elif lim = 1 or Testzero(lim-1) then res := `multiseries/function`[EllipticE,1](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(`multiseries/function`[EllipticE,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = EllipticE(op(9,expr)),res) end proc:
`multiseries/function`[EllipticE, 1, "BasisVector", 0, 1, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:22`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticE,1,"CoeffProc",1,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticE/1/BasisVector/0/1/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticE, 0, "BasisVector", 0, 0, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:17`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticE,0,"CoeffProc",0,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticE/0/BasisVector/0/0/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticE, -1, "BasisVector", 0, 1, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:29`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticE,-1,"CoeffProc",1,0,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticE/-1/BasisVector/0/1/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[EllipticE, 1, "CoeffProc", 1, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:19`; loc[0] := 4; loc[1] := -1; loc[2] := 3/4; for i1 from 3 to n do loc[i1] := (loc[i1-1]-(-2*loc[i1-2]-loc[i1-1]+(loc[i1-2]+3*loc[i1-1])*i1)*i1)/i1/(2*i1+2) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[EllipticE, 1, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:38:21`; SERIES(scale,MultiSeries:-`multiseries/function`[EllipticE,1,"CoeffProc",1,1,2](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`EllipticE/1/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
