# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[JacobiP, infinity]:=proc (expr, scale, var, order, a1, a2, a3) local d1, d2, d3, loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:48`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[JacobiP,infinity,"BasisVector",_a1+_a2+_a3+1,"MultiSeries"](expr,scale,var,order,a1,a2,a3); loc2 := limit(limit(limit(2^(d1+d2+d3+1)*sin(d1*Pi)*GAMMA(-d2-3*d1-1)*GAMMA(d2+d1+1)/Pi/GAMMA(-d3-d1),d1 = a1,'left'),d2 = a2,'left'),d3 = a3,'left'); res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],a1+a2+a3+1,loc2,infinity); loc1 := MultiSeries:-`multiseries/function`[JacobiP,infinity,"BasisVector",-_a1,"MultiSeries"](expr,scale,var,order,a1,a2,a3); loc2 := limit(limit(limit(2^(-d1)*GAMMA(d2+d3+2*d1+1)/GAMMA(d1+d2+d3+1)/GAMMA(d1+1),d1 = a1,'left'),d2 = a2,'left'),d3 = a3,'left'); res2 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],-a1,loc2,infinity); res := MultiSeries:-`multiseries/add`([res1, res2]); subsop(9 = JacobiP(a1,a2,a3,op(9,expr)),res) end proc:
`multiseries/function`[JacobiP, infinity, "CoeffProc"]:=proc (n, c, a1, a2, a3) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:45`; if n = 0 then [normal(1)] elif n = 1 then [normal(1), normal(-c*(a2-a3)/(a1+a1^2+a1*a2+a1*a3+a2*c+a2+c*a3+a3-c^2-c))] else loc[0] := normal(1); loc[1] := normal(-c*(a2-a3)/(a1+a1^2+a1*a2+a1*a3+a2*c+a2+c*a3+a3-c^2-c)); for i1 from 2 to n do loc[i1] := normal((-(c^2-3*c+2)*loc[i1-2]-(a2*c-a2-c*a3+a3)*loc[i1-1]-((2*c-3)*loc[i1-2]+(a2-a3)*loc[i1-1]+loc[i1-2]*i1)*i1)/(a1+a1^2+a1*a2+a1*a3+a2*c+c*a3+c-c^2+(a2-2*c+a3+1-i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[JacobiP, -1, "BasisVector", -_a3]:=proc (n, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:43`; [-a3, MultiSeries:-`multiseries/function`[JacobiP,-1,"CoeffProc"](n,-a3,a1,a2,a3)] end proc:
`multiseries/function`[JacobiP, -1]:=proc (expr, scale, var, order, a1, a2, a3) local d1, d2, d3, loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:45`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[JacobiP,-1,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1,a2,a3); loc2 := limit(limit(limit(GAMMA(-d3)/GAMMA(d1+1)/GAMMA(-d3-d1),d1 = a1,'left'),d2 = a2,'left'),d3 = a3,'left'); res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,-1); loc1 := MultiSeries:-`multiseries/function`[JacobiP,-1,"BasisVector",-_a3,"MultiSeries"](expr,scale,var,order,a1,a2,a3); loc2 := limit(limit(limit(sin(d1*Pi)*GAMMA(d3)*GAMMA(d2+d1+1)*2^d3/Pi/GAMMA(d1+d2+d3+1),d1 = a1,'left'),d2 = a2,'left'),d3 = a3,'left'); res2 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],-a3,loc2,-1); res := MultiSeries:-`multiseries/add`([res1, res2]); subsop(9 = JacobiP(a1,a2,a3,op(9,expr)),res) end proc:
`multiseries/function`[JacobiP, infinity, "CoeffProc", -_a1]:=proc (n, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:46`; MultiSeries:-`multiseries/function`[JacobiP,infinity,"CoeffProc"](n,-a1,a1,a2,a3) end proc:
`multiseries/function`[JacobiP, -1, "BasisVector", -_a3, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:44`; SERIES(scale,MultiSeries:-`multiseries/function`[JacobiP,-1,"CoeffProc",-_a3](order,a1,a2,a3),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`JacobiP/-1/BasisVector/-_a3/MultiSeries/0`(a1,a2,a3,eval(scale['variable'],1))) end proc:
`multiseries/function`[JacobiP, 1, "CoeffProc", 0]:=proc (n, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:39`; MultiSeries:-`multiseries/function`[JacobiP,1,"CoeffProc"](n,0,a1,a2,a3) end proc:
`multiseries/function`[JacobiP, 1, "BasisVector", -_a2, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:41`; SERIES(scale,MultiSeries:-`multiseries/function`[JacobiP,1,"CoeffProc",-_a2](order,a1,a2,a3),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`JacobiP/1/BasisVector/-_a2/MultiSeries/0`(a1,a2,a3,eval(scale['variable'],1))) end proc:
`multiseries/function`[JacobiP, 0]:=proc (expr, scale, var, order, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:38`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[JacobiP,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,2^(-a1)*GAMMA(a2+a1+1)/GAMMA(a2+1)/GAMMA(a1+1)*hypergeom([-a1, -a3-a1],[a2+1],-1),a1*(a1+a2+a3+1)/(a2+1)*2^(-a1)*GAMMA(a2+a1+1)/GAMMA(a2+1)/GAMMA(a1+1)*hypergeom([1-a1, -a3-a1],[a2+2],-1),a1,a2,a3,0)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),JacobiP(a1,a2,a3,eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[JacobiP, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:38`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[JacobiP,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,JacobiP(a1,a2,a3,_AnyFiniteOrdinaryPoint),(a1+a2+a3+1)/(1-_AnyFiniteOrdinaryPoint)*JacobiP(a1,a2,a3,_AnyFiniteOrdinaryPoint)-(a1+a2+a3+1)/(1-_AnyFiniteOrdinaryPoint)*JacobiP(a1,a2,a3+1,_AnyFiniteOrdinaryPoint),a1,a2,a3,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),JacobiP(a1,a2,a3,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[JacobiP, -1, "BasisVector", -_a3, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:44`; [MultiSeries:-`multiseries/function`[JacobiP,-1,"BasisVector",-_a3,"MultiSeries",0](args)] end proc:
`multiseries/function`[JacobiP, 1, "BasisVector", -_a2]:=proc (n, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:40`; [-a2, MultiSeries:-`multiseries/function`[JacobiP,1,"CoeffProc"](n,-a2,a1,a2,a3)] end proc:
`multiseries/function`[JacobiP, 1, "CoeffProc"]:=proc (n, c, a1, a2, a3) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:39`; if n = 0 then [normal(1)] else loc[0] := normal(1); for i1 to n do loc[i1] := normal(-(a1^2+a1*a2+a1*a3+a1-a2*c+a2+c-c*a3+a3-c^2+(1-a3-a2-2*c-i1)*i1)*loc[i1-1]/(-2*a2*c-2*c^2+(-2*a2-4*c-2*i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[JacobiP, 1, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:40`; SERIES(scale,MultiSeries:-`multiseries/function`[JacobiP,1,"CoeffProc",0](order,a1,a2,a3),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`JacobiP/1/BasisVector/0/MultiSeries/0`(a1,a2,a3,eval(scale['variable'],1))) end proc:
`multiseries/function`[JacobiP, -1, "CoeffProc"]:=proc (n, c, a1, a2, a3) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:42`; if n = 0 then [normal(1)] else loc[0] := normal(1); for i1 to n do loc[i1] := normal(-(a1^2+a1*a2+a1*a3+a1-a2*c+a2+c-c*a3+a3-c^2+(1-a3-a2-2*c-i1)*i1)*loc[i1-1]/(2*c*a3+2*c^2+(2*a3+4*c+2*i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[JacobiP, -1, "CoeffProc", -_a3]:=proc (n, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:43`; MultiSeries:-`multiseries/function`[JacobiP,-1,"CoeffProc"](n,-a3,a1,a2,a3) end proc:
`multiseries/function`[JacobiP, -1, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:44`; [MultiSeries:-`multiseries/function`[JacobiP,-1,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[JacobiP, infinity, "BasisVector", _a1+_a2+_a3+1]:=proc (n, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:45`; [a1+a2+a3+1, MultiSeries:-`multiseries/function`[JacobiP,infinity,"CoeffProc"](n,a1+a2+a3+1,a1,a2,a3)] end proc:
`multiseries/function`[JacobiP, 1, "CoeffProc", -_a2]:=proc (n, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:40`; MultiSeries:-`multiseries/function`[JacobiP,1,"CoeffProc"](n,-a2,a1,a2,a3) end proc:
`multiseries/function`[JacobiP, -1, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:43`; SERIES(scale,MultiSeries:-`multiseries/function`[JacobiP,-1,"CoeffProc",0](order,a1,a2,a3),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`JacobiP/-1/BasisVector/0/MultiSeries/0`(a1,a2,a3,eval(scale['variable'],1))) end proc:
`multiseries/function`[JacobiP, 1]:=proc (expr, scale, var, order, a1, a2, a3) local d1, d2, d3, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:41`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[JacobiP,1,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1,a2,a3); loc2 := limit(limit(limit(GAMMA(d2+d1+1)/GAMMA(d1+1)/GAMMA(d2+1),d1 = a1,'left'),d2 = a2,'left'),d3 = a3,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*JacobiP(a1,a2,a3,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,1); res := res1; subsop(9 = JacobiP(a1,a2,a3,op(9,expr)),res) end proc:
`multiseries/function`[JacobiP, -1, "BasisVector", 0]:=proc (n, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:42`; [0, MultiSeries:-`multiseries/function`[JacobiP,-1,"CoeffProc"](n,0,a1,a2,a3)] end proc:
`multiseries/function`[JacobiP]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:48`; if nops(exprlist) <> 4 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return `multiseries/Convert2SERIES`(JacobiP(paramseq,0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = -1 or Testzero(lim+1) then res := `multiseries/function`[JacobiP,-1](argseq) elif lim = 0 then res := `multiseries/function`[JacobiP,0](argseq) elif lim = 1 or Testzero(lim-1) then res := `multiseries/function`[JacobiP,1](argseq) elif lim = infinity then res := `multiseries/function`[JacobiP,infinity](argseq) else res := eval(`multiseries/function`[JacobiP,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = JacobiP(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[JacobiP, infinity, "BasisVector", -_a1, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:47`; [MultiSeries:-`multiseries/function`[JacobiP,infinity,"BasisVector",-_a1,"MultiSeries",0](args)] end proc:
`multiseries/function`[JacobiP, infinity, "BasisVector", -_a1]:=proc (n, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:46`; [-a1, MultiSeries:-`multiseries/function`[JacobiP,infinity,"CoeffProc"](n,-a1,a1,a2,a3)] end proc:
`multiseries/function`[JacobiP, 1, "BasisVector", 0]:=proc (n, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:39`; [0, MultiSeries:-`multiseries/function`[JacobiP,1,"CoeffProc"](n,0,a1,a2,a3)] end proc:
`multiseries/function`[JacobiP, 1, "BasisVector", -_a2, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:41`; [MultiSeries:-`multiseries/function`[JacobiP,1,"BasisVector",-_a2,"MultiSeries",0](args)] end proc:
`multiseries/function`[JacobiP, infinity, "BasisVector", _a1+_a2+_a3+1, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:47`; [MultiSeries:-`multiseries/function`[JacobiP,infinity,"BasisVector",_a1+_a2+_a3+1,"MultiSeries",0](args)] end proc:
`multiseries/function`[JacobiP, infinity, "BasisVector", -_a1, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:47`; SERIES(scale,MultiSeries:-`multiseries/function`[JacobiP,infinity,"CoeffProc",-_a1](order,a1,a2,a3),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`JacobiP/infinity/BasisVector/-_a1/MultiSeries/0`(a1,a2,a3,eval(scale['variable'],1))) end proc:
`multiseries/function`[JacobiP, infinity, "CoeffProc", _a1+_a2+_a3+1]:=proc (n, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:46`; MultiSeries:-`multiseries/function`[JacobiP,infinity,"CoeffProc"](n,a1+a2+a3+1,a1,a2,a3) end proc:
`multiseries/function`[JacobiP, -1, "CoeffProc", 0]:=proc (n, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:42`; MultiSeries:-`multiseries/function`[JacobiP,-1,"CoeffProc"](n,0,a1,a2,a3) end proc:
`multiseries/function`[JacobiP, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, a1, a2, a3, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:38`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] else loc[0] := arg0; loc[1] := arg1; for i1 from 2 to n do loc[i1] := (-(a1+a1^2+a1*a2+a1*a3+2*a2-2+2*a3)*loc[i1-2]-(-a3-2*xarg+a2+xarg*a2+a3*xarg)*loc[i1-1]-((-a3+3-a2)*loc[i1-2]+(-a3*xarg-a2+4*xarg+a3-xarg*a2)*loc[i1-1]+(-loc[i1-2]-2*xarg*loc[i1-1])*i1)*i1)/(-1+xarg^2+(1-xarg^2)*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[JacobiP, infinity, "BasisVector", _a1+_a2+_a3+1, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:47`; SERIES(scale,MultiSeries:-`multiseries/function`[JacobiP,infinity,"CoeffProc",_a1+_a2+_a3+1](order,a1,a2,a3),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`JacobiP/infinity/BasisVector/_a1+_a2+_a3+1/MultiSeries/0`(a1,a2,a3,eval(scale['variable'],1))) end proc:
`multiseries/function`[JacobiP, 1, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2, a3) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:41`; [MultiSeries:-`multiseries/function`[JacobiP,1,"BasisVector",0,"MultiSeries",0](args)] end proc:
