# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[`KummerU/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:01`; SERIES(scale,MultiSeries:-`multiseries/function`[`KummerU/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc",0](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`KummerU/infinity/aux/0/-Pi .. Pi/0/BasisVector/0/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[KummerU, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:58`; [MultiSeries:-`multiseries/function`[KummerU,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[KummerU, infinity, -Pi .. Pi]:=proc (expr, scale, var, order, a1, a2, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:03`; res := MultiSeries:-`multiseries/add`([MultiSeries:-`multiseries/mul`([MultiSeries:-`multiseries/pow`(expr,a1,scale,var,order), MultiSeries:-`multiseries/function`[`KummerU/infinity/aux/0/-Pi .. Pi`](op(arglist))])]) end proc:
`multiseries/function`[`KummerU/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, a1, a2, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:00`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] else loc[0] := arg0; loc[1] := arg1; for i1 from 2 to n do loc[i1] := (-(-a1*a2-3*a1+a1^2+2+2*a2)*loc[i1-2]-(-2*a1*xarg+xarg*a2+2*xarg-1)*loc[i1-1]-((-a2-3+2*a1)*loc[i1-2]+(2*a1*xarg-xarg*a2+1-4*xarg)*loc[i1-1]+(loc[i1-2]+2*xarg*loc[i1-1])*i1)*i1)/(-xarg^2+xarg^2*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`KummerU/infinity/aux/0/-Pi .. Pi`]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:02`; if nops(exprlist) <> 3 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`KummerU/infinity/aux/0/-Pi .. Pi`(paramseq,0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`KummerU/infinity/aux/0/-Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`KummerU/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `KummerU/infinity/aux/0/-Pi .. Pi`(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[`KummerU/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:01`; [0, MultiSeries:-`multiseries/function`[`KummerU/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0,a1,a2)] end proc:
`multiseries/function`[KummerU, 0, "CoeffProc", 1-_a2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:58`; MultiSeries:-`multiseries/function`[KummerU,0,"CoeffProc"](n,1-a2,a1,a2) end proc:
`multiseries/function`[KummerU, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:56`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[KummerM,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,KummerU(a1,a2,_AnyFiniteOrdinaryPoint),((_AnyFiniteOrdinaryPoint+a1-a2)*KummerU(a1,a2,_AnyFiniteOrdinaryPoint)-KummerU(a1-1,a2,_AnyFiniteOrdinaryPoint))/_AnyFiniteOrdinaryPoint,a1,a2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),KummerU(a1,a2,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`KummerU/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:01`; MultiSeries:-`multiseries/function`[`KummerU/infinity/aux/0/-Pi .. Pi`,0,"CoeffProc"](n,0,a1,a2) end proc:
`multiseries/function`[KummerU, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:58`; SERIES(scale,MultiSeries:-`multiseries/function`[KummerU,0,"CoeffProc",0](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`KummerU/0/BasisVector/0/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[KummerU, 0, "BasisVector", 1-_a2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:57`; [1-a2, MultiSeries:-`multiseries/function`[KummerU,0,"CoeffProc"](n,1-a2,a1,a2)] end proc:
`multiseries/function`[KummerU, 0, "BasisVector", 1-_a2, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:59`; SERIES(scale,MultiSeries:-`multiseries/function`[KummerU,0,"CoeffProc",1-_a2](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`KummerU/0/BasisVector/1-_a2/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[KummerU, 0, "CoeffProc"]:=proc (n, c, a1, a2) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:56`; if n = 0 then [normal(1)] else loc[0] := normal(1); for i1 to n do loc[i1] := normal(-(-a1-c-i1+1)*loc[i1-1]/(-c+a2*c+c^2+(-1+a2+2*c+i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`KummerU/infinity/aux/0/-Pi .. Pi`, 0]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:02`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`KummerU/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit(1,d1 = a1,'left'),d2 = a2,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`KummerU/infinity/aux/0/-Pi .. Pi`(a1,a2,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `KummerU/infinity/aux/0/-Pi .. Pi`(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[KummerU, 0, "BasisVector", 0]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:57`; [0, MultiSeries:-`multiseries/function`[KummerU,0,"CoeffProc"](n,0,a1,a2)] end proc:
`multiseries/function`[`KummerU/infinity/aux/0/-Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c, a1, a2) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:00`; if n = 0 then [normal(1)] else loc[0] := normal(1); for i1 to n do loc[i1] := normal(-(-a1-a1*a2+a1^2+2*a1*c-c-a2*c+a2+c^2+(-1-a2+2*a1+2*c+i1)*i1)*loc[i1-1]/(c+i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[KummerU, 0, "CoeffProc", 0]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:57`; MultiSeries:-`multiseries/function`[KummerU,0,"CoeffProc"](n,0,a1,a2) end proc:
`multiseries/function`[KummerU]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:03`; if nops(exprlist) <> 3 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return `multiseries/Convert2SERIES`(KummerU(paramseq,0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = 0 then res := `multiseries/function`[KummerU,0](argseq) elif lim = infinity then res := `multiseries/function`[KummerU,infinity,-Pi .. Pi](argseq,[[op(1 .. -2,exprlist), op(1,[argseq])], scale, var, order]) else res := eval(`multiseries/function`[KummerU,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = KummerU(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[KummerU, 0, "BasisVector", 1-_a2, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:59`; [MultiSeries:-`multiseries/function`[KummerU,0,"BasisVector",1-_a2,"MultiSeries",0](args)] end proc:
`multiseries/function`[KummerU, 0]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:39:59`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[KummerU,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit(Pi/sin(Pi*d2)/GAMMA(d2)/GAMMA(1-d2+d1),d1 = a1,'left'),d2 = a2,'left'); res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); loc1 := MultiSeries:-`multiseries/function`[KummerU,0,"BasisVector",1-_a2,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit(-Pi/sin(Pi*d2)/GAMMA(d1)/GAMMA(2-d2),d1 = a1,'left'),d2 = a2,'left'); res2 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],1-a2,loc2,0); res := MultiSeries:-`multiseries/add`([res1, res2]); subsop(9 = KummerU(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[`KummerU/infinity/aux/0/-Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:02`; [MultiSeries:-`multiseries/function`[`KummerU/infinity/aux/0/-Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`KummerU/infinity/aux/0/-Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:00`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`KummerU/infinity/aux/0/-Pi .. Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`KummerU/infinity/aux/0/-Pi .. Pi`(a1,a2,_AnyFiniteOrdinaryPoint),D[3](`KummerU/infinity/aux/0/-Pi .. Pi`)(a1,a2,_AnyFiniteOrdinaryPoint),a1,a2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`KummerU/infinity/aux/0/-Pi .. Pi`(a1,a2,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
