# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[LegendreP, 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:15`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[LegendreP,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,2^a2*cos(1/2*(-a1+a2)*Pi)*GAMMA(1/2*a1+1/2*a2+1/2)/GAMMA(1/2*a1-1/2*a2+1),2^a2*cos(1/2*(-a1+a2)*Pi)*GAMMA(1/2*a1+1/2*a2+1/2)/GAMMA(1/2*a1-1/2*a2+1),a1,a2,0)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),LegendreP(a1,a2,eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[LegendreP, -1, "BasisVector", -1/2*_a2, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:21`; [MultiSeries:-`multiseries/function`[LegendreP,-1,"BasisVector",-1/2*_a2,"MultiSeries",0](args)] end proc:
`multiseries/function`[LegendreP, 1, "CoeffProc", 1/2*_a2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:16`; MultiSeries:-`multiseries/function`[LegendreP,1,"CoeffProc"](n,1/2*a2,a1,a2) end proc:
`multiseries/function`[LegendreP, 1, "BasisVector", -1/2*_a2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:16`; [-1/2*a2, MultiSeries:-`multiseries/function`[LegendreP,1,"CoeffProc"](n,-1/2*a2,a1,a2)] end proc:
`multiseries/function`[LegendreP, -1]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:22`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[LegendreP,-1,"BasisVector",1/2*_a2,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit(2^(-1/2*d2)*GAMMA(-d2)*(-1)^(1/2*d2)/GAMMA(-d2-d1)/GAMMA(1-d2+d1),d1 = a1,'left'),d2 = a2,'left'); res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],1/2*a2,loc2,-1); loc1 := MultiSeries:-`multiseries/function`[LegendreP,-1,"BasisVector",-1/2*_a2,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit(2^(1/2*d2)*sin(Pi*d2)*GAMMA(d2)*(-1)^(1/2*d2)/Pi,d1 = a1,'left'),d2 = a2,'left'); res2 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],-1/2*a2,loc2,-1); res := MultiSeries:-`multiseries/add`([res1, res2]); subsop(9 = LegendreP(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[LegendreP, 1, "BasisVector", 1/2*_a2, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:17`; SERIES(scale,MultiSeries:-`multiseries/function`[LegendreP,1,"CoeffProc",1/2*_a2](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`LegendreP/1/BasisVector/1/2*_a2/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[LegendreP, -1, "CoeffProc"]:=proc (n, c, a1, a2) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:19`; if n = 0 then [normal(1)] elif n = 1 then [normal(1), normal(2*(-c+a1-2*c^2+a1^2)/(a2^2-4*c^2-8*c-4))] else loc[0] := normal(1); loc[1] := normal(2*(-c+a1-2*c^2+a1^2)/(a2^2-4*c^2-8*c-4)); for i1 from 2 to n do loc[i1] := normal((-(-a1^2-a1-3*c+2+c^2)*loc[i1-2]-(6*c-2+2*a1-4*c^2+2*a1^2)*loc[i1-1]-((2*c-3)*loc[i1-2]+(6-8*c)*loc[i1-1]+(loc[i1-2]-4*loc[i1-1])*i1)*i1)/(-a2^2+4*c^2+(8*c+4*i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[LegendreP, 1, "BasisVector", 1/2*_a2, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:17`; [MultiSeries:-`multiseries/function`[LegendreP,1,"BasisVector",1/2*_a2,"MultiSeries",0](args)] end proc:
`multiseries/function`[LegendreP, -1, "BasisVector", -1/2*_a2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:20`; [-1/2*a2, MultiSeries:-`multiseries/function`[LegendreP,-1,"CoeffProc"](n,-1/2*a2,a1,a2)] end proc:
`multiseries/function`[LegendreP, -1, "CoeffProc", -1/2*_a2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:20`; MultiSeries:-`multiseries/function`[LegendreP,-1,"CoeffProc"](n,-1/2*a2,a1,a2) end proc:
`multiseries/function`[LegendreP, 1, "BasisVector", -1/2*_a2, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:18`; [MultiSeries:-`multiseries/function`[LegendreP,1,"BasisVector",-1/2*_a2,"MultiSeries",0](args)] end proc:
`multiseries/function`[LegendreP, infinity, "CoeffProc", _a1+1]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:23`; MultiSeries:-`multiseries/function`[LegendreP,infinity,"CoeffProc"](n,a1+1,a1,a2) end proc:
`multiseries/function`[LegendreP, -1, "BasisVector", 1/2*_a2, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:20`; SERIES(scale,MultiSeries:-`multiseries/function`[LegendreP,-1,"CoeffProc",1/2*_a2](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`LegendreP/-1/BasisVector/1/2*_a2/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[LegendreP, infinity, "BasisVector", _a1+1, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:25`; [MultiSeries:-`multiseries/function`[LegendreP,infinity,"BasisVector",_a1+1,"MultiSeries",0](args)] end proc:
`multiseries/function`[LegendreP, 1]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:18`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[LegendreP,1,"BasisVector",-1/2*_a2,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit(2^(1/2*d2)/GAMMA(1-d2),d1 = a1,'left'),d2 = a2,'left'); if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*LegendreP(a1,a2,eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],-1/2*a2,loc2,1); res := res1; subsop(9 = LegendreP(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[LegendreP, infinity, "BasisVector", -_a1]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:22`; [-a1, MultiSeries:-`multiseries/function`[LegendreP,infinity,"CoeffProc"](n,-a1,a1,a2)] end proc:
`multiseries/function`[LegendreP, 1, "BasisVector", -1/2*_a2, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:18`; SERIES(scale,MultiSeries:-`multiseries/function`[LegendreP,1,"CoeffProc",-1/2*_a2](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`LegendreP/1/BasisVector/-1/2*_a2/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[LegendreP, infinity, "CoeffProc", -_a1]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:23`; MultiSeries:-`multiseries/function`[LegendreP,infinity,"CoeffProc"](n,-a1,a1,a2) end proc:
`multiseries/function`[LegendreP, infinity, "BasisVector", -_a1, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:24`; SERIES(scale,MultiSeries:-`multiseries/function`[LegendreP,infinity,"CoeffProc",-_a1](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`LegendreP/infinity/BasisVector/-_a1/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[LegendreP, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:15`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[LegendreP,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,LegendreP(a1,a2,_AnyFiniteOrdinaryPoint),((1-a2+a1)*LegendreP(a1+1,a2,_AnyFiniteOrdinaryPoint)-(a1+1)*_AnyFiniteOrdinaryPoint*LegendreP(a1,a2,_AnyFiniteOrdinaryPoint))/(_AnyFiniteOrdinaryPoint^2-1),a1,a2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),LegendreP(a1,a2,_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[LegendreP, infinity, "CoeffProc"]:=proc (n, c, a1, a2) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:22`; if n = 0 then [normal(1)] elif n = 1 then [normal(1), normal(0)] elif n = 2 then [normal(1), normal(0), normal((a1^2-a2^2+a1-2*c^2)/(a1^2-c^2-3*c-2+a1))] elif n = 3 then [normal(1), normal(0), normal((a1^2-a2^2+a1-2*c^2)/(a1^2-c^2-3*c-2+a1)), normal(0)] else loc[0] := normal(1); loc[1] := normal(0); loc[2] := normal((a1^2-a2^2+a1-2*c^2)/(a1^2-c^2-3*c-2+a1)); loc[3] := normal(0); for i1 from 4 to n do loc[i1] := normal((-(-7*c+12+c^2)*loc[i1-4]-(a1^2-a2^2+a1-2*c^2+8*c-8)*loc[i1-2]-((-7+2*c)*loc[i1-4]+(-4*c+8)*loc[i1-2]+(loc[i1-4]-2*loc[i1-2])*i1)*i1)/(-a1^2+c^2-a1-c+(2*c-1+i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[LegendreP, 1, "CoeffProc"]:=proc (n, c, a1, a2) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:15`; if n = 0 then [normal(1)] elif n = 1 then [normal(1), normal(-2*(-c+a1-2*c^2+a1^2)/(a2^2-4*c^2-8*c-4))] else loc[0] := normal(1); loc[1] := normal(-2*(-c+a1-2*c^2+a1^2)/(a2^2-4*c^2-8*c-4)); for i1 from 2 to n do loc[i1] := normal((-(-a1^2-a1-3*c+2+c^2)*loc[i1-2]-(-6*c+2-2*a1+4*c^2-2*a1^2)*loc[i1-1]-((2*c-3)*loc[i1-2]+(-6+8*c)*loc[i1-1]+(loc[i1-2]+4*loc[i1-1])*i1)*i1)/(-a2^2+4*c^2+(8*c+4*i1)*i1)) end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[LegendreP, 1, "CoeffProc", -1/2*_a2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:17`; MultiSeries:-`multiseries/function`[LegendreP,1,"CoeffProc"](n,-1/2*a2,a1,a2) end proc:
`multiseries/function`[LegendreP, -1, "BasisVector", 1/2*_a2, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:21`; [MultiSeries:-`multiseries/function`[LegendreP,-1,"BasisVector",1/2*_a2,"MultiSeries",0](args)] end proc:
`multiseries/function`[LegendreP, infinity]:=proc (expr, scale, var, order, a1, a2) local d1, d2, loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:25`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[LegendreP,infinity,"BasisVector",-_a1,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit(2^d1*GAMMA(d1+1/2)/Pi^(1/2)/GAMMA(1-d2+d1),d1 = a1,'left'),d2 = a2,'left'); res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],-a1,loc2,infinity); loc1 := MultiSeries:-`multiseries/function`[LegendreP,infinity,"BasisVector",_a1+1,"MultiSeries"](expr,scale,var,order,a1,a2); loc2 := limit(limit(-(-1)^(d1-d2)*2^(d1+1)*GAMMA(d2+d1+1)/GAMMA(-d1)/GAMMA(2*d1+2),d1 = a1,'left'),d2 = a2,'left'); res2 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],a1+1,loc2,infinity); res := MultiSeries:-`multiseries/add`([res1, res2]); subsop(9 = LegendreP(a1,a2,op(9,expr)),res) end proc:
`multiseries/function`[LegendreP, 1, "BasisVector", 1/2*_a2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:16`; [1/2*a2, MultiSeries:-`multiseries/function`[LegendreP,1,"CoeffProc"](n,1/2*a2,a1,a2)] end proc:
`multiseries/function`[LegendreP, _AnyFiniteOrdinaryPoint, "CoeffProc"]:=proc (n, arg0, arg1, a1, a2, xarg) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:14`; if n = 0 then [arg0] elif n = 1 then [arg0, arg1] elif n = 2 then [arg0, arg1, 1/2*(-a1^2*arg0+arg0*a1^2*xarg^2-a1*arg0+arg0*a1*xarg^2+arg0*a2^2+2*arg1*xarg-2*arg1*xarg^3)/(1-2*xarg^2+xarg^4)] elif n = 3 then [arg0, arg1, 1/2*(-a1^2*arg0+arg0*a1^2*xarg^2-a1*arg0+arg0*a1*xarg^2+arg0*a2^2+2*arg1*xarg-2*arg1*xarg^3)/(1-2*xarg^2+xarg^4), -1/6*(2*arg1-arg1*a1^2-arg1*a1+arg1*a2^2+4*arg1*xarg^2+2*arg1*a1^2*xarg^2+2*arg1*a1*xarg^2-xarg^4*arg1*a1^2+4*xarg^3*arg0*a1^2+4*xarg^3*arg0*a1-6*xarg^4*arg1-xarg^4*arg1*a1-4*arg0*a1^2*xarg-4*arg0*a1*xarg-arg1*a2^2*xarg^2+6*arg0*a2^2*xarg)/(3*xarg^2-3*xarg^4+xarg^6-1)] else loc[0] := arg0; loc[1] := arg1; loc[2] := 1/2*(-a1^2*arg0+arg0*a1^2*xarg^2-a1*arg0+arg0*a1*xarg^2+arg0*a2^2+2*arg1*xarg-2*arg1*xarg^3)/(1-2*xarg^2+xarg^4); loc[3] := -1/6*(2*arg1-arg1*a1^2-arg1*a1+arg1*a2^2+4*arg1*xarg^2+2*arg1*a1^2*xarg^2+2*arg1*a1*xarg^2-xarg^4*arg1*a1^2+4*xarg^3*arg0*a1^2+4*xarg^3*arg0*a1-6*xarg^4*arg1-xarg^4*arg1*a1-4*arg0*a1^2*xarg-4*arg0*a1*xarg-arg1*a2^2*xarg^2+6*arg0*a2^2*xarg)/(3*xarg^2-3*xarg^4+xarg^6-1); for i1 from 4 to n do loc[i1] := (-(-a1^2-a1+12)*loc[i1-4]-(-6*xarg+6*xarg^3)*loc[i1-1]-(a1^2-a1^2*xarg^2+a1-a1*xarg^2-a2^2+24*xarg^2-8)*loc[i1-2]-(-2*a1^2*xarg-2*a1*xarg+30*xarg)*loc[i1-3]-(-22*xarg*loc[i1-3]-7*loc[i1-4]+(-10*xarg^3+10*xarg)*loc[i1-1]+(8-24*xarg^2)*loc[i1-2]+((6*xarg^2-2)*loc[i1-2]+4*xarg*loc[i1-3]+loc[i1-4]+(-4*xarg+4*xarg^3)*loc[i1-1])*i1)*i1)/(-xarg^4+2*xarg^2-1+(1-2*xarg^2+xarg^4)*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[LegendreP, infinity, "BasisVector", -_a1, "MultiSeries"]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:24`; [MultiSeries:-`multiseries/function`[LegendreP,infinity,"BasisVector",-_a1,"MultiSeries",0](args)] end proc:
`multiseries/function`[LegendreP, -1, "CoeffProc", 1/2*_a2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:19`; MultiSeries:-`multiseries/function`[LegendreP,-1,"CoeffProc"](n,1/2*a2,a1,a2) end proc:
`multiseries/function`[LegendreP, infinity, "BasisVector", _a1+1]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:23`; [a1+1, MultiSeries:-`multiseries/function`[LegendreP,infinity,"CoeffProc"](n,a1+1,a1,a2)] end proc:
`multiseries/function`[LegendreP, infinity, "BasisVector", _a1+1, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:24`; SERIES(scale,MultiSeries:-`multiseries/function`[LegendreP,infinity,"CoeffProc",_a1+1](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`LegendreP/infinity/BasisVector/_a1+1/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
`multiseries/function`[LegendreP, -1, "BasisVector", 1/2*_a2]:=proc (n, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:19`; [1/2*a2, MultiSeries:-`multiseries/function`[LegendreP,-1,"CoeffProc"](n,1/2*a2,a1,a2)] end proc:
`multiseries/function`[LegendreP]:=proc (exprlist, scale, var, order) local paramseq, expr, lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:25`; if nops(exprlist) <> 3 then error "wrong number of arguments" end if; paramseq := op(map(`multiseries/Series2Expr`,[op(1 .. -2,exprlist)])); if has([paramseq],eval(scale['varname'],1)) then error "unable to expand with respect to parameter" end if; expr := op(-1,exprlist); if expr = 0 then return `multiseries/Convert2SERIES`(LegendreP(paramseq,0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then lim := infinity end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order, paramseq else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order, paramseq end if; if lim = -1 or Testzero(lim+1) then res := `multiseries/function`[LegendreP,-1](argseq) elif lim = 0 then res := `multiseries/function`[LegendreP,0](argseq) elif lim = 1 or Testzero(lim-1) then res := `multiseries/function`[LegendreP,1](argseq) elif lim = infinity then res := `multiseries/function`[LegendreP,infinity](argseq) else res := eval(`multiseries/function`[LegendreP,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = LegendreP(paramseq,op(9,expr)),res) end proc:
`multiseries/function`[LegendreP, -1, "BasisVector", -1/2*_a2, "MultiSeries", 0]:=proc (expr, scale, var, order, a1, a2) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:40:21`; SERIES(scale,MultiSeries:-`multiseries/function`[LegendreP,-1,"CoeffProc",-1/2*_a2](order,a1,a2),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`LegendreP/-1/BasisVector/-1/2*_a2/MultiSeries/0`(a1,a2,eval(scale['variable'],1))) end proc:
