# Copyright (C) 1991--2010 by INRIA.
#
# This file is part of Algolib.
#
# Algolib is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Algolib is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with Algolib.  If not, see
# <http://www.gnu.org/licenses/>.

`multiseries/function`[`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:53`; if n = 0 then [1] elif n = 1 then [1, 3/2*I*c+I] else loc[0] := 1; loc[1] := 3/2*I*c+I; for i1 from 2 to n do loc[i1] := -1/2*(-c^2+2*c-1)*loc[i1-2]-1/2*(I-3*I*c)*loc[i1-1]-1/2*((-2*c+2)*loc[i1-2]-3*I*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:49`; if n = 0 then [1] elif n = 1 then [1, -3/2*I*c-I] else loc[0] := 1; loc[1] := -3/2*I*c-I; for i1 from 2 to n do loc[i1] := -1/2*(-c^2+2*c-1)*loc[i1-2]-1/2*(-I+3*I*c)*loc[i1-1]-1/2*((-2*c+2)*loc[i1-2]+3*I*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:50`; MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[Ssi, 0, "CoeffProc", 1, 0, 0]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:40`; loc[0] := 4; loc[1] := 0; loc[2] := -2/9; for i1 from 3 to n do loc[i1] := -(i1-1)*loc[i1-2]/(1+(i1+2)*i1)/i1 end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:48`; SERIES(scale,MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Ssi/infinity/aux/2/1/2*Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:42:03`; SERIES(scale,MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/2/1/2*Pi .. Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ssi/infinity/aux/2/1/2*Pi .. Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:51`; [MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[Ssi, 0, "BasisVector", 0, 0, 1, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:44`; SERIES(scale,MultiSeries:-`multiseries/function`[Ssi,0,"CoeffProc",1,1,2](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ssi/0/BasisVector/0/0/1/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:54`; SERIES(scale,MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ssi/infinity/aux/1/-Pi .. -1/2*Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Ssi/infinity/aux/1/1/2*Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:42:00`; SERIES(scale,MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/1/2*Pi .. Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ssi/infinity/aux/1/1/2*Pi .. Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Ssi/infinity/aux/2/1/2*Pi .. Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:42:03`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/2/1/2*Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := -1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Ssi/infinity/aux/2/1/2*Pi .. Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Ssi/infinity/aux/2/1/2*Pi .. Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Ssi/infinity/aux/2/1/2*Pi .. Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:42:03`; if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`Ssi/infinity/aux/2/1/2*Pi .. Pi`(0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/2/1/2*Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/2/1/2*Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Ssi/infinity/aux/2/1/2*Pi .. Pi`(op(9,expr)),res) end proc:
`multiseries/function`[Ssi, 0, "CoeffProc", 1, 1, 1]:=proc (n) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:41`; loc[0] := 1; loc[1] := 0; loc[2] := 0; loc[3] := 0; for i1 from 4 to n do loc[i1] := -(i1-2)*loc[i1-2]/i1^2/(i1-1) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:55`; if n = 0 then [1] elif n = 1 then [1, -3/2*I*c-I] else loc[0] := 1; loc[1] := -3/2*I*c-I; for i1 from 2 to n do loc[i1] := -1/2*(-c^2+2*c-1)*loc[i1-2]-1/2*(-I+3*I*c)*loc[i1-1]-1/2*((-2*c+2)*loc[i1-2]+3*I*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`Ssi/infinity/aux/1/1/2*Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:58`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Ci/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Ssi/infinity/aux/1/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint),diff(`Ssi/infinity/aux/1/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Ssi/infinity/aux/1/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ssi/infinity/aux/1/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:54`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := -1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Ssi/infinity/aux/1/-Pi .. -1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:50`; [0, MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`Ssi/infinity/aux/1/1/2*Pi .. Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:42:00`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/1/2*Pi .. Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := -1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Ssi/infinity/aux/1/1/2*Pi .. Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Ssi/infinity/aux/1/1/2*Pi .. Pi`(op(9,expr)),res) end proc:
`multiseries/function`[Ssi, 0, "BasisVector", 0, 0, 0, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:43`; SERIES(scale,MultiSeries:-`multiseries/function`[Ssi,0,"CoeffProc",1,1,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ssi/0/BasisVector/0/0/0/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Ssi, 0, "BasisVector", 0, 1, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:42`; [1, MultiSeries:-`multiseries/function`[Ssi,0,"CoeffProc",1,0,0](n)] end proc:
`multiseries/function`[Ssi, 0, "BasisVector", 0, 0, 1, "MultiSeries", 2]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:44`; SERIES(scale,MultiSeries:-`multiseries/function`[Ssi,0,"CoeffProc",1,1,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ssi/0/BasisVector/0/0/1/MultiSeries/2`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Ssi/infinity/aux/1/1/2*Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:42:00`; [MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/1/2*Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[Ssi, infinity, -Pi .. -1/2*Pi]:=proc (expr, scale, var, order, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:58`; res := MultiSeries:-`multiseries/add`([MultiSeries:-`multiseries/Convert2SERIES`(-Pi,scale,var,false), MultiSeries:-`multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),-I),scale,var,order), MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`](op(arglist))]), MultiSeries:-`multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),I),scale,var,order), MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`](op(arglist))])]) end proc:
`multiseries/function`[`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:50`; SERIES(scale,MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:46`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Ci/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint),diff(`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[Ssi, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1, res2; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:46`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[Ssi,0,"BasisVector",0,0,0,"MultiSeries"](expr,scale,var,order); loc2 := -1/2*Pi; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); loc1 := MultiSeries:-`multiseries/function`[Ssi,0,"BasisVector",0,1,0,"MultiSeries"](expr,scale,var,order); loc2 := 1/4; res2 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],1,loc2,0); res := MultiSeries:-`multiseries/add`([res1, res2]); subsop(9 = Ssi(op(9,expr)),res) end proc:
`multiseries/function`[`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:49`; if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`(0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:57`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := -1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Ssi/infinity/aux/2/-Pi .. -1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Ssi/infinity/aux/2/1/2*Pi .. Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:42:02`; [0, MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/2/1/2*Pi .. Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:48`; [MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`Ssi/infinity/aux/1/1/2*Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:59`; if n = 0 then [1] elif n = 1 then [1, 3/2*I*c+I] else loc[0] := 1; loc[1] := 3/2*I*c+I; for i1 from 2 to n do loc[i1] := -1/2*(-c^2+2*c-1)*loc[i1-2]-1/2*(I-3*I*c)*loc[i1-1]-1/2*((-2*c+2)*loc[i1-2]-3*I*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`Ssi/infinity/aux/2/1/2*Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:42:02`; MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/2/1/2*Pi .. Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[`Ssi/infinity/aux/1/1/2*Pi .. Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:42:01`; if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`Ssi/infinity/aux/1/1/2*Pi .. Pi`(0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/1/2*Pi .. Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/1/2*Pi .. Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Ssi/infinity/aux/1/1/2*Pi .. Pi`(op(9,expr)),res) end proc:
`multiseries/function`[Ssi, 0, "BasisVector", 0, 0, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:42`; [0, MultiSeries:-`multiseries/function`[Ssi,0,"CoeffProc",1,1,1](n), MultiSeries:-`multiseries/function`[Ssi,0,"CoeffProc",1,1,0](n)] end proc:
`multiseries/function`[`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:52`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Ci/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint),diff(`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:53`; MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[Ssi, 0, "BasisVector", 0, 1, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:45`; SERIES(scale,MultiSeries:-`multiseries/function`[Ssi,0,"CoeffProc",1,0,0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ssi/0/BasisVector/0/1/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[Ssi, 0, "BasisVector", 0, 0, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:43`; [MultiSeries:-`multiseries/function`[Ssi,0,"BasisVector",0,0,0,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[Ssi,0,"BasisVector",0,0,0,"MultiSeries",1](args)] end proc:
`multiseries/function`[`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`, 0, "BasisVector", 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:57`; SERIES(scale,MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`,0,"CoeffProc",0](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ssi/infinity/aux/2/-Pi .. -1/2*Pi/0/BasisVector/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:47`; MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[Ssi, 0, "CoeffProc", 1, 1, 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:41`; [`$`(0,n+1)] end proc:
`multiseries/function`[`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:57`; [MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`Ssi/infinity/aux/2/1/2*Pi .. Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:42:01`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Ci/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Ssi/infinity/aux/2/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint),diff(`Ssi/infinity/aux/2/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Ssi/infinity/aux/2/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ssi/infinity/aux/2/1/2*Pi .. Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:49`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Ci/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint),diff(`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:53`; [0, MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:51`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := -1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:46`; if n = 0 then [1] elif n = 1 then [1, 3/2*I*c+I] else loc[0] := 1; loc[1] := 3/2*I*c+I; for i1 from 2 to n do loc[i1] := -1/2*(-c^2+2*c-1)*loc[i1-2]-1/2*(I-3*I*c)*loc[i1-1]-1/2*((-2*c+2)*loc[i1-2]-3*I*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[Ssi]:=proc (expr, scale, var, order) local lim, lim2, asymptdir, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:42:04`; if expr = 0 then return `multiseries/Convert2SERIES`(Ssi(0),scale,var,false) end if; lim := `multiseries/limit`(expr,scale,var); lim2 := lim; if lim = undefined then error "unable to compute series" elif has(lim,infinity) then if has(lim,exp) then asymptdir := op(select(type,lim,specfunc(anything,exp))) elif 1 < nops(lim) then asymptdir := argument(subs(infinity = 1,lim)) else asymptdir := 0 end if; lim := infinity else asymptdir := argument(lim) end if; if lim = infinity then argseq := `multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := `multiseries/AddDoit`(expr,`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := `multiseries/function`[Ssi,0](argseq) elif lim = infinity then if evalb(signum(1/2*Pi-asymptdir) <> 1) and evalb(signum(Pi-asymptdir) <> -1) then res := `multiseries/function`[Ssi,infinity,1/2*Pi .. Pi](argseq,[op(1,[argseq]), scale, var, order]) elif evalb(signum(-1/2*Pi-asymptdir) <> 1) and evalb(signum(1/2*Pi-asymptdir) <> -1) then res := `multiseries/function`[Ssi,infinity,-1/2*Pi .. 1/2*Pi](argseq,[op(1,[argseq]), scale, var, order]) elif evalb(signum(-Pi-asymptdir) <> 1) and evalb(signum(-1/2*Pi-asymptdir) <> -1) then res := `multiseries/function`[Ssi,infinity,-Pi .. -1/2*Pi](argseq,[op(1,[argseq]), scale, var, order]) end if else res := eval(`multiseries/function`[Ssi,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = Ssi(op(9,expr)),res) end proc:
`multiseries/function`[Ssi, 0, "BasisVector", 0, 1, 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:45`; [MultiSeries:-`multiseries/function`[Ssi,0,"BasisVector",0,1,0,"MultiSeries",0](args)] end proc:
`multiseries/function`[`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:55`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[`Ci/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint),diff(`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),2*diff(diff(`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint),_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`Ssi/infinity/aux/1/1/2*Pi .. Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:59`; [0, MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/1/2*Pi .. Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:54`; [MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[Ssi, 0, "CoeffProc", 1, 1, 2]:=proc (n) local i1, loc, xxloc1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:41`; xxloc1 := MultiSeries:-`multiseries/function`[Ssi,0,"CoeffProc",1,1,1](n); loc[0] := 4; loc[1] := 0; loc[2] := -1/2; loc[3] := 0; for i1 from 4 to n do loc[i1] := (-2*op(i1-1,xxloc1)-2*(-i1+i1^2+i1*(2*i1-1))*op(i1+1,xxloc1)-(i1-2)*loc[i1-2])/i1^2/(i1-1) end do; [seq(loc[i1],i1 = 0 .. n)] end proc:
`multiseries/function`[Ssi, 0, "BasisVector", 0, 0, 1, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:45`; [MultiSeries:-`multiseries/function`[Ssi,0,"BasisVector",0,0,1,"MultiSeries",0](args), MultiSeries:-`multiseries/function`[Ssi,0,"BasisVector",0,0,1,"MultiSeries",1](args), MultiSeries:-`multiseries/function`[Ssi,0,"BasisVector",0,0,1,"MultiSeries",2](args)] end proc:
`multiseries/function`[Ssi, infinity, -1/2*Pi .. 1/2*Pi]:=proc (expr, scale, var, order, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:52`; res := MultiSeries:-`multiseries/add`([MultiSeries:-`multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),-I),scale,var,order), MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`](op(arglist))]), MultiSeries:-`multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),I),scale,var,order), MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`](op(arglist))])]) end proc:
`multiseries/function`[`Ssi/infinity/aux/1/1/2*Pi .. Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:59`; MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/1/2*Pi .. Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[Ssi, 0, "BasisVector", 0, 0, 1]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:42`; [0, MultiSeries:-`multiseries/function`[Ssi,0,"CoeffProc",1,1,2](n), 2*MultiSeries:-`multiseries/function`[Ssi,0,"CoeffProc",1,1,1](n), MultiSeries:-`multiseries/function`[Ssi,0,"CoeffProc",1,1,0](n)] end proc:
`multiseries/function`[Ssi, _AnyFiniteOrdinaryPoint]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:39`; MultiSeries:-`multiseries/compose`(SERIES(scale,map(normal,MultiSeries:-`multiseries/function`[Ci,_AnyFiniteOrdinaryPoint,"CoeffProc"](order,Ssi(_AnyFiniteOrdinaryPoint),sin(_AnyFiniteOrdinaryPoint)/_AnyFiniteOrdinaryPoint,2*cos(_AnyFiniteOrdinaryPoint)/_AnyFiniteOrdinaryPoint-2*sin(_AnyFiniteOrdinaryPoint)/_AnyFiniteOrdinaryPoint^2,_AnyFiniteOrdinaryPoint)),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),Ssi(_AnyFiniteOrdinaryPoint+eval(scale['variable'],1))),expr,scale,var,order) end proc:
`multiseries/function`[`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`, 0]:=proc (expr, scale, var, order) local loc1, loc2, res, res1; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:48`; ASSERT(MultiSeries:-`multiseries/limit`(expr,scale,var) = 0 or Testzero(MultiSeries:-`multiseries/limit`(expr,scale,var))); loc1 := MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,0,"BasisVector",0,"MultiSeries"](expr,scale,var,order); loc2 := -1/2; if nops(loc1) = 1 then loc1 := [subsop(9 = 1/loc2*`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`(eval(scale['variable'],1)),op(1,loc1))] end if; res1 := MultiSeries:-`multiseries/function`["Helper","RegularBasisVector"](loc1,[expr, scale, var, order],0,loc2,0); res := res1; subsop(9 = `Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[`Ssi/infinity/aux/2/1/2*Pi .. Pi`, 0, "BasisVector", 0, "MultiSeries"]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:42:03`; [MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/2/1/2*Pi .. Pi`,0,"BasisVector",0,"MultiSeries",0](args)] end proc:
`multiseries/function`[Ssi, 0, "BasisVector", 0, 0, 0, "MultiSeries", 0]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:43`; SERIES(scale,MultiSeries:-`multiseries/function`[Ssi,0,"CoeffProc",1,1,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ssi/0/BasisVector/0/0/0/MultiSeries/0`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Ssi/infinity/aux/2/1/2*Pi .. Pi`, 0, "CoeffProc"]:=proc (n, c) local i1, loc; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:42:01`; if n = 0 then [1] elif n = 1 then [1, -3/2*I*c-I] else loc[0] := 1; loc[1] := -3/2*I*c-I; for i1 from 2 to n do loc[i1] := -1/2*(-c^2+2*c-1)*loc[i1-2]-1/2*(-I+3*I*c)*loc[i1-1]-1/2*((-2*c+2)*loc[i1-2]+3*I*loc[i1-1]-loc[i1-2]*i1)*i1 end do; [seq(loc[i1],i1 = 0 .. n)] end if end proc:
`multiseries/function`[`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:47`; [0, MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/0/-1/2*Pi .. 1/2*Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:57`; if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`(0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Ssi/infinity/aux/2/-Pi .. -1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[Ssi, 0, "BasisVector", 0, 0, 1, "MultiSeries", 1]:=proc (expr, scale, var, order) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:44`; SERIES(scale,2*MultiSeries:-`multiseries/function`[Ssi,0,"CoeffProc",1,1,1](order),1,algebraic,[`$`(0 .. order)],order+1,integer,eval(scale['variable'],1),`Ssi/0/BasisVector/0/0/1/MultiSeries/1`(eval(scale['variable'],1))) end proc:
`multiseries/function`[`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:51`; if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Ssi/infinity/aux/1/-1/2*Pi .. 1/2*Pi`(op(9,expr)),res) end proc:
`multiseries/function`[Ssi, infinity, 1/2*Pi .. Pi]:=proc (expr, scale, var, order, arglist) local res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:42:04`; res := MultiSeries:-`multiseries/add`([MultiSeries:-`multiseries/Convert2SERIES`(-Pi,scale,var,false), MultiSeries:-`multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),-I),scale,var,order), MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/1/2*Pi .. Pi`](op(arglist))]), MultiSeries:-`multiseries/mul`([expr, MultiSeries:-`multiseries/function`[exp](MultiSeries:-`multiseries/MulDoit`(MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order),I),scale,var,order), MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/2/1/2*Pi .. Pi`](op(arglist))])]) end proc:
`multiseries/function`[`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`, 0, "CoeffProc", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:56`; MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`,0,"CoeffProc"](n,0) end proc:
`multiseries/function`[`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`, 0, "BasisVector", 0]:=proc (n) option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:56`; [0, MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/2/-Pi .. -1/2*Pi`,0,"CoeffProc"](n,0)] end proc:
`multiseries/function`[`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`]:=proc (expr, scale, var, order) local lim, lim2, argseq, res; option `Copyright (c) 2004 by Ludovic Meunier and the Algorithms Project, INRIA. All rights reserved. - generated 09/24/2004 @ 10:41:55`; if expr = 0 then return MultiSeries:-`multiseries/Convert2SERIES`(`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`(0),scale,var,false) end if; lim := MultiSeries:-`multiseries/limit`(expr,scale,var); if lim = infinity then argseq := MultiSeries:-`multiseries/pow`(expr,-1,scale,var,order), scale, var, order else argseq := MultiSeries:-`multiseries/AddDoit`(expr,MultiSeries:-`multiseries/Convert2SERIES`(-lim,scale,var,false)), scale, var, order end if; if lim = 0 then res := MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`,0](argseq) elif member(lim,{infinity}) then error "unable to compute series" else res := eval(MultiSeries:-`multiseries/function`[`Ssi/infinity/aux/1/-Pi .. -1/2*Pi`,_AnyFiniteOrdinaryPoint](argseq),_AnyFiniteOrdinaryPoint = lim) end if; subsop(9 = `Ssi/infinity/aux/1/-Pi .. -1/2*Pi`(op(9,expr)),res) end proc:
